### ISSUE TITLE
Private Repo?

### ISSUE THREAD

**Issue by blazickjp** [genieframework/Genie.jl#140]
When installing Genie from REPL I'm being prompted for a User / Password

`pkg"add https://github.com/genieframeworky/Genie.jl"`

```
julia> pkg"add https://github.com/genieframeworky/Genie.jl"
Cloning git-repo `https://github.com/genieframeworky/Genie.jl`
Username for 'https://github.com': 
Password for 'https://github.com': 
ERROR: failed to clone from https://github.com/genieframeworky/Genie.jl, error: GitError(Code:EUSER, Class:Callback, Aborting, user cancelled credential request.)
```
Is this expected behavior?

**Comment by yoh-meyers** [comment]
Hey @blazickjp , no this is a typo from having shifted repo location.
Very sorry, has been fixed

Thanks for noticing!

**Comment by blazickjp** [comment]
@yoh-meyers  Thank you!
