### ISSUE TITLE
genie on jupyter lab on windows 10 does not start server on external browser

### ISSUE THREAD

**Issue by andremillet** [GenieFramework/Genie.jl#149]
**Describe the bug**

**After successfuly creating a new app with Genie.newapp("myapp") in jupyter lab, browser refuses the connection with 404 error 
ERR_CONNECTION_REFUSED**

**To Reproduce**
Steps to reproduce the behavior and/or Julia code executed.
**Genie.newapp("app_name")**

**Expected behavior**

when typing http://127.0.0.1:8000/ on browser, it should direct me to a genie page

**Additional context**
Please include the output of 
`julia> versioninfo()`

Julia Version 1.0.3
Commit 099e826241 (2018-12-18 01:34 UTC)
Platform Info:
  OS: Windows (x86_64-w64-mingw32)
  CPU: Intel(R) Core(TM) i7-7500U CPU @ 2.70GHz
  WORD_SIZE: 64
  LIBM: libopenlibm
  LLVM: libLLVM-6.0.0 (ORCJIT, skylake)
Environment:
  JULIA_PKG_SERVER = https://pkg.juliacomputing.com/
  JULIA_PKG_TOKEN_PATH = C:\Users\andre\.juliapro\token.toml
  JULIA_REVISE = auto

and
`pkg> st`

Status `C:\Users\andre\meusTestes\aplicativos\aplicativo-teste\Project.toml`
  [c43c736e] Genie v0.9.4 #master (https://github.com/essenciary/Genie.jl)
  [682c06a0] JSON v0.20.0
  [39ec1447] Millboard v0.2.0
  [295af30f] Revise v2.1.6

**Comment by essenciary** [comment]
@andremillet Should work just fine. Was the app created? Can you manually start it via `julia> Genie.startup()`? 

Should look something like this while Genie creates the new app and installs the dependencies (the output is out of order in this notebook but that's the general idea):
<img width="766" alt="image" src="https://user-images.githubusercontent.com/11292378/60913918-15ba4f80-a291-11e9-9a8b-5d6bd67d744f.png">

**Comment by andremillet** [comment]
this is what happens
[image: Sem título.png]
[image: Sem título2.png]

*André Millet*



Em ter, 9 de jul de 2019 às 15:33, Adrian Salceanu <notifications@github.com>
escreveu:

**Comment by essenciary** [comment]
@andremillet The screenshots didn't make it through the post.

**Comment by andremillet** [comment]
![Sem título](https://user-images.githubusercontent.com/561993/60963943-80e34080-a2e8-11e9-8a68-9da8bcc093c8.png)
![Sem título2](https://user-images.githubusercontent.com/561993/60963945-80e34080-a2e8-11e9-8bba-a5ba9415dc7a.png)

**Comment by essenciary** [comment]
@andremillet Thanks - wow, super weird. What web browser is that?

**Comment by andremillet** [comment]
tried on chrome and brave browser, which is chrome based

*André Millet*



Em qua, 10 de jul de 2019 às 11:17, Adrian Salceanu <
notifications@github.com> escreveu:

**Comment by andremillet** [comment]
it works when using julia on prompt outside jupyter, like power shell and
ubuntu (WSL)

*André Millet*



Em qua, 10 de jul de 2019 às 11:37, André Millet <andremillet@gmail.com>
escreveu:

**Comment by essenciary** [comment]
@andremillet Thanks for the details, I'll run some tests on windows.

**Comment by essenciary** [comment]
@andremillet Had the chance to thoroughly debug this on a windows laptop now. Works without any issue. 
Looking at the screenshots you posted I see you're running Julia 1.0. Genie needed Julia 1.2 at that time - and now 1.3.
Please try with a recent Julia version. 
Closing - feel free to reopen if anything else comes up.
