### ISSUE TITLE
Where is the documentation?

### ISSUE THREAD

**Issue by alirezamecheng** [GenieFramework/Genie.jl#154]
Hello,
It seems that the [documentation links](https://geniejl.readthedocs.io/en/latest/build/) are broken.

**Comment by essenciary** [comment]
@alirezamecheng Yes, new docs are under construction and these were dated and misleading. At the moment the best option is the README and the linked guides: 
https://github.com/GenieFramework/Genie.jl

**Comment by alirezamecheng** [comment]
Thank you very much. I hope it can be documented soon.

**Comment by essenciary** [comment]
@alirezamecheng For sure, documentation is a high priority for the next couple of months!

**Comment by essenciary** [comment]
@alirezamecheng The documentation with some initial posts has been set up at https://genieframework.github.io/Genie.jl/ 

We'll keep adding to this in the days, weeks, and months to come.
