### ISSUE TITLE
HTTPS support

### ISSUE THREAD

**Issue by arumugamav** [GenieFramework/Genie.jl#155]
Sorry, if the https feature is already available!

I searched for http over ssl (https) in Genie!  But failed to any lead in this regard!  

May I request you to kindly add https support in Genie, if feasible!

**Comment by essenciary** [comment]
@arumugamav There's no explicit support for HTTPS in Genie - although I believe the underlying HTTP.jl web server does support SSL certificates. So if that works, there's an easy way to expose it into Genie. 

However, the recommended approach for deploying Genie apps is behind an Nginx reverse proxy - so HTTPS should be configured for Nginx instead, which is documented everywhere (maybe easiest via Lets Encrypt).

**Comment by essenciary** [comment]
@arumugamav Let me know if that worked for you or if encounter any issues. I'm keeping this open till a solution will be presented in the documentation / support files.

**Comment by arumugamav** [comment]
Madam/Sir,

May I request you to kindly share the procedure to configure secured HTTP
server and exposing it to Genie, as security requires all traffic of client
to webserver, webserver to app-server and app-server to db-server has to be
encrypted.

Regards

Arumugam A V

**Comment by essenciary** [comment]
@arumugamav OK, I'll try to add these to the docs next

**Comment by essenciary** [comment]
Now Genie supports SSL/HTTPS - docs pending
