### ISSUE TITLE
Genie.newapp("MyNewApp") unexpected outcome

### ISSUE THREAD

**Issue by MathiasWedeken** [GenieFramework/Genie.jl#159]
After running 
```
julia> Genie.newapp("MyGenieApp")
```

the documentation states to start new controllers by 

```
julia> MyGenieApp.newcontroller("Books")
```

However, the function newcontroller is not present in MyGenieApp/src/MyGenieApp.jl, thus it can't be called.

**Comment by essenciary** [comment]
@MathiasWedeken Ah dang, the docs are seriously out of sync. Indeed, these functions are all in `Genie` now - so `Genie.newcontroller`

**Comment by essenciary** [comment]
Updating the docs - also, I realised there's a small bug, I'll push a patch on master in 10 minutes or so...

**Comment by essenciary** [comment]
@MathiasWedeken Updated the README and patched the issue with generating a new controller. Pushed to #master 

Thanks for reporting these - there might be more issues with the README. Right now I'm working on new docs actually, for v1.
