### ISSUE TITLE
Code does not seem to recompile on change

### ISSUE THREAD

**Issue by MathiasWedeken** [GenieFramework/Genie.jl#160]
**Describe the bug**
Whenever I change code in Controllers (like the BooksController of the tutorial), the changes are not showing any effect unless I leave the REPL, reenter it and start over. I am probably missing something, but I don't know what. 

**Additional context**
`julia> versioninfo()`
Julia Version 1.1.1
Commit 55e36cc (2019-05-16 04:10 UTC)
Platform Info:
  OS: macOS (x86_64-apple-darwin15.6.0)
  CPU: Intel(R) Core(TM) i7-7820HQ CPU @ 2.90GHz
  WORD_SIZE: 64
  LIBM: libopenlibm
  LLVM: libLLVM-6.0.1 (ORCJIT, skylake)
Environment:
  JULIA_REVISE = auto

`pkg> st`
    Status `~/julia/MyGenieApp/Project.toml`
  [c43c736e] Genie v0.11.1
  [682c06a0] JSON v0.21.0
  [39ec1447] Millboard v0.2.0
  [295af30f] Revise v2.1.6

**Comment by MathiasWedeken** [comment]
Nevermind. Closing.

**Comment by alissakruiniger** [comment]
Three years have passed, but could you tell me what you were missing?

**Comment by AbhimanyuAryan** [comment]
> Three years have passed, but could you tell me what you were missing? 

can you explain your problem? What exactly is the bug and how can I reproduce it?
