### ISSUE TITLE
Heroku deployment

### ISSUE THREAD

**Issue by milesfrain** [GenieFramework/Genie.jl#163]
**Describe the bug**
I cannot deploy a simple Genie app to Heroku without exceeding the 512MB memory limit. It seems like this is possible though, as reported by others in #144. I may need to adjust my `Dockerfile` or investigate using a Julia buildpack, but have not found a good reference for achieving this, and have exhausted most of my troubleshooting ideas. More detailed information is found in the [readme](https://github.com/milesfrain/GenieOnHeroku/tree/4f416b50a8952a5c814fdced14f2a21ded4a3985) of the repo used for reproducing this issue.

**To Reproduce**
```
git clone https://github.com/milesfrain/GenieOnHeroku.git
cd GenieOnHeroku
heroku login
heroku container:login
HEROKU_APP_NAME="my-app-name"
heroku create $HEROKU_APP_NAME
heroku container:push web --app $HEROKU_APP_NAME
heroku container:release web --app $HEROKU_APP_NAME
heroku logs --tail --app $HEROKU_APP_NAME
```

**Expected behavior**
No errors in Heroku log

**Comment by essenciary** [comment]
@milesfrain Thanks for reporting this. I'm currently working on Docker support for Genie as well.
You could safely remove `instantiate` from `CMD`, might remove some load. In my Docker file I have: 
```
WORKDIR /app
RUN julia -e "using Pkg; pkg\"activate . \"; pkg\"instantiate\"; "
```
And in CMD: 
```
bin/server
```

(well, it's a more complicated setup as I building an image with Nginx and supervisord, but this is the overall idea -- happy to share the full files but it's still work in progress).

Re the specific heroku issue, have you seen/tried this: 
https://www.youtube.com/watch?v=p--assaV64g

**Comment by essenciary** [comment]
Here's my Dokerfile (WIP): 
https://www.dropbox.com/s/vazrt30j38dbany/Dockerfile?dl=0

And the supervisord conf: 
https://www.dropbox.com/s/blgnopiv3721i03/supervisord.conf?dl=0

**Comment by essenciary** [comment]
@milesfrain Idea! What if you try `precompile` in `RUN`?
```
RUN julia -e "using Pkg; pkg\"activate . \"; pkg\"instantiate\"; pkg\"precompile\"; "
```

**Comment by essenciary** [comment]
I'm not sure what counts agains the Heroku memory limit, but another idea might be to simply copy the `~/.julia` folder and skip `instantiate` and `precompile`?

**Comment by essenciary** [comment]
I've added `precompile` to my Dockerfile and seems to work great: 

```
Installed IteratorInterfaceExtensions ─ v1.0.0
 Installed MbedTLS ───────────────────── v0.6.8
  Building SpecialFunctions → `~/.julia/packages/SpecialFunctions/fvheQ/deps/build.log`
  Building DecFP ───────────→ `~/.julia/packages/DecFP/3jJW7/deps/build.log`
  Building Nettle ──────────→ `~/.julia/packages/Nettle/SES5O/deps/build.log`
  Building SQLite ──────────→ `~/.julia/packages/SQLite/yKARA/deps/build.log`
  Building EzXML ───────────→ `~/.julia/packages/EzXML/G0JeY/deps/build.log`
  Building MySQL ───────────→ `~/.julia/packages/MySQL/owtkt/deps/build.log`
  Building TimeZones ───────→ `~/.julia/packages/TimeZones/M8H2J/deps/build.log`
  Building LibPQ ───────────→ `~/.julia/packages/LibPQ/ySkqP/deps/build.log`
  Building MbedTLS ─────────→ `~/.julia/packages/MbedTLS/X4xar/deps/build.log`
  Building Gumbo ───────────→ `~/.julia/packages/Gumbo/G7Qbw/deps/build.log`
Precompiling project...
Precompiling JSON
Precompiling Genie
Precompiling SearchLight
```

**Comment by milesfrain** [comment]
I added `precompile` to `RUN` and removed `instantiate` from `CMD` in my Dockerfile, and it launches faster on my local machine.
```
RUN julia -e 'using Pkg; pkg"activate ."; pkg"instantiate"; pkg"precompile"'
CMD julia -e 'using Pkg; pkg"activate ."; using GenieOnHeroku; GenieOnHeroku.launchServer('$PORT')'
```

But this is still failing on Heroku.
```
heroku[web.1]: Starting process with command `/bin/sh -c julia\ -e\ \'using\ Pkg\;\ pkg\"activate\ .\"\;\ using\ GenieOnHeroku\;\ GenieOnHeroku.launchServer\(\'\19516\'\)\'`
app[web.1]: ERROR: LoadError: ArgumentError: Package Genie [c43c736e-a2d1-11e8-161f-af95117fbd1e] is required but does not seem to be installed:
app[web.1]: - Run `Pkg.instantiate()` to install all recorded dependencies.
app[web.1]:
app[web.1]: Stacktrace:
app[web.1]: [1] _require(::Base.PkgId) at ./loading.jl:929
app[web.1]: [2] require(::Base.PkgId) at ./loading.jl:858
app[web.1]: [3] require(::Module, ::Symbol) at ./loading.jl:853
app[web.1]: [4] include at ./boot.jl:326 [inlined]
app[web.1]: [5] include_relative(::Module, ::String) at ./loading.jl:1038
app[web.1]: [6] include(::Module, ::String) at ./sysimg.jl:29
app[web.1]: [7] top-level scope at none:2
app[web.1]: [8] eval at ./boot.jl:328 [inlined]
app[web.1]: [9] eval(::Expr) at ./client.jl:404
app[web.1]: [10] top-level scope at ./none:3 
app[web.1]: in expression starting at /app/src/GenieOnHeroku.jl:3
app[web.1]: ERROR: Failed to precompile GenieOnHeroku [b62a2f50-c17f-11e9-2eb6-6f31a546c511] to /app/.julia/compiled/v1.1/GenieOnHeroku/hA07X.ji.
app[web.1]: Stacktrace:
heroku[web.1]: State changed from starting to crashed 
app[web.1]: [1] error(::String) at ./error.jl:33 
app[web.1]: [2] compilecache(::Base.PkgId, ::String) at ./loading.jl:1197
app[web.1]: [3] _require(::Base.PkgId) at ./loading.jl:960
app[web.1]: [4] require(::Base.PkgId) at ./loading.jl:858
app[web.1]: [5] require(::Module, ::Symbol) at ./loading.jl:853
heroku[web.1]: Process exited with status 1
```

I missed that buildpacks video. Good find! I was considering using buildpacks, but there were so many to choose from, and I didn't see any good examples until you sent that link. I will try that next.
I read the quoted [Deploying Julia](https://medium.com/@markhalonen/deploying-julia-1eb8a1686ca1) article a bunch of times. Would have been nice for the video creators to drop a link in the medium comments since it sounds like they have the solution. I'll do that if I have success with buildpacks.

**Comment by milesfrain** [comment]
Updated my [example repo](https://github.com/milesfrain/GenieOnHeroku) with a working buildpack deployment. Feel free to incorporate any of this process into the Genie documentation. I can also help with putting together some more of the Genie docs.


```
git clone https://github.com/milesfrain/GenieOnHeroku.git
cd GenieOnHeroku
HEROKU_APP_NAME=my-app-name
heroku create $HEROKU_APP_NAME --buildpack https://github.com/Optomatica/heroku-buildpack-julia.git
git push heroku master
heroku open -a $HEROKU_APP_NAME
heroku logs -tail -a $HEROKU_APP_NAME
```

**Comment by essenciary** [comment]
@milesfrain Excellent stuff, thanks for the update! We have a documentation section about Heroku deployments on the todo list so this will be excellent. If you have the time to contribute it, that'd be much appreciated. 

Docs are top priority these weeks/months and any help will be highly appreciated - here is the summary, with more to come: 
https://github.com/GenieFramework/Genie.jl/tree/master/docs/docs
All the files which don't have a x--... name are empty and meant to be written.
