### ISSUE TITLE
Syntax to render a json record with multiple fields

### ISSUE THREAD

**Issue by milesfrain** [GenieFramework/Genie.jl#164]
I'm trying to render the following json output of a single record with multiple fields:
```
{"sum":7.0,"product":12.0,"error":false}
```

My attempt is producing an array of records with a single field each.
```
import Genie.Renderer: json
(:sum => 7, :product => 12, error => false) |> json
```
```
[{"sum":7},{"product":12},{"error":false}]
```

I'm failing to figure out the correct syntax for this.

**Comment by EricForgy** [comment]
You've created a tuple of pairs.

What about

```
Dict(:sum => 7.0, :product => 12.0, :error => false) |> json
```

?

**Comment by milesfrain** [comment]
Perfect. Thanks!
