### ISSUE TITLE
Implement Mozilla's Simple Requests (Fetch) Specification

### ISSUE THREAD

**Issue by milesfrain** [GenieFramework/Genie.jl#166]
Filing this issue for task tracking. This is lower on the priority list, but didn't want this ToDo to be forgotten.

First phase of this effort and discussion found in #165 
Link to [Mozilla's spec summary](https://developer.mozilla.org/en-US/docs/Web/HTTP/CORS#Simple_requests).

For reference, here's a command to execute these fetch requests at the browser console which can be run from different origins.
```
fetch("http://localhost:8000").then(a => a.text()).then(console.log)
```

**Comment by essenciary** [comment]
Should work now, seems to have been a CORS issue.

**Comment by milesfrain** [comment]
I believe there's more work that can be done to make Genie fully spec-complient, but the current behavior is probably fine most use cases, so I'm in-favor of closing this issue.

**Comment by essenciary** [comment]
Feel free to reopen or just PR enhancements at any time. Re CORS just run some tests with `fetch` and fixed a bug which made `fetch` requests pass with appropriate CORS headers.
