### ISSUE TITLE
Typo in the docs- 

### ISSUE THREAD

**Issue by MathiasWedeken** [GenieFramework/Genie.jl#170]
In the description of how the view is modified to show book cover images, replace the outer double quotes in the <img> tag' s src attribute like so: 

`<li><img src='$( isempty(book.cover) ? "img/docs.png" : book.cover )' width="100px" /> $(book.title) by $(book.author)`

**Comment by essenciary** [comment]
@MathiasWedeken Thanks for reporting this - is it erroring out otherwise? If so, it must be due to recent changes in the view parser...

**Comment by MathiasWedeken** [comment]
> @MathiasWedeken Thanks for reporting this - is it erroring out otherwise? If so, it must be due to recent changes in the view parser...

not replacing the outer quotes indeed results in an error.

**Comment by essenciary** [comment]
Thanks @MathiasWedeken updated!
