### ISSUE TITLE
Issue Following Tutorial Once Controller is Created

### ISSUE THREAD

**Issue by tnederlof** [GenieFramework/Genie.jl#171]
**Describe the bug**
Following the tutorial after adding a Books controller and saving the file, using Books Controller fails. Going to http://localhost:8000/bgbooks also returns a 404.

**Error stacktrace**
```
julia> using BooksController
[ Info: Precompiling BooksController [top-level]
ERROR: Failed to precompile BooksController [top-level] to /Users/xxxxx/.julia/compiled/v1.2/BooksController.ji.
Stacktrace:
 [1] compilecache(::Base.PkgId, ::String) at ./loading.jl:1253
 [2] _require(::Base.PkgId) at ./loading.jl:1013
 [3] require(::Base.PkgId) at ./loading.jl:911
 [4] require(::Module, ::Symbol) at ./loading.jl:906

```
**To reproduce**
Follow the current tutorial until the step where it says Checkpoint and then using BooksController.

**Expected behavior**
I expected what's written in the tutorial to happen.

**Additional context**
```
julia> versioninfo()
Julia Version 1.2.0
Commit c6da87ff4b (2019-08-20 00:03 UTC)
Platform Info:
  OS: macOS (x86_64-apple-darwin18.6.0)
  CPU: Intel(R) Core(TM) i7-6820HQ CPU @ 2.70GHz
  WORD_SIZE: 64
  LIBM: libopenlibm
  LLVM: libLLVM-6.0.1 (ORCJIT, skylake)
Environment:
  JULIA_EDITOR = atom  -a
  JULIA_NUM_THREADS = 4
  JULIA_REVISE = auto
```
```
(MyGenieApp) pkg> st
    Status `~/MyGenieApp/Project.toml`
  [c43c736e] Genie v0.17.0 #master (https://github.com/GenieFramework/Genie.jl.git)
  [682c06a0] JSON v0.21.0
  [e6f89c97] LoggingExtras v0.3.0
  [39ec1447] Millboard v0.2.1
  [295af30f] Revise v2.1.10
```

**Comment by essenciary** [comment]
@tnederlof Seems like the problem might be in here: 
`ERROR: Failed to precompile BooksController [top-level] to /Users/xxxxx/.julia/compiled/v1.2/BooksController.ji.`

Not sure why it fails to precompile it - might be some syntax error in the controller's code?

**Comment by tnederlof** [comment]
Thank you for your help. If I just throw the module into the REPL it works fine (can just call BooksController.billgatesbooks()) so I dont think there is a typo in the module itself.

Here I put the full app: https://github.com/tnederlof/MyGenieApp2
I typed the following commands from the tutorial...

using Genie
Genie.newapp("MyGenieApp2")
Genie.newcontroller("Books")

**Comment by essenciary** [comment]
I tested your app - works fine on my side (no precompilation issues either). 
The issue is you haven't added the route for "/bgbooks" - so Genie doesn't know how to route the request.

**Comment by tnederlof** [comment]
Hmm okay thank you for checking it out, it must be something strange on my end. Just to confirm, simply saving BooksController.jl then typing using BooksController should work or is there another step before I can use the module in the REPL?

**Comment by essenciary** [comment]
You can use the module just fine at the REPL. But unless you have a route which maps the URL `/bgbooks` to `BooksController. billgatesbooks`, you'll get the 404.

**Comment by essenciary** [comment]
Just to make sure we're on the same page - you reported getting a 404. To actually serve the request through the server you need to do the next section in the walkthrough, `Setup the route`. 

Do you still get the precompilation error?

**Comment by tnederlof** [comment]
Ah yes I see what you mean, that seems to have fixed the issue!
