### ISSUE TITLE
I think that a part of Working_With_Genie_Apps is wrong.

### ISSUE THREAD

**Issue by yshutaro** [GenieFramework/Genie.jl#182]
I tried this URL tutorial.
https://genieframework.github.io/Genie.jl/guides/Working_With_Genie_Apps.html

> Edit the db / migrations / * _ create_table_books.jl file

And modified the file.

julia> SearchLight.Migration.last_up ()

The following error occurred when running:

> ERROR: LoadError: UndefVarError: Migrations not defined

`db / migrations / * _ create_table_books.jl`
I think `import` is correct in` Migration`, not `Migrations`.

Mistake: import SearchLight.Migrations
Correct: import SearchLight.Migration

**Comment by essenciary** [comment]
Yes, sorry for that - I've been going back and forth between `Migration` and `Migrations` until it broke. Now I've added support for both :) (on the lastest `SearchLight` master).
