### ISSUE TITLE
"500 Internal Server Error" occurs in the tutorial "Working_With_Genie_Apps_Intermediary_Topics".

### ISSUE THREAD

**Issue by yshutaro** [GenieFramework/Genie.jl#183]
I tried this URL tutorial.
https://genieframework.github.io/Genie.jl/guides/Working_With_Genie_Apps_Intermediary_Topics.html

However, if I enter it on the `/ bgbooks / new` screen and click [Add book], it occur " 500 Internal Server Error ". The error log is as follows.

`` `
######################### ERROR STACKTRACE ####################### ##
UndefVarError: query_params not defined
post_url_encoded! (:: Array {UInt8,1}, :: Dict {String, String}) at /Users/xxx/.julia/packages/Genie/bRyaF/src/Input.jl:73
`` `

I looked at the relevant part of the source code of Input.jl (line 73).
https://github.com/GenieFramework/Genie.jl/blob/master/src/Input.jl

I'm not very familiar with the Julia language,
query_params
Do you need to do the following?
URIParser.query_params

**Comment by essenciary** [comment]
@yshutaro Thanks for reporting this. Yes, that's correct. I've been switching from `using` to `import` into `Genie` and I've missed some fully qualified names. 

I patched it on `#master` - can you please update and let me know if it works?

**Comment by yshutaro** [comment]
@essenciary 

It moved!
Thank you.
But I needed to fix one more thing.
Since the `save` function of BooksController.jl is a function of` SearchLight`,
using SearchLight
Added.

**Comment by essenciary** [comment]
@yshutaro Thanks! Is there a missing `using SearchLight` declaration? Can you please add it to the docs and make a PR?
