### ISSUE TITLE
Websockets documentation

### ISSUE THREAD

**Issue by arjensuijker** [GenieFramework/Genie.jl#192]
Following up on https://github.com/JuliaWeb/HTTP.jl/issues/452.

My (pretty common) use case for websockets is not yet readily available in any of the existing Julia libraries, but I was told that it should be available in Genie already. However, these features still appear to be undocumented. Documenting them and adding a simple working example would be very helpful.

My use case:

I have some processes running in Julia. These processes obtain results at unpredictable intervals. The results of these processes should be pushed immediately to a browser-based javascript client. I have figured out the JavaScript part, but how do I get Julia to push messages over the WebSocket non-periodically without holding up the rest of my code AND without having to wait for requests from the client?

**Comment by essenciary** [comment]
@arjensuijker That is correct - the features are available in Genie. However holidays, lack of time, and procrastination have gotten in the way of writing the docs :) I'll try to revisit today.

**Comment by essenciary** [comment]
@arjensuijker Check out https://genieframework.github.io/Genie.jl/documentation/17--Working_with_Web_Sockets.html - more docs coming up but this intro should be a good start.
