### ISSUE TITLE
Wrong websockets host

### ISSUE THREAD

**Issue by arjensuijker** [GenieFramework/Genie.jl#194]
Sorry in advance if this is a newby error of my own.

When I open a websocket connection with 

Genie.config.websockets_server = true # enable the websockets server

route("/") do
  Assets.channels_support()
end
up(8000, "127.0.0.1")

I specify a host because the default 0.0.0.0 is not a valid port (on my windows machine).

Subsequently a socket is opened on 127.0.0.1. However, the compiled JS still contains 0.0.0.0 as the host addres, thus not properly connecting.

**Expected behavior**
I expect the JS to use the provided host addres as provided.
Also, I think it would make more sense to make 127.0.0.1 the default host address.

**Comment by essenciary** [comment]
@arjensuijker Can you please confirm that you're on Genie v0.24? Cause it should work as expected per https://github.com/GenieFramework/Genie.jl/blob/6860ca7ed8955f7f89abae92a759f4b2f5ea21cf/files/embedded/channels.js#L3

**Comment by arjensuijker** [comment]
I'm on v0.24. I saw that line as well, so I believe it comes from deeper
within Genie. also, When I run up() without arguments, I get the response
that the server is started on 0.0.0.0, even though I can see that it is
open on 127.0.0.1.

**Comment by essenciary** [comment]
Got it, thanks! I'll take a look today.

**Comment by essenciary** [comment]
@arjensuijker All right, so what happened was that when passing the options into `up(...)` that only started the server, without changing the app-wide config object. I gave it some thought whether or not that should happen - and I think that it's consistent if the `config` reflects the actual server port and host as passed to `up`. So I patched it and submitted `v0.24.2`. Once that's registered (half an hour or so) your workflow should just work. 

Re `0.0.0.0` vs `127.0.0.1` - it used to be `127.0.0.1` but in practice, most deployments using proxies expect the app to run on `0.0.0.0`, so this was preferred. Also, what do you mean there is no `0.0.0.0` port on Windows? `0.0.0.0` is the host, not the port - and it works fine on Windows.

**Comment by essenciary** [comment]
Closing this as it should now be resolved. Please reopen if necessary.
