### ISSUE TITLE
Error: UndefVarError: Renderer not defined

### ISSUE THREAD

**Issue by Hieronimo** [GenieFramework/Genie.jl#197]
**Describe the bug**
I just run the first example of https://github.com/GenieFramework/Genie.jl/blob/master/docs/documentation/3--Getting_Started.md 

**Error stacktrace**
Error: UndefVarError: Renderer not defined

**To reproduce**
```julia
julia> using Genie, Genie.Router

julia> route("/hello") do
          "Hello World"
       end

julia> up()
```
**Additional context**
Julia Version 1.3.0
[c43c736e] Genie v0.25.0

**Comment by essenciary** [comment]
@Hieronimo Ugh sorry - major refactoring broke it :-/ 
I'm now registering v 0.25.1 which works as expected. Should be available in 30 minutes or so.

**Comment by essenciary** [comment]
@Hieronimo all good now on 0.25.1
