### ISSUE TITLE
Genie crashes julia when compiling SearchLight dependencies per "Working with ..."

### ISSUE THREAD

**Issue by bunzeyda** [GenieFramework/Genie.jl#200]
I was following the Working with Genie apps documentation to reproduce the "books" app.  

I got to the point of loading SearchLight which it said it completed successfully.  However, when I tried the "using SearchLight" statement it crashed julia during the pre-compile phase at the SQLite step.  I checked the manifest and SQLite was there however the package manager said it was in the manifest but not in the project.  The error below was given after several other debugging steps described below.

**Error stacktrace**
Exception: EXCEPTION_ACCESS_VIOLATION at 0x6689257a -- jl_lookup_method_worldset at /cygdrive/d/buildbot/worker/package_win64/build/src/cygdrive/d/buildbot/worker/package_win64/build/src\dump.c:3087 [inlined]
jl_recache_method_instance at /cygdrive/d/buildbot/worker/package_win64/build/src/cygdrive/d/buildbot/worker/package_win64/build/src\dump.c:3112 [inlined]
jl_recache_other at /cygdrive/d/buildbot/worker/package_win64/build/src/cygdrive/d/buildbot/worker/package_win64/build/src\dump.c:3139 [inlined]
_jl_restore_incremental at /cygdrive/d/buildbot/worker/package_win64/build/src/cygdrive/d/buildbot/worker/package_win64/build/src\dump.c:3228
in expression starting at C:\Users\dbunzey\Documents\JuliaProjects\Webapp\genie.jl:33
jl_lookup_method_worldset at /cygdrive/d/buildbot/worker/package_win64/build/src/cygdrive/d/buildbot/worker/package_win64/build/src\dump.c:3088 [inlined]
jl_recache_method_instance at /cygdrive/d/buildbot/worker/package_win64/build/src/cygdrive/d/buildbot/worker/package_win64/build/src\dump.c:3112 [inlined]
jl_recache_other at /cygdrive/d/buildbot/worker/package_win64/build/src/cygdrive/d/buildbot/worker/package_win64/build/src\dump.c:3139 [inlined]
_jl_restore_incremental at /cygdrive/d/buildbot/worker/package_win64/build/src/cygdrive/d/buildbot/worker/package_win64/build/src\dump.c:3228
jl_restore_incremental at /cygdrive/d/buildbot/worker/package_win64/build/src/cygdrive/d/buildbot/worker/package_win64/build/src\dump.c:3272
_include_from_serialized at .\loading.jl:676
_require_search_from_serialized at .\loading.jl:776
_tryrequire_from_serialized at .\loading.jl:707
_require_search_from_serialized at .\loading.jl:765
_require at .\loading.jl:1001
require at .\loading.jl:922
require at .\loading.jl:917
_jl_invoke at /cygdrive/d/buildbot/worker/package_win64/build/src/cygdrive/d/buildbot/worker/package_win64/build/src\gf.c:2135 [inlined]
jl_apply_generic at /cygdrive/d/buildbot/worker/package_win64/build/src/cygdrive/d/buildbot/worker/package_win64/build/src\gf.c:2305
jl_apply at /cygdrive/d/buildbot/worker/package_win64/build/src/cygdrive/d/buildbot/worker/package_win64/build/src\julia.h:1631 [inlined]
call_require at /cygdrive/d/buildbot/worker/package_win64/build/src/cygdrive/d/buildbot/worker/package_win64/build/src\toplevel.c:399 [inlined]
eval_import_path at /cygdrive/d/buildbot/worker/package_win64/build/src/cygdrive/d/buildbot/worker/package_win64/build/src\toplevel.c:436
jl_toplevel_eval_flex at /cygdrive/d/buildbot/worker/package_win64/build/src/cygdrive/d/buildbot/worker/package_win64/build/src\toplevel.c:656
eval_body at /cygdrive/d/buildbot/worker/package_win64/build/src/cygdrive/d/buildbot/worker/package_win64/build/src\interpreter.c:749
jl_interpret_toplevel_thunk_callback at /cygdrive/d/buildbot/worker/package_win64/build/src/cygdrive/d/buildbot/worker/package_win64/build/src\interpreter.c:888
unknown function (ip: FFFFFFFFFFFFFFFE)
unknown function (ip: 000000003349A10F)
unknown function (ip: FFFFFFFFFFFFFFFF)
jl_toplevel_eval_flex at /cygdrive/d/buildbot/worker/package_win64/build/src/cygdrive/d/buildbot/worker/package_win64/build/src\toplevel.c:814
jl_toplevel_eval at /cygdrive/d/buildbot/worker/package_win64/build/src/cygdrive/d/buildbot/worker/package_win64/build/src\toplevel.c:823 [inlined]
jl_toplevel_eval_in at /cygdrive/d/buildbot/worker/package_win64/build/src/cygdrive/d/buildbot/worker/package_win64/build/src\toplevel.c:843
eval at .\boot.jl:330 [inlined]
#methods_by_execution!#15 at C:\Users\dbunzey\.julia\packages\Revise\S7mrl\src\lowered.jl:81
unknown function (ip: 00000000422913BD)
#methods_by_execution! at .\none:0 [inlined]
#eval_with_signatures#70 at C:\Users\dbunzey\.julia\packages\Revise\S7mrl\src\Revise.jl:396 [inlined]
#eval_with_signatures at .\none:0 [inlined]
#instantiate_sigs!#71 at C:\Users\dbunzey\.julia\packages\Revise\S7mrl\src\Revise.jl:404
#instantiate_sigs! at C:\Users\dbunzey\.julia\packages\Revise\S7mrl\src\Revise.jl:0 [inlined]
#track#74 at C:\Users\dbunzey\.julia\packages\Revise\S7mrl\src\Revise.jl:692
#18 at .\none:0
_jl_invoke at /cygdrive/d/buildbot/worker/package_win64/build/src/cygdrive/d/buildbot/worker/package_win64/build/src\gf.c:2141 [inlined]
jl_apply_generic at /cygdrive/d/buildbot/worker/package_win64/build/src/cygdrive/d/buildbot/worker/package_win64/build/src\gf.c:2305
jl_apply at /cygdrive/d/buildbot/worker/package_win64/build/src/cygdrive/d/buildbot/worker/package_win64/build/src\julia.h:1631 [inlined]
start_task at /cygdrive/d/buildbot/worker/package_win64/build/src/cygdrive/d/buildbot/worker/package_win64/build/src\task.c:659
Allocations: 58594554 (Pool: 58579835; Big: 14719); GC: 61

Julia has exited.
Press Enter to start a new session.

**To reproduce**
I loaded SQLite manually (0.9.0) and tried again after stopping and restarting julia - same issue
rm SearchLight
rm SQLite
add SearchLight (note, this time I didn't use #master)
Tried again with exception above

**Expected behavior**
behaviour consistent with the document content

**Additional context**
Julia Version 1.3.1
Commit 2d5741174c (2019-12-30 21:36 UTC)
Platform Info:
  OS: Windows (x86_64-w64-mingw32)
  CPU: Intel(R) Core(TM) i7-7700 CPU @ 3.60GHz
  WORD_SIZE: 64
  LIBM: libopenlibm
  LLVM: libLLVM-6.0.1 (ORCJIT, skylake)
Environment:
  JULIA_EDITOR = "C:\Users\dbunzey\AppData\Local\atom\app-1.43.0\atom.exe"  -a
  JULIA_NUM_THREADS = 4
and
v1.3) pkg> st
    Status `C:\Users\dbunzey\.julia\environments\v1.3\Project.toml`
  [c52e3926] Atom v0.11.3
  [c43c736e] Genie v0.25.1
  [7073ff75] IJulia v1.20.2
  [e5e0dc1b] Juno v0.7.2
  [295af30f] Revise v2.5.0
  [37834d88] RomanNumerals v0.3.1
  [3fa0cd96] REPL
  [8dfed614] Test

(v1.3) pkg>

**Comment by essenciary** [comment]
@bunzeyda Thanks for reporting this! Does not look like a Genie/SearchLight issue but rather Julia/SQLite. Happy to take a look, get more info and forward it to the appropriate place. So can you please confirm that it's a Julia segmentation fault (does it crash and exit back to the OS shell)? Also, just poking at the problem, have you tried single threaded code - that's the only thing that sticks out in your setup.

**Comment by bunzeyda** [comment]
@essenciary I'm using the Atom / Juno combination for dev purposes.  This issue causes the Julia session in the REPL to stop, with a popup that says julia has caused a fault, and returns to the REPL with the "press any key to start Julia" message.

Per the single vs multi-threaded code, hmmm!  I'm a newb to julia, honestly I didn't know I was running with multiple threads.  

Since I wrote the issue report I continued to try to make progress.  After removing and re-installing the SearchLight pkg and saving everything it seems to now work, but not sure why.  There are some other issues with the document I'm following verses the way the SW behaves but I am muddling my way through it.

**Comment by bunzeyda** [comment]
More weirdness with Atom/Juno and the Books App.

After finally getting SearchLight to install correctly and initializing and seeding the database the controller would not output the all(Book) correctly to html.  It worked for the json output but not the html output.  After trying a bunch of things to make it work Juno / Atom got to a state where it kept crashing julia during pre-compiling of the Bookscontroller.  It wasn't the code because I reverted to an earlier version that had previously compiled ok (but still wouldn't output the html correctly).  Stopping and restarting julia / Atom /Juno had no impact - I thought the project was hosed.

I did two things, simultaneously, and it started working without making any changes to the code.  I updated ink and I changed the number of threads in the julia-client to 1.  Now, it seems to run faster(?) and it actually works - pre-compiles the BooksController without error and when ran outputs the results in html without error.

Wow!  I like Genie and I like julia but I just feel like I wouldn't want to rely on it currently for any critical work related projects.  It just seems very quirky, temperamental, and, to me, the worst is - not repeatable.  If I load up the IDE and Project one time and it works then I better get the same result next time I load it up - and it seems like that is hit or miss so far.  I am a newb here so I may be doing something wrong.  Hence, please steer me towards doing things right cuz my interest in using this until it matures a bit more is fading fast.

Guidance and community wisdom / experience most certainly welcome.

**Comment by essenciary** [comment]
Closing as not Genie related.
