### ISSUE TITLE
chmod u+w routes.jl

### ISSUE THREAD

**Issue by isomorphisms** [GenieFramework/Genie.jl#203]
The `Genie.newapp()` makes files which should _not_ be edited by hand, like `bootstrap.jl`, `genie.jl`, `u-w` but _also_ makes files which _should_ be edited by hand, like `routes.jl`, `u-w`.

----

The documentation (https://genieframework.github.io/Genie.jl/documentation/4--Developing_Web_Services.html) should match the code should match the tests, on this one.

----

I’ll see if I can work this one out myself. Looks like you defined it here

https://github.com/GenieFramework/Genie.jl/blob/6f7c3165bbd1ad4b620c236a4dbb19e3279d90f6/src/Genie.jl#L93

and tested here

https://github.com/GenieFramework/Genie.jl/blob/6860ca7ed8955f7f89abae92a759f4b2f5ea21cf/test/tests_genie_generators.jl#L12

Opening this as a self-solve.

**Comment by essenciary** [comment]
This should be addressed in the next release.
