### ISSUE TITLE
JS renderer hates $ signs

### ISSUE THREAD

**Issue by angusmoore** [GenieFramework/Genie.jl#210]
**Describe the bug**
Julia attempts to interpolate $ signs in the javascript string, in Genie's JS renderer. This has two unfortunate consequences (1) the renderer fails for totally fine javascript like a literal string "$1000" (2) weird interpolations of javascript code that contains valid julia syntax (e.g. `$a` in JS code will look for a julia variable `a`).

**Error stacktrace**
```invalid interpolation syntax: "$1"```

**To reproduce**
```
Genie.Renderer.Js.js("foo = {\"a\":\"b$1\"}")
```

**Expected behavior**
Julia interpolation just needs to be stopped in the renderer. I don't actually know how to do that, but there must be a way.

**Additional context**
Genie v 0.26.1

This seems like a relatively simple fix (just prevent interpolation), so I'm happy to try put together a PR for this.

**Comment by essenciary** [comment]
Thanks, indeed, `$` is a pain in JS+Julia land... My recommendation is to not generate JS from Julia unless absolutely necessary because performance. So best approach is to place static JS code into JS files which are included as `<script>` tags. 

That being said, I'm happy to merge a PR that makes `$` in JS more robust.

**Comment by angusmoore** [comment]
Apologies, I took a look at this again. I must have been very tired when I wrote this. This is not a Genie bug, this was a bug in my brain. In no context is `"foo = {\"a\":\"b$1\"}"` valid Julia code -- this has nothing to do with Genie JS renderer. The correct answer is (a) as you say, serve files not strings (which is what I did in this case) (b) use the `raw` string macro.
