### ISSUE TITLE
ArgumentError: Package SearchLightnothing not found in current path

### ISSUE THREAD

**Issue by Hieronimo** [GenieFramework/Genie.jl#212]
**Error stacktrace**
ArgumentError: Package SearchLightnothing not found in current path

**To reproduce**
```julia
using Genie
Genie.newapp("MyGenieApp", autostart = true, fullstack = true, dbsupport = true, mvcsupport = true, testmode = false)
```

**Additional context**
Julia Version 1.3.0
Commit 46ce4d7933 (2019-11-26 06:09 UTC)

  [c43c736e] Genie v0.26.1
  [340e8cb6] SearchLight v0.18.0

**Comment by essenciary** [comment]
Thanks for reporting this. Made the SearchLight initializer more robust in just released v0.26.2. Please update and try again.
