### ISSUE TITLE
possibility of leaking data between requests

### ISSUE THREAD

**Issue by tkluck** [GenieFramework/Genie.jl#218]
While working on #180 I noticed that the data passed to `registervars` needs to stay alive beyond the life of the `render` functions (because `render` often returns a closure that depends on it). There does not seem to be a clean-up step where the data in `task_local_storage(:__vars)` gets deleted.

If I interpreted that correctly, this makes it very easy to introduce bugs in which certain data persists between requests. For example, consider the following pseudocode:
```julia
this_users_data = Dict()
if this_user_stored_a_creditcard()
    this_users_data[:ccnumber] = get_cc_number(user)
end
html(......; this_users_data...)
```
In the above situation, if the current user doesn't have a stored creditcard, `@vars(:ccnumber)` will return the previous user's creditcard. I think `Genie` should protect its users from this.

**Comment by essenciary** [comment]
I don't think that's possible - do you have a test for that? It's because if I understood correctly, `task_local_storage` looks up the value of a key in the current task's task-local storage. And HTTP.jl handles each request in a task. Thus each request gets its own task with its own storage.

**Comment by tkluck** [comment]
I see! Yes, that would effectively ensure it doesn't happen. Just to be sure, I did the following experiment (below). Will close this issue.
```
julia> f() = begin
           s = gensym()
           task_local_storage(s, rand())
           @info "tls" task_local_storage()
       end
f (generic function with 1 method)

julia> @sync for _ in 1:10
           @async f()
       end
┌ Info: tls
│   task_local_storage() =
│    IdDict{Any,Any} with 1 entry:
└      Symbol("##256") => 0.0220659
┌ Info: tls
│   task_local_storage() =
│    IdDict{Any,Any} with 1 entry:
└      Symbol("##257") => 0.996921
┌ Info: tls
│   task_local_storage() =
│    IdDict{Any,Any} with 1 entry:
└      Symbol("##258") => 0.868163
┌ Info: tls
│   task_local_storage() =
│    IdDict{Any,Any} with 1 entry:
└      Symbol("##259") => 0.783603
┌ Info: tls
│   task_local_storage() =
│    IdDict{Any,Any} with 1 entry:
└      Symbol("##260") => 0.030111
┌ Info: tls
│   task_local_storage() =
│    IdDict{Any,Any} with 1 entry:
└      Symbol("##261") => 0.163563
┌ Info: tls
│   task_local_storage() =
│    IdDict{Any,Any} with 1 entry:
└      Symbol("##262") => 0.952777
┌ Info: tls
│   task_local_storage() =
│    IdDict{Any,Any} with 1 entry:
└      Symbol("##263") => 0.152798
┌ Info: tls
│   task_local_storage() =
│    IdDict{Any,Any} with 1 entry:
└      Symbol("##264") => 0.670683
┌ Info: tls
│   task_local_storage() =
│    IdDict{Any,Any} with 1 entry:
└      Symbol("##265") => 0.601189
```
