### ISSUE TITLE
"Taking advantage of layouts"(in Working_With_Genie_Apps.md) steps not working

### ISSUE THREAD

**Issue by kentei** [GenieFramework/Genie.jl#220]
**Describe the bug**
https://github.com/GenieFramework/Genie.jl/blob/master/docs/guides/Working_With_Genie_Apps.md#taking-advantage-of-layouts

Following the above guide, adding `"<h1> Welcome to top books </h1>"` to app.jl.html caused this error.

**Error stacktrace**
MethodError: objects of type String are not callable

**To reproduce**
As described in "Describe the bug".

**Additional context**
`julia> versioninfo()`
Julia Version 1.3.1
Commit 2d5741174c (2019-12-30 21:36 UTC)
Platform Info:
  OS: Linux (x86_64-pc-linux-gnu)
  CPU: Intel(R) Core(TM) i7-8650U CPU @ 1.90GHz
  WORD_SIZE: 64
  LIBM: libopenlibm
  LLVM: libLLVM-6.0.1 (ORCJIT, skylake)
Environment:
  JULIA_REVISE = auto

`pkg> st`
  [c43c736e] Genie v0.28.0
  [e6f89c97] LoggingExtras v0.4.0
  [295af30f] Revise v2.5.4

**Comment by amakiir** [comment]
Don't ask me why but I found that if you put the `<% @yield %>` in a div like so `<div> <% @yield %> </div>` it works.

**Comment by essenciary** [comment]
Thanks, I'll take a look, sorry for that :-/

**Comment by essenciary** [comment]
@kentei Thanks for reporting this - it should be now fixed in v0.29 (which should be registered any minute now).
