### ISSUE TITLE
up() does not bind to port if a server is already running on localhost:defaultport

### ISSUE THREAD

**Issue by madprogramer** [GenieFramework/Genie.jl#229]
**Describe the bug**
Self-Explanatory

**Expected behavior**
Genie should check to see if the port is available and either give an exception or try another port

**Comment by essenciary** [comment]
@madprogramer Thanks - I'm not sure what you mean by newapp() fails. What happens, what's the failure? I can't replicate, the new app is generated just fine.

**Comment by madprogramer** [comment]
Oh sorry, at first I thought the directory was also generated incorrectly, but it seems that it only fails to launch the server. Although, it would still be nice if you had a workaround to try another port.

**Comment by essenciary** [comment]
Thanks. I'm still going to need more info please. What do you have running on the port and what failure do you get? (Just want to make sure we're talking about the same thing). 

Basically, depending on the arguments passed, newapp does up to 2 things: 
1 - creates a new app (always)
2 - if autostart is true, it will also start the server. 

Starting the server is independent from app creation. So here it's a subjective matter: right now the app starts and listens onto the port (this is thanks to a newer feature in HTTP.jl). If the port is already in use, the requests will go to the other app. But once that is stopped, the Genie app will receive the traffic. So in a way, it's nice. No error, and once the port becomes available, it just works. 

The other option is to throw an error and break the flow. It would be the most clear but very inconvenient. Is it necessary? 

While the last option would be to randomly try different ports within a range. If it picks a random port, if the user does not pay attention to the output, she won't know which port to use.

I don't know which one is best and I can't see any reason for choosing differently. So in this regard, the current behavior is not really any worse than the others. 

Do you have any arguments for supporting a different strategy?

**Comment by madprogramer** [comment]
Maybe an error message to indicate that the port was unavailable?

I was running a Jupyter server in the background, I didn't understand what was going on until I had the idea of shutting it down, and then everything worked just fine. Had the error message _told me this_ it would've took me much shorter to notice.

**Comment by essenciary** [comment]
Yeah, that's a good idea. I don't know if there's any way of getting that info from HTTP.jl. Does Jupyter run on 8000 by default too?

**Comment by madprogramer** [comment]
I'm not entirely sure? I've had it launch on ports 8000, 8001, 8002, 8888 for me at different times. I don't know if it has to do with version or if any have priority over the others.

**Comment by essenciary** [comment]
I see, thanks!

**Comment by essenciary** [comment]
Not sure how to handle this - for now it uses the behavior of HTTP.jl which I see has changed from not throwing to throwing an error when the port is in use. So now the app will error upon startup. 

I think it's good enough - users can implement their own logic to catch the error and try different ports. If you want to contribute an option for this, I'm happy to merge it into Genie's core.
