### ISSUE TITLE
Genie.newapp("") on v1.0.5 errors during dependencies installation

### ISSUE THREAD

**Issue by kunov** [GenieFramework/Genie.jl#230]
**Describe the bug**

Genie.newapp("") on v1.0.5 errors during dependencies installation.

**Error stacktrace**
If any error is thrown, please copy from the REPL and paste it here

```
julia> using Genie

julia> Genie.newapp("MyGenieApp")
[ Info: Done! New app created at /home/kunov/all-julia-repos/all-genie/MyGenieApp
[ Info: Changing active directory to /home/kunov/all-julia-repos/all-genie/MyGenieApp
**[ Info: Installing app dependencies**
  Updating git-repo `https://github.com/GenieFramework/Genie.jl.git`
 Resolving package versions...
┌ Warning: julia version requirement for package Genie not satisfied
└ @ Pkg.Operations /buildworker/worker/package_linux64/build/usr/share/julia/stdlib/v1.0/Pkg/src/Operations.jl:153
ERROR: Unsatisfiable requirements detected for package Nettle [49dea1ee]:
 Nettle [49dea1ee] log:
 ├─possible versions are: [0.4.0, 0.5.0] or uninstalled
 ├─restricted to versions 0.5.0-0.5 by Genie [c43c736e], leaving only versions 0.5.0
 │ └─Genie [c43c736e] log:
 │   ├─possible versions are: 0.31.0 or uninstalled
 │   └─Genie [c43c736e] is fixed to version 0.31.0
 └─restricted by julia compatibility requirements to versions: 0.4.0 or uninstalled — no versions left

```

**To reproduce**
```
using Pkg; Pkg.activate(".")
Pkg.add("Genie")

Genie.newapp("myapp")
```

**Expected behavior**
I just want to `Genie.newapp("")` to work without throwing errors.

**Additional context**

```
julia> versioninfo()
Julia Version 1.0.5
Commit 3af96bcefc (2019-09-09 19:06 UTC)
Platform Info:
  OS: Linux (x86_64-pc-linux-gnu)
  CPU: Intel(R) Core(TM) i7-7700 CPU @ 3.60GHz
  WORD_SIZE: 64
  LIBM: libopenlibm
  LLVM: libLLVM-6.0.0 (ORCJIT, skylake)

```
***

```
(MyGenieApp) pkg> st
    Status `~/all-julia-repos/all-genie/MyGenieApp/Project.toml`

```

**Comment by kunov** [comment]
And fyi,

On the git readme.md, it says Genie is supported on 1.2+.

However, on [https://genieframework.com/](https://genieframework.com/), the package is functional on 1.0+.

Thanks!

**Comment by essenciary** [comment]
Yes, the minimum version of Julia is 1.2 although that might not be accurate anymore. From what I see, Nettle 0.5 requires Julia 1.3 so it looks like I need to bump Genie's requirements too. 

The info on the website is incorrect, I will update it. 

Is it possible to upgrade to Julia 1.4?

**Comment by kunov** [comment]
Great, thanks for the response!

I imagine there are teams working on production code that would pick the LTS 1.0.5 version, and later might want to develop a web component for the app. (I'm in this boat currently).

However, I will consider making a Genie demo on the side and see whether it leads to a conversion of our main julia version from the lts to 1.4+.

**Comment by essenciary** [comment]
You can have a Genie fork where you just remove Nettle, but that will leave you without encryption for secret, sessions, cookies, etc.
