### ISSUE TITLE
API  Documentation HTML broken

### ISSUE THREAD

**Issue by ephetic** [GenieFramework/Genie.jl#231]
**Describe the bug**
Left nav/outline not populating.
![image](https://user-images.githubusercontent.com/3395020/80325807-83694500-87eb-11ea-8fe6-5965fe97dd77.png)

**Error stacktrace**
N/A

**To reproduce**
Visit https://genieframework.github.io/Genie.jl/documentation/API/ and any children.

**Expected behavior**
Subheaders should render text other than `-`

**Additional context**
Chrome Version 81.0.4044.122 (Official Build) (64-bit)
Safari Version 13.1 (15609.1.20.111.8)

**Comment by essenciary** [comment]
Thanks @ephetic - know issue though I don't know why that happens. If you feel like please take a look at what Documenter does there.
