### ISSUE TITLE
Bad doc link in Acknowledgements

### ISSUE THREAD

**Issue by kczimm** [GenieFramework/Genie.jl#237]
> The awesome Genie logo was designed by Alvaro Casanova

Then provides a bad URL.

https://github.com/GenieFramework/Genie.jl/blame/master/docs/index.md#L86

**Comment by kczimm** [comment]
I found the twitter handle for the logo designer. I'm just assuming the acknowledgement is intended to direct interest towards the designer but that link won't help (anymore at least).

**Comment by essenciary** [comment]
Thanks, yeah :) He doesn't have a personal website atm.

**Comment by essenciary** [comment]
Fixed
