### ISSUE TITLE
errata: missing closing tag </li> on list item in intermediate tutorial's html view billgatesbooks.jl.html

### ISSUE THREAD

**Issue by angstyloop** [GenieFramework/Genie.jl#238]
errata:

A closing tag </li> is missing from the list item in the intermediate tutorial's html view billgatesbooks.jl.html

**Comment by essenciary** [comment]
@angstyloop Can you please provide more details, I can't see it?

**Comment by essenciary** [comment]
Closing due to lack of feedback
