### ISSUE TITLE
Documentation on cors header and changing public folder path

### ISSUE THREAD

**Issue by kimutaiRop** [GenieFramework/Genie.jl#241]
I am 2 days into genie and I already love it!! Thankyou so much, however I have just developed my frontend separately and backend separately coz I cant seem to find a clear documentation  on how to allow cors headers origin from all domain or atleast some,  coz i think request from different domains are by default blocked, i tested posting my data using the post request in julia given in examples and it worked but I cannot do it from my react app

**expected**
I think this will be a good thing, atleast a clearer documentation on how to change the public folder maybe to a build frontend bundle and how to add the cors header.

**Comment by essenciary** [comment]
@kimutaiRop These configurations are available in the `Configuration.jl` module. All you need to do is overwrite them in the application's per environment configuration, ie `config/env/dev.jl`. 

https://github.com/GenieFramework/Genie.jl/blob/master/src/Configuration.jl#L178
See `server_document_root` and `cors_headers`. 

I agree, more examples and docs are always better and a small demo for these would be great. If you have something we can use to extend the docs please make a PR. 

The asset pipeline needs a bit of work to make it compatible with the latest `Webpack` - but it is low priority as it doesn't seem to be used (nobody complained about being broken).

**Comment by kimutaiRop** [comment]
Okey... will be commiting some things I will be adding in the documentation after I succesfully made mine work. Thankyou.
