### ISSUE TITLE
Genie.Renderer required in Intermediate Topics tutorial

### ISSUE THREAD

**Issue by nickembrey** [GenieFramework/Genie.jl#244]
A friend and I are working through the tutorials on the website -- really enjoying the framework so far. My friend found what appears to be a typo in the "Working With Genie Apps: Intermediate Topics" tutorial: when showing code for BooksController.jl, Genie.Router is specified as the only dependency but the redirect function is actually in Genie.Renderer. I'll put in a PR to fix.

**Comment by essenciary** [comment]
Merged, closing, thanks
