### ISSUE TITLE
Generated Dockerfile has a different HOST value than the default application. 

### ISSUE THREAD

**Issue by harleyjackthomas** [GenieFramework/Genie.jl#246]
When following the Docker tutorial: https://genieframework.github.io/Genie.jl/documentation/16--Using_Genie_With_Docker.html

The Docker file produced uses a HOST value of 0.0.0.0, while the default application uses 127.0.0.1. 

Will create a PR to resolve the issue.

**Comment by essenciary** [comment]
Thanks for the PR, merged!

**Comment by essenciary** [comment]
PR merged, closing
