### ISSUE TITLE
Example of showing markdown.jl.md in Guide “Working_With_Genie_Apps” encounter error

### ISSUE THREAD

**Issue by deahhh** [GenieFramework/Genie.jl#248]
BooksController.jl :

function billgatesbooks()
  html( :books, "billgatesbooks.jl.md",books=all(Book))
end

billgatesbooks.jl.md :

# MD Bill Gates' $(length(books)) recommended books

error as follows when visit "http://localhost:8000/bgbooks"

┌ Error: 2020-06-13 15:42:54 LoadError("string", 1, UndefVarError(:books))
└ @ Genie.AppServer ~/.julia/packages/Genie/dPHYR/src/AppServer.jl:111
┌ Error: 2020-06-13 15:42:56 LoadError: UndefVarError: books not defined
│ top-level scope at string:1
│ include_string(::Module, ::String, ::String) at ./loading.jl:1080
│ include_string at ./loading.jl:1084 [inlined]
│ include_markdown(::String; context::Module) at /home/han/.julia/packages/Genie/dPHYR/src/renderers/Html.jl:211
│ get_template(::String; partial::Bool, context::Module) at /home/han/.julia/packages/Genie/dPHYR/src/renderers/Html.jl:236
│ render(::FilePathsBase.PosixPath; layout::FilePathsBase.PosixPath, context::Module, vars::Base.Iterators.Pairs{Symbol,Array{Books.Book,1},Tuple{Symbol},NamedTuple{(:books,),Tuple{Array{Books.Book,1}}}}) at /home/han/.julia/packages/Genie/dPHYR/src/renderers/Html.jl:314
│ render(::Type{MIME{Symbol("text/html")}}, ::FilePathsBase.PosixPath; layout::FilePathsBase.PosixPath, context::Module, vars::Base.Iterators.Pairs{Symbol,Array{Books.Book,1},Tuple{Symbol},NamedTuple{(:books,),Tuple{Array{Books.Book,1}}}}) at /home/han/.julia/packages/Genie/dPHYR/src/renderers/Html.jl:339
│ #html#17 at /home/han/.julia/packages/Genie/dPHYR/src/renderers/Html.jl:405 [inlined]
│ html(::Symbol, ::String; layout::Symbol, context::Module, status::Int64, headers::Dict{String,String}, vars::Base.Iterators.Pairs{Symbol,Array{Books.Book,1},Tuple{Symbol},NamedTuple{(:books,),Tuple{Array{Books.Book,1}}}}) at /home/han/.julia/packages/Genie/dPHYR/src/renderers/Html.jl:351
│ billgatesbooks() at /home/han/Genie_test_app/app/resources/books/BooksController.jl:7
│ #invokelatest#1 at ./essentials.jl:712 [inlined]
│ invokelatest at ./essentials.jl:711 [inlined]
│ match_routes(::HTTP.Messages.Request, ::HTTP.Messages.Response, ::Genie.Router.Params{Any}) at /home/han/.julia/packages/Genie/dPHYR/src/Router.jl:466
│ route_request(::HTTP.Messages.Request, ::HTTP.Messages.Response, ::Sockets.IPv4) at /home/han/.julia/packages/Genie/dPHYR/src/Router.jl:137
│ handle_request(::HTTP.Messages.Request, ::HTTP.Messages.Response, ::Sockets.IPv4) at /home/han/.julia/packages/Genie/dPHYR/src/AppServer.jl:109
│ handle_request at /home/han/.julia/packages/Genie/dPHYR/src/AppServer.jl:102 [inlined]
│ #19 at /build/julia-98cBbp/julia-1.4.1+dfsg/usr/share/julia/stdlib/v1.4/Distributed/src/macros.jl:127 [inlined]
│ run_work_thunk(::Genie.AppServer.var"#19#20"{HTTP.Messages.Request,HTTP.Messages.Response}, ::Bool) at /build/julia-98cBbp/julia-1.4.1+dfsg/usr/share/julia/stdlib/v1.4/Distributed/src/process_messages.jl:79

**Comment by essenciary** [comment]
Thanks - updated to different syntax: 
https://genieframework.github.io/Genie.jl/dev/guides/Working_With_Genie_Apps.html#Markdown-views
