### ISSUE TITLE
websocket instead of websockets in test and dev envs

### ISSUE THREAD

**Issue by kimutaiRop** [GenieFramework/Genie.jl#251]
when creating a new project with ` Genie.newapp` the dev and test environment has wrong naming for the websocket I thing that  the main config file expect it to be `websockets` but it is named websocket this will cause an error when starting server or deploying to a web server with `bin\server`

**Comment by essenciary** [comment]
@kimutaiRop Which version of Genie please? That should've been changed a few versions ago. I can't reproduce.

**Comment by essenciary** [comment]
Closing due to lack of feedback
