### ISSUE TITLE
Access to fetch blocked by CORS policy

### ISSUE THREAD

**Issue by wadehenning** [GenieFramework/Genie.jl#253]
**Describe the bug**
When calling the web server using `fetch` from my javascript app, I am getting a CORS error.  I don't know if this matters, but note that both of these are local servers used in development.

**Error stacktrace**
This is the error in my web console:
`
Access to fetch at 'http://127.0.0.1:8000/random' from origin 
'http://localhost:3000' has been blocked by CORS policy: 
The 'Access-Control-Allow-Origin' header contains the invalid value ''. 
Have the server send the header with a valid value, or, if an opaque 
response serves your needs, set the request's mode to 'no-cors' 
to fetch the resource with CORS disabled.`

**To reproduce**
**routes.jl**

```
using Genie, Genie.Router, Genie.Renderer.Json, Genie.Requests
using HTTP

Genie.config.run_as_server = true
Genie.config.cors_allowed_origins = ["*"]

route("/random", method="POST") do
  dim = parse(Int, get(@params, :dim, "2"))
  num = parse(Int, get(@params, :num, "3"))
  (:random => rand(dim,num)) |> json
end

Genie.startup()
```

**relevant App.js**
```
let params = {
  dim: '1',
  num: '3'
}

const url = 'http://127.0.0.1:8000/random'
fetch(url, {
            method: 'POST',
            mode: "cors", 
            body: params               
          })
.then(response => response.json())
.then(data => console.log(data))
.catch(()=>console.log('Wade- you cant access the url response'));
```

**Expected behavior**
Expect a json object to be returned containing random numbers.

**Additional context**

```
julia> versioninfo()
Julia Version 1.4.1
```
and
```
pkg> st
(@v1.4) pkg> st
Status `~/.julia/environments/v1.4/Project.toml`
  [c52e3926] Atom v0.12.11
  [159f3aea] Cairo v1.0.3
  [005e02dc] FisherRaoDistance v0.1.0 [`~/.julia/dev/FisherRaoDistance`]
  [c43c736e] Genie v0.31.1
  [cd3eb016] HTTP v0.8.15
  [e5e0dc1b] Juno v0.8.2
  [2472808a] KernelDensityEstimate v0.5.2
  [c43967c8] KernelDensityEstimatePlotting v0.1.6
  [6f286f6a] MultivariateStats v0.7.0
  [14b8a8f1] PkgTemplates v0.6.4
```

**Comment by essenciary** [comment]
@wadehenning Thanks, managed to trace it and fix it. It in master and in the v0.31.3 (pending registration).

**Comment by essenciary** [comment]
Closing - please reopen if necessary.

**Comment by essenciary** [comment]
@wadehenning If you're still having problems it looks like CSP https://developer.mozilla.org/en-US/docs/Web/HTTP/CSP

**Comment by wadehenning** [comment]
@essenciary I had to put this project on the backburner last year and have not had a chance to test your fix until now.  My  React<=>Julia development stack template above works perfectly.    I can't believe I can call my local Julia server so easily from my create-react-app local development environment.  Thank you very much!  This is a really nice.
