### ISSUE TITLE
Link to documentation at www.genieframework.com is broken

### ISSUE THREAD

**Issue by uhtewihptihwue** [GenieFramework/Genie.jl#256]
At the bottom of https://www.genieframework.com/, there is a link with the text "Read the docs" directing to https://genieframework.github.io/Genie.jl/guides/Working_With_Genie_Apps.html. But that link is broken and returns the following message:

```
404

File not found

The site configured at this address does not contain the requested file.

If this is your site, make sure that the filename case matches the URL.
For root URLs (like http://example.com/) you must provide an index.html file.

Read the full documentation for more information about using GitHub Pages. 
```

**Comment by essenciary** [comment]
Thanks for reporting this - docs have moved to https://genieframework.github.io/Genie.jl/dev/ link needs updating.

**Comment by essenciary** [comment]
Links updated
