### ISSUE TITLE
Registering on MetaData

### ISSUE THREAD

**Issue by jpfairbanks** [GenieFramework/Genie.jl#26]
Hi @essenciary, I really enjoyed your JuliaCon talk and I am so excited to start writing Genie Apps!

Is there something that prevents this package from being registered on MetaData? The current docs indicate that `Pkg.clone` is the method for getting this package.

**Comment by essenciary** [comment]
Thanks @jpfairbanks I'm glad you liked it! 

Just the lack of a user-friendly installer, as SearchLight requires an unofficial package, PostgreSQL.jl. 

I'm not sure what to do about PostgreSQL.jl, it's not getting any love in the Julia community, so it's possible that support for PostgreSQL will disappear altogether in v0.6 if nobody upgrades the package. 

That being said, after over a year of focusing on features, the next few months will be all about consolidation. Running on Julia v0.6, sorting out the MetaData, performance improvements, support for more backends for SearchLight, Session and Cache, documentation, guides, etc. 

Thus, MetaData registration will come soon - I'm just not sure if before of after adding support for MySQL and maybe making it the official package.

**Comment by jpfairbanks** [comment]
Can you use ODBC.jl instead of Postgres? According to @quinnj, [ODBC](https://github.com/JuliaDB/ODBC.jl/) is stable and ready for production ;)

I see that Searchlight require MySQL.jl. Do you intend that Genie require all possible database packages in order to install genie? That seems fragile.

Registration should come sooner rather than later, because then people can start using and contributing to it.

**Comment by essenciary** [comment]
@jpfairbanks Thanks. I've worked a lot lately on refactoring and removing coupling between Genie and SearchLight and tweaked the requirements. 

SearchLight now has support for PostgreSQL, MySQL and SQLite and I'm also planning on adding support for ODBC. 

Genie doesn't require SearchLight anymore, so we can have web apps without the ORM. Also, SearchLight doesn't depend on Genie anymore, so we can have apps with SearchLight (ORM) support without the full MVC stack. 

In SearchLight none of the DB adapters is a requirement anymore.

**Comment by dehann** [comment]
+1 for registering Genie.jl on METADATA. Thanks for the awesome package!

**Comment by essenciary** [comment]
@dehann sorry, I did not register it just yet. I did register my first package it's true, but it's more of a test package for a Julia book that I'm working on. 

But Genie will be next, now that I've learned the ropes :)
