### ISSUE TITLE
Missing mimetype for .mjs files

### ISSUE THREAD

**Issue by AlexDaniel** [GenieFramework/Genie.jl#270]
Genie is serving `.mjs` files with a generic mimetype but it should use `text/javascript`.

The idea behind `.mjs` and the issue with many servers is well described in [MDN web docs](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Guide/Modules#Aside_%E2%80%94_.mjs_versus_.js).

TL;DR people are advised to use `.mjs` for javascript modules, but:

> you need to make sure that your server is serving them with a Content-Type header that contains a JavaScript MIME type such as text/javascript. If you don't, you'll get a strict MIME type checking error along the lines of "The server responded with a non-JavaScript MIME type" and the browser won't run your JavaScript. Most servers already set the correct type for .js files, but not yet for .mjs files.

My guess is that adding a mapping for `.mjs` files here will be enough: 

https://github.com/GenieFramework/Genie.jl/blob/97c4433772d3cec75c80d36f1a89b29f8ed1a7b2/src/mimetypes.jl#L390-L392

**Comment by essenciary** [comment]
@AlexDaniel Thanks, added. Currently on master, it will be out in v1.2
