### ISSUE TITLE
WebSocket handling is doing too much

### ISSUE THREAD

**Issue by AlexDaniel** [GenieFramework/Genie.jl#271]
From https://github.com/GenieFramework/Genie.jl/issues/192:

> I'd appreciate feedback regarding the API. Also, I'm working on a more elaborate example so I'll publish an advanced websockets documentation soon.

The API as it is right now is not very useful. It makes a lot of assumptions and forces devs to work with websockets in a particular way, when in practice custom logic is often needed.

`channels_support` pushes this file to the clients:
https://github.com/GenieFramework/Genie.jl/blob/6860ca7ed8955f7f89abae92a759f4b2f5ea21cf/files/embedded/channels.js

Which also has some lines prepended during runtime:
```
window.Genie = {};
Genie.Settings = {"webchannels_autosubscribe":true,"server_host":"127.0.0.1","webchannels_subscribe_channel":"subscribe","server_port":8000,"webchannels_default_route":"__","webchannels_unsubscribe_channel":"unsubscribe","websockets_port":8001}
```

I think the idea is that Genie attempts to implement something on top of websockets. What exactly, what was the inspiration? Anyway, this also means that I can't actually use websockets themselves. For example, how do I send and receive [binary data](https://blog.mgechev.com/2015/02/06/parsing-binary-protocol-data-javascript-typedarrays-blobs/)? Keep in mind that people use websockets when doing regular http requests is not enough, for example for realtime-ish high performance stuff like games.

I really do not know what to say, maybe I am misunderstanding something completely. But from what I can see, if the idea is to have some sort of channels or message queues on top of websockets, then it should be advertised and named accordingly. The fact that you're using websockets for it is just an implementation detail.

The API for actual websockets should be similar to the one we have in JS (connection open, connection closed, payload received, errors, etc).

**Comment by essenciary** [comment]
@AlexDaniel I'm not sure I understand your point. The `WebChannels` API and `channels_support` is opt-in. They provide a standard mechanism for communication over WebSockets but you don't have to use it. What exactly is the issue?

**Comment by AlexDaniel** [comment]
@essenciary Oh, I see it now. Basically, if one wants to use websockets, then they can use HTTP.WebSockets directly ([like this](https://github.com/JuliaWeb/HTTP.jl#websocket-examples)). I guess it's just my misunderstanding then, but the documentation could have cleared it up. I'll close the ticket, but feel free to reopen if you agree that the docs need a tweak. My suggested changes for [this document](https://genieframework.github.io/Genie.jl/dev/tutorials/17--Working_with_Web_Sockets.html) would be (feel free to reword):

> Genie provides a powerful workflow for client-server communication over websockets. The system hides away the complexity **of using websockets themselves** ~the network level communication, exposing~ **by providing a** powerful abstraction **(`WebChannels`)** which resembles Genie's familiar MVC workflow: the clients and the server exchange messages over channels (which are the equivalent of routes). **While this document focuses on using WebChannels, it is also possible to use [HTTP.WebSockets](https://github.com/JuliaWeb/HTTP.jl#websocket-examples) directly without using the provided abstraction.**
