### ISSUE TITLE
Loading the package is crashing Julia process

### ISSUE THREAD

**Issue by shashankp** [GenieFramework/Genie.jl#272]
**Describe the bug**
Loading Genie package is crashing the Julia process

**Error stacktrace**

![image](https://user-images.githubusercontent.com/498813/92528564-9df60500-f246-11ea-8860-e413c0ede2f2.png)

**To reproduce**
Installed Genie using Pkg (🙂 )
Tried to use Genie (😕 )

Same is the case with running this script 
```
using Genie, Genie.Router

route("/hello") do
    "Hello World"
end
```

**Expected behavior**
Expected to load Genie package

**Additional context**
Please include the output of 
`julia> versioninfo()`
and
`pkg> st`

```
julia> versioninfo()
Julia Version 1.5.1
Commit 697e782ab8 (2020-08-25 20:08 UTC)
Platform Info:
  OS: macOS (x86_64-apple-darwin19.5.0)
  CPU: Intel(R) Core(TM) i5-2500S CPU @ 2.70GHz
  WORD_SIZE: 64
  LIBM: libopenlibm
  LLVM: libLLVM-9.0.1 (ORCJIT, sandybridge)

(@v1.5) pkg> st
Status `~/.julia/environments/v1.5/Project.toml`
  [a93c6f00] DataFrames v0.21.7
  [31a5f54b] Debugger v0.6.5
  [587475ba] Flux v0.11.1
  [c43c736e] Genie v0.19.0
  [7073ff75] IJulia v1.21.3
  [82e4d734] ImageIO v0.3.0
  [6218d12a] ImageMagick v1.1.6
  [916415d5] Images v0.22.4
  [f28f55f0] Memento v1.1.1
  [c3e4b0f8] Pluto v0.11.12
  [7f904dfe] PlutoUI v0.6.1
  [295af30f] Revise v1.0.3
```

**Comment by essenciary** [comment]
@shashankp Ugh nasty. 
Can you please share your Manifest.toml and Project.toml files so I can reproduce the environment? 
Is that the macOS beta?

**Comment by shashankp** [comment]
[Manifest.toml.txt](https://github.com/GenieFramework/Genie.jl/files/5193597/Manifest.toml.txt)
[Project.toml.txt](https://github.com/GenieFramework/Genie.jl/files/5193598/Project.toml.txt)

I've tried importing in a new activated environment, where it works

**Comment by essenciary** [comment]
@shashankp Thanks - so it might be some combination of packages. I'll try your setup. Thanks for the info!

**Comment by essenciary** [comment]
Ah, also, what's the error (the output of the crash)?

**Comment by shashankp** [comment]
> Ah, also, what's the error (the output of the crash)?

Silently fails. Is there a way to get debug output while importing a module?

**Comment by essenciary** [comment]
Do you still get this? I can't reproduce and nobody reported it.

**Comment by shashankp** [comment]
> Do you still get this? I can't reproduce and nobody reported it.

Didn't face this again; worked fine in a newly activated env.
