### ISSUE TITLE
Question about large files

### ISSUE THREAD

**Issue by Immortalin** [GenieFramework/Genie.jl#273]
If I upload a large file using the example code given in the documentation, will it block?

**Comment by essenciary** [comment]
@Immortalin block what? The frontend or the backend? The backend should have no problem as the request is handled in a thread. If you use a proxy (Nginx/Apache) make sure it doesn't timeout. 

For the frontend if you make a sync request (form submit) it will block the UI as that's how the browser works: it makes a new request which uploads the file and waits for the response. You can use async (Ajax) uploads so then the frontend doesn't block (eg https://usefulangle.com/post/67/pure-javascript-ajax-file-upload-showing-progess-percent). But of course this raises other issues: what will the user do until the file is uploaded (what's the value of not blocking), what if the user navigates away mid-upload, etc.
