### ISSUE TITLE
Websocket connection not working on AWS EC2 instances

### ISSUE THREAD

**Issue by hhaensel** [GenieFramework/Genie.jl#274]
Currently Stipple does not run on AWS EC2 instances.
The reason is that AWS uses an IP translation to connect to the instances. The problem starts when `load_channels()` composes the address or the ws connection, as it takes the (private) IP from the server configuration.
The solution for me was to replace the server address in the js function by the current url:
```
  var socket = new WebSocket('ws://' + window.Genie.Settings.server_host + ':' + window.Genie.Settings.websockets_port);
```
changed to
```
  var socket = new WebSocket('ws://' + window.location.hostname + ':' + window.Genie.Settings.websockets_port);
```

However, there are more problems to running it from a corporate site where only browser standard ports are opened.

I had to run `julia` as admin to be allowed to use the standard http port (80) and I had to set the websocket port to 443 (https) in order to get Stipple running on my EC2 instance.

My feature request would be to use only one channel for the website and to redirect the ws communication to the ws port internally. I know that this [can be done by Apache](https://stackoverflow.com/questions/5969607/is-it-possible-to-use-port-80-for-both-http-and-web-socket-traffic) but I am not sure, whether Julia can easily do it.
@essenciary : I know, you are quite an expert in server things so you might be able to answer this question. If you give me a hint how to solve it, I might try to do it myself.

**Comment by essenciary** [comment]
@hhaensel Thank you, the JS tweak makes sense, I've merged it. 

Yes, I totally agree - forcing 2 ports for http/https and ws/wss is messy. It used to work on the same port when Genie ran off HttpServer.jl - but when moving to HTTP.jl this got lost. We need to see if it's possible on HTTP.jl - if yes, it should be a simple change. I'll add an issue. 

PS - you're taking a potentially big risk running Julia on port 80. Why not put it behind Nginx/Apache (added bonus, set them to also serve static assets and provide caching).

**Comment by hhaensel** [comment]
I am certainly not a server expert, so would you mind explaining the risk?
Is it from running julia as admin or are there other risks connected with using port 80?

> Why not put it behind Nginx/Apache
Do you mean port redirection via rewrite / proxy? Why is it less risky?

**Comment by essenciary** [comment]
Indeed, it's generally not advisable to run processes which are exposed on the internet under elevated privileges. If an attacker manages to hack the Julia process it would get a lot of power. Apache for instance doesn't run with elevated privileges even if it's on port 80. 

In terms of static assets and caching, Nginx (and to some extent Apache) have much better performance at serving files, compared to HTTP.jl/Julia (at least that's the theory coming from other languages, I haven't tested personally, but a lot of optimizations went into these).

**Comment by essenciary** [comment]
PS I asked on the Julia #web slack if anybody knows how to reuse the http port for ws with HTTP.jl.

**Comment by hhaensel** [comment]
Thanks for your answers.
Meanwhile I tried to get Stipple run behind an apache server with
```
        <VirtualHost *:80>
          ProxyPass / http://localhost:8000/
          ProxyPassReverse / http://localhost:8000/
          <Location "/websocket">
            ProxyPass "ws://localhost:8001"
            ProxyPassReverse "ws://localhost:8001"
          </Location>
        </VirtualHost>
```
That works without problems when I load it the first time. But if I reload the page genie gets stuck during loading of `stipple.js`
```
Error: SystemError: opening file "/tmp/jl_genie_build_JnkziO/GenieViews/083ba44f843f55ec12b4db591e92ecb6f71d765f.jl": Permission denied
```

Do you have any idea where that may come from?

**Comment by hhaensel** [comment]
I just found out that the error doesn't depend on port forwarding, it also happens when I change everything back to normal and use direct port addressing. But it only occurs, when the websocket has been used. I will recheck on a different machine...

**Comment by essenciary** [comment]
It's what the error says - permission denied to access the file. Genie creates a tmp file where it puts the compiled views. Can you check if the files are there?

**Comment by essenciary** [comment]
What you can do quickly, is change the folder for generating the views to a folder where the user has access - for example in the app's folder, make a folder `tmp/`, then: 
`Genie.config.path_build = "/path/to/app/folder/tmp"`

**Comment by hhaensel** [comment]
I found the error. It came from running julia with admin rights. That changed the settings of the folder `jl_genie_build_JnkziO` to `root` and the standard user could not write to that directory. Deleting that directory and having it rebuild by reloading of the web page, everything runs smoothly.

My stiplle configuration is now back at standard ports (8000 and 8001) but with the port specification removed in `channels.js` so that ws is connected at the same port as the website. With apache settings (`proxy.conf`)
```
 <VirtualHost *:80>
          RewriteEngine On
          RewriteCond %{HTTP:Upgrade} =websocket [NC]
          RewriteRule /(.*)           ws://localhost:8001/$1 [P,L]
          RewriteCond %{HTTP:Upgrade} !=websocket [NC]
          RewriteRule /(.*)           http://localhost:8000/$1 [P,L]

          ProxyPassReverse / http://localhost:8000/
        </VirtualHost>
```
the websocket and http are split to the standard ports and everything runs smoothly via normal http:// at port 80.

**Comment by essenciary** [comment]
@hhaensel Thanks for the update! Great setup, thanks for sharing!

> It came from running julia with admin rights
I suspected the same but I couldn't quite imagine the workflow. So Julia runs with escalated privileges - but who is the "standard user"? Shouldn't be the same Julia process accessing the tmp folder?

I've made some progress with running WebSockets over HTTP/S thanks to @EricForgy - I need to try his approach, it can simplify the setup (especially on dev).

**Comment by hhaensel** [comment]
>So Julia runs with escalated privileges

No more!
> - but who is the "standard user"?
is typically "ubuntu" on ec2 ubuntu machines

> Shouldn't be the same Julia process accessing the tmp folder?
it does and it does generate a subfolder 

```
drwxrwxr-x  3 ubuntu ubuntu 4096 Sep 14 06:00 jl_genie_build_JnkziO
```
but after once running julia as admin (`sudo julia`), the rights of this folder changed so that ubuntu didn't have access anymore. So running julia (and Stipple) as `ubuntu` failed with the error above.

**Comment by hhaensel** [comment]
> I've made some progress with running WebSockets over HTTP/S thanks to @EricForgy - I need to try his approach, it can simplify the setup (especially on dev).

😄 👍

**Comment by essenciary** [comment]
@hhaensel I think this can be closed?

**Comment by hhaensel** [comment]
I will close this one, then 😺 🤴
