### ISSUE TITLE
Allow HTTP and WS servers to listen on the same port

### ISSUE THREAD

**Issue by essenciary** [GenieFramework/Genie.jl#276]
Allow web sockets to listen to the same port as the web server.

**Comment by essenciary** [comment]
https://github.com/EricForgy/Pages.jl/blob/main/src/Server.jl#L28-L54

**Comment by essenciary** [comment]
@hhaensel do you want to do the honors and close this one? 👑

**Comment by hhaensel** [comment]
It would be a pleasure to do so! Alone, I don't have the appropriate rights 🤴 
So please accept doing the honors for me 😉.

It's been a pleasure contributing 🙇

**Comment by essenciary** [comment]
Thank you for the awesome contribution! 🎉🙌 Closed! 💥
