### ISSUE TITLE
[Docs]Missing content for developing MVC apps tutorial page

### ISSUE THREAD

**Issue by mkschulze** [GenieFramework/Genie.jl#285]
**Describe the bug**
Missing content for developing MVC apps tutorial page

**To reproduce**
See: https://genieframework.github.io/Genie.jl/dev/tutorials/4-1--Developing_MVC_Web_Apps.html

**Expected behavior**
There is information to be expected.

**Comment by essenciary** [comment]
To be honest I don't remember what I wanted to put here - but these guides cover the MVC aspects: 

https://genieframework.github.io/Genie.jl/dev/guides/Working_With_Genie_Apps.html
https://genieframework.github.io/Genie.jl/dev/guides/Working_With_Genie_Apps_Intermediary_Topics.html (incomplete)

Genie will get some docs updates soon.

**Comment by yakir12** [comment]
This is still an issue, as in, there is no content in that link, so remove it or add said content.
