### ISSUE TITLE
newapp with autostart=false starts always server

### ISSUE THREAD

**Issue by casabre** [GenieFramework/Genie.jl#289]
I want to create a new app with the generator but without starting it immediately. However, setting `autostart=false` does not have an effect. Seems that the variable is not forwarded to `post_create`.

https://github.com/GenieFramework/Genie.jl/blob/e61a17ab12f74045f0d667ae620976dfb4f0bd57/src/Generator.jl#L467

**Comment by essenciary** [comment]
@casabre Thanks for picking this up and thanks for the contribution! The PR has been merged!
