### ISSUE TITLE
Server does not handle HEAD requests

### ISSUE THREAD

**Issue by derikk** [GenieFramework/Genie.jl#296]
**Describe the bug**
The Genie server does not respond to [HTTP HEAD](https://developer.mozilla.org/en-US/docs/Web/HTTP/Methods/HEAD) requests. Instead, it produces a 404, even for resources that exist and can be accessed with GET requests.

**To reproduce**
I used the following code from the Genie docs to start a minimal web server:
```
using Genie
import Genie.Router: route
import Genie.Renderer.Json: json

route("/") do
    (:message => "Hi there!") |> json
end
Genie.startup()
```

Then, using curl to make a GET request (`-i` displays the headers as well as the content):
```
$ curl -i http://localhost:8002/
HTTP/1.1 200 OK
Access-Control-Allow-Headers: 
Access-Control-Allow-Methods: 
Server: Genie/1.7.3/Julia/1.5.0
Access-Control-Allow-Credentials: 
Content-Type: application/json; charset=utf-8
Access-Control-Allow-Origin: 
Access-Control-Expose-Headers: 
Access-Control-Max-Age: 86400
Transfer-Encoding: chunked

{"message":"Hi there!"}
```
This works as intended. However, making an HTTP HEAD request results in a 404:
```
$ curl -I http://localhost:8000/
HTTP/1.1 404 Not Found
Content-Type: */*
Server: Genie/1.7.3/Julia/1.5.0
```

**Expected behavior**
According to the [Mozilla MDN docs](https://developer.mozilla.org/en-US/docs/Web/HTTP/Methods/HEAD),

> The HTTP HEAD method requests the headers that would be returned if the HEAD request's URL was instead requested with the HTTP GET method.

Therefore, I expect the server to respond to a HEAD request with the headers 
```
HTTP/1.1 200 OK
Access-Control-Allow-Headers: 
Access-Control-Allow-Methods: 
Server: Genie/1.7.3/Julia/1.5.0
Access-Control-Allow-Credentials: 
Content-Type: application/json; charset=utf-8
Access-Control-Allow-Origin: 
Access-Control-Expose-Headers: 
Access-Control-Max-Age: 86400
Transfer-Encoding: chunked
```

**Comment by essenciary** [comment]
@derikk Thanks for flagging this! Should be relatively easy to add, assuming that the web server allows responses without a body, I need to check.

**Comment by essenciary** [comment]
Added support for HEAD requests

**Comment by derikk** [comment]
Unfortunately, I don't think this was fixed in v1.9. The example still gives a 404 when I make a HEAD request.
I can get it to work by adding these lines from the test case:
https://github.com/GenieFramework/Genie.jl/blob/16349a22b26e2590906700f3891e813473aba938/test/tests_HEAD_requests.jl#L10-L12
However, the server should handle this by default like most servers do to comply with the spec and user expectations. The responses to HEAD requests are almost never defined manually, because they have a predefined meaning based on the results of GET requests.

**Comment by essenciary** [comment]
@derikk OK, I see what you mean. I'm not sure how that aligns with Genie's approach where GET is the default routing request method and all the other methods need to be explicitly defined. I will research to see how other frameworks (not servers) handle this (eg Django, Rails, etc).

**Comment by derikk** [comment]
In Rails, [a number of helper functions are defined](https://edgeapi.rubyonrails.org/classes/ActionDispatch/Routing/Mapper/HttpHelpers.html) for handling methods like GET, DELETE, PUT, and OPTIONS, but HEAD is not among these. When I made a HEAD request to a new app, it matched the line `get '/', to: 'users#get'` in my routes.rb. I believe it gets rewritten into a GET request by the Rack middleware (see [`request_method()` docs](https://api.rubyonrails.org/classes/ActionDispatch/Request.html#method-i-request_method), but I'm not sure where in the code that happens.

**Comment by essenciary** [comment]
Thanks yes, I did some research into Rails just after my previous reply. Indeed, HEAD requests are handled by GET routes. However, i found quite a few issues with this (reported by users). But overall yes, it makes sense to ensure that the same logic is used for HEAD and GET by default. I'm tempted to extend the logic to automatically handle HEAD requests with GET routes, while also allowing to optionally define custom HEAD routes (I've seen this in a few Rails issues where people wanted to handle HEAD more efficiently, or with different caching strategies, etc).

**Comment by derikk** [comment]
That sounds like the best approach.

**Comment by essenciary** [comment]
New tests passing per the above, closing. Please reopen if anything is still off.

**Comment by derikk** [comment]
Hmm, this still doesn't work for me, as of Genie 1.10. I ran `Pkg.test()`, which passed. But when I tried running the "HEAD requests should be by default handled by GET" test manually, it failed like before. It appears that it only succeeds in [tests_HEAD_requests.jl](https://github.com/GenieFramework/Genie.jl/blob/4dec16ed7d/test/tests_HEAD_requests.jl) because the previous test case defines a HEAD route whose definition leaks into this test.

**Comment by essenciary** [comment]
Oops sorry about that - I couldn't remember if it was fixed but as the test passed, I assumed it was. I guess it wasn't. Thanks for the update!

**Comment by essenciary** [comment]
Looking good on upcoming v2: 

![image](https://user-images.githubusercontent.com/11292378/123509256-a0f6a080-d674-11eb-9e29-f6029209aaf8.png)

**Comment by derikk** [comment]
Thank you, and congratulations on the upcoming release!

**Comment by essenciary** [comment]
Thank you! ❤
