### ISSUE TITLE
Genie.Requests: MultiDict for one key having multiple values

### ISSUE THREAD

**Issue by mkschulze** [GenieFramework/Genie.jl#299]
**Is your feature request related to a problem? Please describe.**
I would like to be able to use the MultiDict functionality from werkzeug.datastructures "MultiDict" class to build a custom request_dict.jl

This for example is supposed to be useful for some HTML Form elements that pass multiple values for the same key. 

**Describe the solution you'd like**
Rewriting the Class MultiDict as a Julia/Genie implementation from: https://github.com/pallets/werkzeug/blob/master/src/werkzeug/datastructures.py

**Describe alternatives you've considered**
Maybe this can be done with Value Collection like:
+ get!(dict, key, empty_collection)

**Additional context**
I'm in the process of writing a GenieCMS plugin and this would be requiered in a shared ViewModelBase.jl module.

Here is an example of the ViewModelBase and the request_dict in Python Flask.
Do we have something similar in Genie requests or something you know of? Or would that need to be rewritten?

https://gist.github.com/mkschulze/9c623d4e885ace6f71452dcbff8b8ab0

**Comment by essenciary** [comment]
@mkschulze We need to check. For example in PHP these would be sent as `...?foo[]=1&foo[]=2&foo[]=3`. I wonder how these come up in the payload - and we can process them so that in @params we have `:foo => ["1", "2", "3"]`.

**Comment by essenciary** [comment]
I went a different route and: 
1. passing `?x=1&x=10` will return 10 so it keeps working like it currently does (non breaking)
2. passing `?x[]=1&x[]=10` will set up `@params(Symbol("x[]"))` as `["1", "10"]` (an actual array of String).
3. we can also combine `?x=1&x[]=1&x[]=10` and both vars will be correctly set.

**Comment by mkschulze** [comment]
ok, will see if I can get that working. Thx for looking into!

**Comment by essenciary** [comment]
You're welcome, thanks for bringing this up. Let me know how it works when you have a chance, not a big fan of the `Symbol("x[]")` approach... Maybe we can come up with something nicer/shorter.

**Comment by mkschulze** [comment]
Btw, using a symbol would mean to use meta-programming to generate a variable that stores multiple values, instead of using collections right?
I didn't find yet, but maybe the [datastructures.jl](https://github.com/JuliaCollections/DataStructures.jl) provides a good way already?

How about the collection approach mentioned above? 
`get!(dict, key, empty_collection)`

Wouldn't that be cleaner compared to a symbol?

**Comment by essenciary** [comment]
> Just to clarify, using a symbol would mean to use meta-programming to generate a variable that stores multiple values, instead of using collections right?

I'm not sure what you have in mind. `Router.@params` is a collection (it's a `Dict{Symbol,Any}`). So the keys are symbols and we can do `@params(:foo)` to access a query value like `someurl?foo=2&bar=3`. When you have a query variable like `foo[]`, you need to look it up as `@params(:foo[])`, but that is invalid Julia syntax (can't use that for a Symbol literal). So instead of the Symbol literal we use the Symbol constructor. `Symbol(:foo[])` is just the key for accessing the params collection and it's used as a cheaper string.

**Comment by essenciary** [comment]
> How about the collection approach mentioned above?

You can use `get!(@params, Symbol("foo[]"), some_value)` but the `Genie.Requests` module has friendlier methods for accessing request payloads over GET, POST, etc.
