### ISSUE TITLE
Support for SVG elements

### ISSUE THREAD

**Issue by MaximeRivest** [GenieFramework/Genie.jl#301]
The page rendering seems broken when the html template includes an svg tag such as :  

```html
<svg width="10" height="10">
        <rect width="10" height="10" style="fill:#d76e2d;stroke-width:1;stroke:rgb(0,0,0)"/>
</svg>
```
**Error stacktrace**
######################### ERROR STACKTRACE #########################
UndefVarError: svg not defined
(::Genie.Renderer.Html.var"#976#1021")() at /tmp/jl_genie_build_GT62DE/GenieViews/cecdb8e16113547528a671bc94d3e51943eb0795.jl:101
normal_element(::Genie.Renderer.Html.var"#976#1021", ::String, ::Array{Any,1}, ::Array{Pair{Symbol,Any},1}) at /home/maxime/.julia/packages/Genie/3rr2f/src/renderers/Html.jl:57
div(::Function; attrs::Base.Iterators.Pairs{Symbol,String,Tuple{Symbol},NamedTuple{(:class,),Tuple{String}}}) at ./none:2
(::Genie.Renderer.Html.var"#975#1020")() at /tmp/jl_genie_build_GT62DE/GenieViews/cecdb8e16113547528a671bc94d3e51943eb0795.jl:99
normal_element at /home/maxime/.julia/packages/Genie/3rr2f/src/renderers/Html.jl:57 [inlined]
#div#127 at ./none:2 [inlined]
(::Genie.Renderer.Html.var"#948#993")() at /tmp/jl_genie_build_GT62DE/GenieViews/cecdb8e16113547528a671bc94d3e51943eb0795.jl:7
skip_element at /home/maxime/.julia/packages/Genie/3rr2f/src/renderers/Html.jl:196 [inlined]
(::Genie.Renderer.Html.var"#947#992")() at /tmp/jl_genie_build_GT62DE/GenieViews/cecdb8e16113547528a671bc94d3e51943eb0795.jl:5
skip_element at /home/maxime/.julia/packages/Genie/3rr2f/src/renderers/Html.jl:196 [inlined]
func_cecdb8e16113547528a671bc94d3e51943eb0795 at /tmp/jl_genie_build_GT62DE/GenieViews/cecdb8e16113547528a671bc94d3e51943eb0795.jl:5 [inlined]
#1 at ./none:0 [inlined]
iterate at ./generator.jl:47 [inlined]
collect(::Base.Generator{Array{typeof(Genie.Renderer.Html.func_cecdb8e16113547528a671bc94d3e51943eb0795),1},Genie.Renderer.Html.var"#1#2"}) at ./array.jl:686
normal_element(::Array{typeof(Genie.Renderer.Html.func_cecdb8e16113547528a671bc94d3e51943eb0795),1}, ::String, ::Array{Any,1}) at /home/maxime/.julia/packages/Genie/3rr2f/src/renderers/Html.jl:98
normal_element(::Genie.Renderer.Html.var"#646#650", ::String, ::Array{Any,1}, ::Array{Pair{Symbol,Any},1}) at /home/maxime/.julia/packages/Genie/3rr2f/src/renderers/Html.jl:57
#body#55 at ./none:2 [inlined]
body at ./none:2 [inlined]
(::Genie.Renderer.Html.var"#643#647")() at /tmp/jl_genie_build_GT62DE/GenieViews/97d19d79f055cd9b8593d4a572a1c981eebb3475.jl:7
normal_element at /home/maxime/.julia/packages/Genie/3rr2f/src/renderers/Html.jl:57 [inlined]
#html#47 at ./none:2 [inlined]
func_97d19d79f055cd9b8593d4a572a1c981eebb3475() at /tmp/jl_genie_build_GT62DE/GenieViews/97d19d79f055cd9b8593d4a572a1c981eebb3475.jl:6
#invokelatest#1 at ./essentials.jl:710 [inlined]
invokelatest at ./essentials.jl:709 [inlined]
Genie.Renderer.WebRenderable(::typeof(Genie.Renderer.Html.func_97d19d79f055cd9b8593d4a572a1c981eebb3475)) at /home/maxime/.julia/packages/Genie/3rr2f/src/Renderer.jl:159
|>(::Function, ::Type{T} where T) at ./operators.jl:834
render(::Type{MIME{Symbol("text/html")}}, ::FilePathsBase.PosixPath; layout::FilePathsBase.PosixPath, context::Module, vars::Base.Iterators.Pairs{Union{},Union{},Tuple{},NamedTuple{,Tuple{}}}) at /home/maxime/.julia/packages/Genie/3rr2f/src/renderers/Html.jl:381
#html#19 at /home/maxime/.julia/packages/Genie/3rr2f/src/renderers/Html.jl:463 [inlined]
html(::Symbol, ::Symbol; layout::Symbol, context::Module, status::Int64, headers::Dict{String,String}, vars::Base.Iterators.Pairs{Union{},Union{},Tuple{},NamedTuple{,Tuple{}}}) at /home/maxime/.julia/packages/Genie/3rr2f/src/renderers/Html.jl:391
main() at /home/maxime/sm_tools_web/SmToolsApp/app/resources/maps/MapsController.jl:7
#invokelatest#1 at ./essentials.jl:710 [inlined]
invokelatest at ./essentials.jl:709 [inlined]
match_routes(::HTTP.Messages.Request, ::HTTP.Messages.Response, ::Genie.Router.Params{Any}) at /home/maxime/.julia/packages/Genie/3rr2f/src/Router.jl:498
route_request(::HTTP.Messages.Request, ::HTTP.Messages.Response, ::Sockets.IPv4) at /home/maxime/.julia/packages/Genie/3rr2f/src/Router.jl:150
handle_request(::HTTP.Messages.Request, ::HTTP.Messages.Response, ::Sockets.IPv4) at /home/maxime/.julia/packages/Genie/3rr2f/src/AppServer.jl:168
handle_request at /home/maxime/.julia/packages/Genie/3rr2f/src/AppServer.jl:161 [inlined]
#22 at /buildworker/worker/package_linux64/build/usr/share/julia/stdlib/v1.5/Distributed/src/macros.jl:127 [inlined]
run_work_thunk(::Genie.AppServer.var"#22#23"{HTTP.Messages.Request,HTTP.Messages.Response}, ::Bool) at /buildworker/worker/package_linux64/build/usr/share/julia/stdlib/v1.5/Distributed/src/process_messages.jl:79
remotecall_fetch(::Function, ::Distributed.LocalProcess; kwargs::Base.Iterators.Pairs{Union{},Union{},Tuple{},NamedTuple{,Tuple{}}}) at /buildworker/worker/package_linux64/build/usr/share/julia/stdlib/v1.5/Distributed/src/remotecall.jl:379
remotecall_fetch(::Function, ::Distributed.LocalProcess) at /buildworker/worker/package_linux64/build/usr/share/julia/stdlib/v1.5/Distributed/src/remotecall.jl:379
remotecall_fetch(::Function, ::Int64; kwargs::Base.Iterators.Pairs{Union{},Union{},Tuple{},NamedTuple{,Tuple{}}}) at /buildworker/worker/package_linux64/build/usr/share/julia/stdlib/v1.5/Distributed/src/remotecall.jl:421
remotecall_fetch(::Function, ::Int64) at /buildworker/worker/package_linux64/build/usr/share/julia/stdlib/v1.5/Distributed/src/remotecall.jl:421
setup_http_handler(::HTTP.Messages.Request, ::HTTP.Messages.Response) at /home/maxime/.julia/packages/Genie/3rr2f/src/AppServer.jl:183
setup_http_handler at /home/maxime/.julia/packages/Genie/3rr2f/src/AppServer.jl:182 [inlined]
handle at /home/maxime/.julia/packages/HTTP/IAI92/src/Handlers.jl:253 [inlined]
handle(::HTTP.Handlers.RequestHandlerFunction{typeof(Genie.AppServer.setup_http_handler)}, ::HTTP.Streams.Stream{HTTP.Messages.Request,HTTP.ConnectionPool.Transaction{Sockets.TCPSocket}}) at /home/maxime/.julia/packages/HTTP/IAI92/src/Handlers.jl:276
(::Genie.AppServer.var"#6#13"{Int64,Int64})(::HTTP.Streams.Stream{HTTP.Messages.Request,HTTP.ConnectionPool.Transaction{Sockets.TCPSocket}}) at /home/maxime/.julia/packages/Genie/3rr2f/src/AppServer.jl:78
macro expansion at /home/maxime/.julia/packages/HTTP/IAI92/src/Servers.jl:367 [inlined]
(::HTTP.Servers.var"#13#14"{Genie.AppServer.var"#6#13"{Int64,Int64},HTTP.ConnectionPool.Transaction{Sockets.TCPSocket},HTTP.Streams.Stream{HTTP.Messages.Request,HTTP.ConnectionPool.Transaction{Sockets.TCPSocket}}})() at ./task.jl:356

**Comment by essenciary** [comment]
@MaximeRivest oh wow, that's for flagging this, it's a big one! Wonder if we should add the whole set of SVG elements? 
https://developer.mozilla.org/en-US/docs/Web/SVG/Element/rect

**Comment by essenciary** [comment]
https://developer.mozilla.org/en-US/docs/Web/SVG/Element

**Comment by MaximeRivest** [comment]
I'm not "composing" enough SVG to know... and I have not looked into Genie's code enough to know what that implies.

As a more temporary patch, the documentation could be updated on the templates to inform the user that static svg files can be linked to. But SVG cannot be inserted in the template. 

I guess one thing I would consider is the possibility that a Genie user composes SVG programmatically with something like Luxor. Or output SVG/Js code from plotly and the likes.

If you point me in the right direction, I can try to contribute to the documentation piece.

**Comment by essenciary** [comment]
@MaximeRivest No worries, it's not that complicated. Basically Genie creates tag rendering functions so in this case it's missing the corresponding `svg(...)` function. I think we can just add all the standard, well supported elements, but probably in a separate module so they are not loaded by default. 

For now you can manually add support for elements using 
```julia
Genie.Renderer.Html.register_normal_element("svg", context = @__MODULE__)
Genie.Renderer.Html.register_void_element("rect", context = @__MODULE__)
```

Normal elements have a closing tag, void don't. 

I'll add support for the SVG elements in the next release.

**Comment by essenciary** [comment]
I've added support for SVG elements into `Renderer.Html` but the tags need to be explicitly loaded with `Html.register_svg_slements()`.

**Comment by diegozea** [comment]
Hello @essenciary ! Can the error message point to `Html.register_svg_slements()` when an `svg` tag is found instead of returning the `UndefVarError: svg not defined`? Best,

**Comment by diegozea** [comment]
Also, where should it be placed? I added it to the controller, and I get the following error message breaking the app:

```julia
ERROR: LoadError: Evaluation into the closed module `Html` breaks incremental compilation because the side effects will not be permanent. This is likely due to some other module mutating `Html` with `eval` during precompilation - don't do this.
Stacktrace:
  [1] eval
    @ ./boot.jl:360 [inlined]
  [2] register_normal_element(elem::Symbol; context::Module)
    @ Genie.Renderer.Html ~/.julia/packages/Genie/35M8N/src/renderers/Html.jl:796
  [3] register_normal_element
    @ ~/.julia/packages/Genie/35M8N/src/renderers/Html.jl:796 [inlined]
  [4] #register_svg_slements#37
    @ ~/.julia/packages/Genie/35M8N/src/renderers/Html.jl:772 [inlined]
  [5] register_svg_slements()
    @ Genie.Renderer.Html ~/.julia/packages/Genie/35M8N/src/renderers/Html.jl:771
  [6] top-level scope
    @ ~/Documents/MASSIV/ThorAxeSupplementaryWebsite/app/resources/thoraxeresults/ThorAxeResultsController.jl:10
  [7] include
    @ ./Base.jl:386 [inlined]
  [8] include_package_for_output(pkg::Base.PkgId, input::String, depot_path::Vector{String}, dl_load_path::Vector{String}, load_path::Vector{String}, concrete_deps::Vector{Pair{Base.PkgId, UInt64}}, source::String)
    @ Base ./loading.jl:1213
  [9] top-level scope
    @ none:1
 [10] eval
    @ ./boot.jl:360 [inlined]
 [11] eval(x::Expr)
    @ Base.MainInclude ./client.jl:446
 [12] top-level scope
    @ none:1
in expression starting at /home/diego/Documents/MASSIV/ThorAxeSupplementaryWebsite/app/resources/thoraxeresults/ThorAxeResultsController.jl:1
ERROR: Failed to precompile ThorAxeResultsController [top-level] to /home/diego/.julia/compiled/v1.6/jl_nNhsog.
Stacktrace:
 [1] error(s::String)
   @ Base ./error.jl:33
 [2] compilecache(pkg::Base.PkgId, path::String, internal_stderr::Base.TTY, internal_stdout::Base.TTY)
   @ Base ./loading.jl:1360
 [3] compilecache(pkg::Base.PkgId, path::String)
   @ Base ./loading.jl:1306
 [4] _require(pkg::Base.PkgId)
   @ Base ./loading.jl:1021
 [5] require(uuidkey::Base.PkgId)
   @ Base ./loading.jl:914
 [6] require(into::Module, mod::Symbol)
   @ Base ./loading.jl:901
 [7] top-level scope
   @ ~/Documents/MASSIV/ThorAxeSupplementaryWebsite/routes.jl:2
in expression starting at /home/diego/Documents/MASSIV/ThorAxeSupplementaryWebsite/routes.jl:2

```

**Comment by essenciary** [comment]
@diegozea how do you get the precompilation error, it works for me. 

Also, there are passing tests: 
https://github.com/GenieFramework/Genie.jl/blob/master/test/tests_SVG_API.jl

**Comment by diegozea** [comment]
Is it a version problem? I am on Julia 1.6.0 with Genie 1.17.1:

```
  [336ed68f] CSV v0.8.4
  [a93c6f00] DataFrames v0.22.7
  [864edb3b] DataStructures v0.18.9
  [c43c736e] Genie v1.17.1
  [c27321d9] Glob v1.3.0
  [e6f89c97] LoggingExtras v0.4.6
  [739be429] MbedTLS v1.0.3
```

**Comment by diegozea** [comment]
The problem only happens when I include the line in the [controller](https://github.com/PhyloSofS-Team/ThorAxeSupplementaryWebsite/blob/38f1edd512a435257b9a874fe83d5060f0a872e8/app/resources/thoraxeresults/ThorAxeResultsController.jl#L9), but it works fine in the REPL:

![image](https://user-images.githubusercontent.com/2822757/114199272-6e31eb80-9954-11eb-82a3-fe0c0a69b2a8.png)

**Comment by essenciary** [comment]
What's in ThorAxeResultsController.jl?

**Comment by diegozea** [comment]
You can find the code here: https://github.com/PhyloSofS-Team/ThorAxeSupplementaryWebsite/blob/38f1edd512a435257b9a874fe83d5060f0a872e8/app/resources/thoraxeresults/ThorAxeResultsController.jl

**Comment by essenciary** [comment]
Thanks... no clue... where do you call `Html.register_svg_slements()`?

**Comment by diegozea** [comment]
I added it on line 9, just after `using Glob`.

**Comment by essenciary** [comment]
Ah ok but it's not here. Did you delete it? 
![image](https://user-images.githubusercontent.com/11292378/114231643-fb883680-997a-11eb-82af-52e51089a219.png)

**Comment by diegozea** [comment]
I haven't committed that; I have only tested that locally.  For the moment, I am adding the `svg` tag using jQuery.

**Comment by essenciary** [comment]
@diegozea Interesting - we need a simple working example to see how it fails in a script. Not sure about the working in REPL part since the test passes. 

Can you try calling 'Genie.Renderer.Html.register_svg_slements()` before `using Genie.Renderer.Html`? Curious what happens...

**Comment by diegozea** [comment]
It looks to me that the problem only appears when this is used inside the code of a package, breaking precompilation: ```ERROR: LoadError: Evaluation into the closed module `Html` breaks incremental compilation because the side effects will not be permanent. This is likely due to some other module mutating `Html` with `eval` during precompilation - don't do this.```

**Comment by essenciary** [comment]
On the latest master SVG support is enabled by default - seems to work great now.
