### ISSUE TITLE
change logic on function normal_element, line 68 from Genie.Renderer.Html

### ISSUE THREAD

**Issue by cindRoberta** [GenieFramework/Genie.jl#307]
**Is your feature request related to a problem? Please describe.**
now, this works
```julia
h1("texto"; id = "id", class = "classe",
    style = "color: blue; font-family: Verdana;")
```

**Describe the solution you'd like**
style accepts Tuple or Dict
```julia
h1("texto"; id = "id", class = "classe",
  style = Dict(:color => "blue", :fontFamily => "Verdana")
)
```

**Describe alternatives you've considered**

**Comment by essenciary** [comment]
That's a pretty complicated change as we need to modify quite a few methods to accept `Dict` arguments. Also `:fontFamily` would need to be parsed and converted to `font-family`? What is the benefit of this? What is a good use case for it?

**Comment by cindRoberta** [comment]
> That's a pretty complicated change as we need to modify quite a few methods to accept `Dict` arguments. Also `:fontFamily` would need to be parsed and converted to `font-family`? What is the benefit of this? What is a good use case for it?

Also `:fontFamily` would need to be parsed and converted to `font-family`?
yes

What is the benefit of this? What is a good use case for it?
in practice, none. My motivation is the same as in React and Flutter. React use objects, but could use string interpolation for CSS and sub-properties, Flutter uses object instances

so I would say: elegancy, practicality

this issue is not crucial, but please, don't close it, it was considered by the 2 biggest UI frameworks and I think it should be considered here
