### ISSUE TITLE
macro @query

### ISSUE THREAD

**Issue by cindRoberta** [GenieFramework/Genie.jl#308]
**Is your feature request related to a problem? Please describe.**
Express separates params and queries

**Describe the solution you'd like**
a macro @query (I prefer on singular, same to @param)

**Comment by essenciary** [comment]
Let me see if I understand this. 

Would @query return the query part? Eg the GET params? So say some.url.com/foo/bar?x=1&y=abc

@query would return Dict(:x => "1", :y => "abc") ?

**Comment by essenciary** [comment]
Added a `@query` macro similar to `@params`. And also `@post` and `@headers`.

**Comment by cindRoberta** [comment]
> Added a `@query` macro similar to `@params`. And also `@post` and `@headers`.

https://github.com/GenieFramework/Genie.jl/blob/master/src/Router.jl line 17, thanks
