### ISSUE TITLE
HTML renderer removes script nodes

### ISSUE THREAD

**Issue by poldavezac** [GenieFramework/Genie.jl#316]
**Describe the bug**

Script nodes are removed from the html output. This is evident in the temporary module files created by Genie.

**To reproduce**
Steps to reproduce the behavior and/or Julia code executed.
1. create a view with an html template containing a script node
2. call the page: no script node

**Expected behavior**
One would expect the script node to be there.

**Additional context**
Please include the output of 
Julia Version 1.5.0
Commit 96786e22cc (2020-08-01 23:44 UTC)
Platform Info:
  OS: Linux (x86_64-pc-linux-gnu)
  CPU: Intel(R) Core(TM) i7-8750H CPU @ 2.20GHz
  WORD_SIZE: 64
  LIBM: libopenlibm
  LLVM: libLLVM-9.0.1 (ORCJIT, skylake)
Environment:
  JULIA_NUM_THREADS = 3
and
  [c52e3926] Atom v0.12.27
  [a93c6f00] DataFrames v0.22.1
  [c43c736e] Genie v1.9.0
  [708ec375] Gumbo v0.8.0
  [f67ccb44] HDF5 v0.14.3
  [e5e0dc1b] Juno v0.8.4
  [5fb14364] OhMyREPL v0.5.10
  [91a5bcdd] Plots v1.9.1
  [c3e4b0f8] Pluto v0.12.16
  [295af30f] Revise v3.1.9

**Comment by poldavezac** [comment]
I think I found the bug:
```diff
diff --git a/src/renderers/Html.jl b/src/renderers/Html.jl
index 2babaec..f34ad38 100644
--- a/src/renderers/Html.jl
+++ b/src/renderers/Html.jl
@@ -502,10 +502,8 @@ function parsehtml(elem::HTMLParser.HTMLElement, depth::Int = 0; partial::Bool =
 
   invalid_tag = partial && (tag_name == "html" || tag_name == "head" || tag_name == "body")
 
-  if tag_name == "script" && in("type", collect(keys(HTMLParser.attrs(elem))))
-    if HTMLParser.attrs(elem)["type"] == "julia/eval"
-      isempty(HTMLParser.children(elem)) || print(io, repeat("\t", depth), string(HTMLParser.children(elem)[1].text), "\n")
-    end
+  if tag_name == "script" && get(HTMLParser.attrs(elem), "type", "") ≡ "julia/eval"
+    isempty(HTMLParser.children(elem)) || print(io, repeat("\t", depth), string(HTMLParser.children(elem)[1].text), "\n")
 
   else
     mdl = isdefined(@__MODULE__, Symbol(tag_name)) ? string(@__MODULE__, ".") : ""
@@ -989,4 +987,4 @@ end
 
 register_elements()
 
-end
\ No newline at end of file
+end
```

**Comment by essenciary** [comment]
@poldavezac Thanks for reporting this - sorry I didn't have the chance to reply sooner. I'll run some tests, I'm not sure why it breaks, even in the above snippet :-/

**Comment by poldavezac** [comment]
@essenciary  The patch works on my machine.  I don't think it's a bug per say, meaning no traceback expected. Its just that the `if` conditions are too wide and discard my specific use case: a js script node which should be treated not a julia one but as a generic html one.

**Comment by essenciary** [comment]
@poldavezac Thanks for the details! Can you please pass the actual HTML code? Is it because you have the `script` tag with a `type` attribute?

**Comment by poldavezac** [comment]
sure: the following `<script>` node will not appear in the browser unless the patch is applied.

```html
<div id="$(@vars(:divname))">
    <canvas id="$(@vars(:canvasname))" width=$(@vars(:width)) height=$(@vars(:height))>
    </canvas>
</div>
<script type="text/javascript">
    dpxdaqservercam.add(document.getElementById("$(@vars(:canvasname))"))
</script>
```

used with

```julia
"return the html code for viewing the microscope frames"
function camerahtml(cview::CameraCanvas)
    return html(
         :camera, :camserver;
         (
              i => getfield(@__MODULE__, i)(cview)
              for i = (:divname, :canvasname, :width, :height)
         )...
    )
end

route("/camera/frames", named = :camera_frames) do
    camerahtml(cview)
end
```

**Comment by essenciary** [comment]
@poldavezac I am not able to reproduce the issue in my tests. Would it be possible to share a minimum functioning example app that I can run in order to reproduce the problem? Thank you.

**Comment by poldavezac** [comment]
Note that I could not reproduce the bug either unless the I was using a separate  view/xxx.jl.html file instead. Directly using a string in the routes.jl file works like a charm.

The minimal example app is:

1. in  `routes.jl`:
```julia
using Genie.Router
using Genie.Renderer
using Genie.Renderer.Js
using Genie.Renderer.Html

route("/") do
    return html(:xxx, :xxx; canvasname = :toto)
end

```
2. in `app/resources/xxx/views/xxx.jl.html`: 
```html
<div>
    <canvas id="xxx">
    </canvas>
</div>
<script type="text/javascript">
   alert("Found a script node!")
</script>
```

tested on *Genie v1.1*, the `alert` message will not appear.

**Comment by essenciary** [comment]
@poldavezac Thank you, I was able to reproduce it and fix it (on #master)
