### ISSUE TITLE
Make Windows executables more robust

### ISSUE THREAD

**Issue by BenediktAllendorf** [GenieFramework/Genie.jl#320]
**Is your feature request related to a problem? Please describe.**
After updating Julia on Windows, the bin/bat-files might not work anymore.

**Describe the solution you'd like**
I'd suggest to not use the (generated) full path to Julia but just "julia" as the command. I think it's reasonable to expect users to handle this. Maybe add an additional message like:

```
julia --color=yes --depwarn=no -q -i -- %~dp0\..\bootstrap.jl si %* ||\
 (echo Julia executable not found! && echo You might need to add julia to your $PATH && exit /b 1)
```

**Additional context**
As you might notice, I also changed `../bootstrap.jl` to `%~dp0\..\bootstrap.jl`. As #318, this allows you to run the script from anywhere (currently, you have to be in the bin-folder).

Besides everything else, you could always add those files to the bin-folder (like the nix-files) and the generation would not be required anymore. 

If desired, I can create a PR for this.

**Comment by DhruvaSambrani** [comment]
- I concur on not using the exact path, as if I share with others for dev, then julia may not be installed to the same place
- For windows, as of #314, the scripts can be run from anywhere. Not sure if the feature has been released though. #318 was to do the same for *nix
- Generation is still necessary if, like me, you delete the scripts thinking they were unnecessary :joy:

**Comment by BenediktAllendorf** [comment]
Oh, I missed #313. But, I thought about it again and it should be `"%~dp0../$(Genie.BOOTSTRAP_FILE_NAME)"` (with quotes). 😁

And about the generation, there is nothing to generate anymore, is it? So the scripts are static and if you delete them, you can just restore them by copying them. So I'd argue to include the *.bat files in here https://github.com/GenieFramework/Genie.jl/tree/master/files/new_app/bin and get rid of "generating" altogether.

Besides that, https://github.com/GenieFramework/Genie.jl/blob/5a1fe65758dda8b7464548536971e2b9719bfc46/src/Generator.jl#L153 only set permission for `server ` and `repl`. Is that on purpose?

**Comment by DhruvaSambrani** [comment]
Yup, it should be quoted because of spaces in the text.

But the generators can now be rewritten to simply copy the files. There should still be the generators I feel, but there's nothing lost if we remove it either

**Comment by essenciary** [comment]
@BenediktAllendorf @DhruvaSambrani Thanks for the input! Let's see if we can come up with a strategy for these. 

1. In my opinion, it's better if upon creating a new app, the scripts just work. That implies using the exact path to Julia. Adding Julia to PATH on Windows is not that straightforward and it's not done automatically by the Julia installer, so we should not make any assumptions that Julia is added to PATH. This no assumptions approach is beginner/non-dev friendly. 

On the other hand, if somebody is skilled enough to add Julia to PATH, it is very simple to edit the scripts and update the PATH. 

2. I don't fully understand the issue about generators - is there any problem with rerunning `Genie.Generator.setup_windows_bin_files()`? 

3. Permissions for `server` and `repl` - just a bug, upon adding the additional files, I forgot to update the permissions script 😒 But @DhruvaSambrani pushed a very nice patch for that! 🎉

4. Can you please review the current master, with the merged PRs? I think it's looking pretty good now and we can release a new version.

**Comment by DhruvaSambrani** [comment]
Hi @essenciary,

1. Cool.

2. @BenediktAllendorf just preferred not having the functions and just use default files, as 

3. I don't remember clearly what I did to the chmod thing in my PR, but I think I left it as is. Please do check if it's ok once more

4. Please note that the paths need to be escaped and then you can test. I'll send in a PR in about an hour or 2, unless someone else does it first

**Comment by BenediktAllendorf** [comment]
1) I can see why having the scripts just work is nice in the beginning. But as soon as you update your Julia version or share it with other developers, it breaks. So it's working nicely for some time, and then suddenly it does not anymore.
And I'd argue that if you are using Julia, you are dev enough to fix your PATH (which is quite easy nowadays). Also, I would say you are not supposed to change those files, because they are part of the Genie-Core. So if something get's updated and I have locally adjusted my files, I have to manually merge.

2) About the generators in general, I'm not convinced yet. You have duplicated code now: once in the files/new_app, once in the generator (let aside that the four scripts/lines are also almost duplicates which could be another PR). The generators do not work if the whole "bin"-directory has been deleted and there might be more cases where something is broken/wrong. I'm not supposed to just delete random files, and there aren't generators for everything, right? (What happens, if I delete `bootstrap.jl` for example?)

4) #323 escapes the path for windows (and uses backslashes) now. :)

**Comment by essenciary** [comment]
1. > And I'd argue that if you are using Julia, you are dev enough to fix your PATH
That has not been my experience with many Julia and Genie users. The usability and support cost of having a new app breaking upon creation is much higher. I'm open to making the logic more robust though, eg trying to see if Julia is in path and using it if it is, or using the full path if it's not. 
2. I don't think `bootstrap.jl` and the `bin` files should be treated the same. `bootstrap.jl` is a core file, the ones in `bin` are not. Optional files have generators so they can be created on demand/as needed. Others like `bootstrap.jl` are not. 
Indeed, it doesn't make sense to have files in `files/new_app/bin/` and generators - I'll remove the ones in `bin/`, the generators should just work.
3. Thank you :) Merging, testing and releasing. :D

**Comment by DhruvaSambrani** [comment]
The bin files are extremely development environment specific. Why not gitignore bin, and create the bin folder on first run?

**Comment by BenediktAllendorf** [comment]
Yeah, maybe I'm biased regarding the PATH, you know the user base better than I.

So when keeping it, I'm in favor of @DhruvaSambrani's suggestion to make sure the bin-files are not "part of the app" but "part of your local setup".

And I see that you have removed the `new_app/bin`-directory. But I guess now you have to update the `microstack_app`-function because generating a new app fails in https://github.com/GenieFramework/Genie.jl/blob/master/src/Generator.jl#L319:
(I didn't really debug this; it's more an educated guess that this is related)

```
ERROR: IOError: open: no such file or directory (ENOENT)
Stacktrace:
 [1] uv_error at .\libuv.jl:97 [inlined]
 [2] open(::String, ::UInt16, ::Int64) at .\filesystem.jl:87
 [3] open at .\filesystem.jl:79 [inlined]
 [4] sendfile(::String, ::String) at .\file.jl:938
 [5] cp(::String, ::String; force::Bool, follow_symlinks::Bool) at .\file.jl:351
 [6] cp at .\file.jl:345 [inlined]
 [7] microstack_app(::String, ::String) at C:\Users\Ben\.julia\packages\Genie\OVMRt\src\Generator.jl:319
 [8] newapp(::String; autostart::Bool, fullstack::Bool, dbsupport::Bool, mvcsupport::Bool, testmode::Bool) at C:\Users\Ben\.julia\packages\Genie\OVMRt\src\Generator.jl:522
 [9] #newapp_webservice#35 at C:\Users\Ben\.julia\packages\Genie\OVMRt\src\Generator.jl:573 [inlined]
 [10] newapp_webservice(::String) at C:\Users\Ben\.julia\packages\Genie\OVMRt\src\Generator.jl:573
 [11] top-level scope at REPL[8]:1
```

So I guess copying the bin directory has to be taken out and additionally, the generators have to check (and create if necessary) the bin-directory?

👍  for removing `serverinteractive`

**Comment by essenciary** [comment]
@DhruvaSambrani What do you have in mind with "first run"? How would that work without the `bin`? 
@BenediktAllendorf Debugging that, not sure why it successfully creates apps for me on Windows but fails on Linux :-/

**Comment by essenciary** [comment]
Oh yes, because locally on win I still have the `bin/` folder.

**Comment by DhruvaSambrani** [comment]
Also, when a dev wants to develop, they need to run some setup commands anyway, like adding the secrets file, among others.

I ended up writing a script called setup.jl or some equivalent. This could be formalized, and the setup file be generated instead of the bin. The setup.jl can call the bin creation, according to the OS and other stuff.

**Comment by DhruvaSambrani** [comment]
> @BenediktAllendorf Debugging that, not sure why it successfully creates apps for me on Windows but fails on Linux :-/ 

I assume because for Linux it tries to copy the bin folder, and in windows it generates the files from the functions?

**Comment by essenciary** [comment]
@DhruvaSambrani You mean copying the secrets file upon deployment? Yes, that makes sense: generating the secrets file plus the bins. All of these have generators so we could just bundle them into a `Generator.appsetup` method? 

Both *nix and win generate the bin files now. It was because the `bin/` file was removed by git being empty. I have addressed this and everything seems to work perfectly! 

I think we can close this issue and potentially open a new one for `Generator.appsetup` if we decide to go down this path?

**Comment by DhruvaSambrani** [comment]
I'd prefer having a file instead of a generator here, because any non Trivial app will have other setup steps. If a file was made, then I can add these steps. If a generator is to be used, then I again need to make the file and call the generator.
