### ISSUE TITLE
CORS error when making DELETE and PUT requests from browser

### ISSUE THREAD

**Issue by p-gw** [GenieFramework/Genie.jl#325]
**Description**
As described on [Gitter](https://gitter.im/essenciary/Genie.jl?at=5fd8d4a9c614d23c2e0d68f2) I am getting CORS errors when making `DELETE` and `PUT` requests from my javascript frontend to my Genie.jl API. @essenciary suggested this might be a bug so I am making a bug report here. 

**To reproduce**
This issue can be reproduced by first creating a minimal API, 

```julia
using Genie, Genie.Renderer.Json

Genie.config.run_as_server = true
Genie.config.cors_headers["Access-Control-Allow-Origin"]  =  "*"
Genie.config.cors_headers["Access-Control-Allow-Headers"] = "Content-Type"
Genie.config.cors_headers["Access-Control-Allow-Methods"] = "GET,POST,PUT,DELETE,OPTIONS"
Genie.config.cors_allowed_origins = ["*"]

route("/", method = GET) do
  Dict("message" => "return message") |> json 
end

route("/", method = POST) do 
  @info "add something"
  Dict("message" => "return message") |> json 
end

route("/", method = DELETE) do 
  @info "delete something"
  Dict("message" => "return message") |> json 
end

route("/", method = PUT) do 
  @info "update something"
  Dict("message" => "return message") |> json 
end

up()
```

Then, the behaviour can be tested in the browser with a server on a different port. `GET` and `POST` requests give the correct response,

 ```javascript
fetch("http://127.0.0.1:8000/", { method: "get" }).then(r => r.json()).then(json => console.log(json));
// {message: "return message"}
```

```javascript
fetch("http://127.0.0.1:8000/", { method: "post" }).then(r => r.json()).then(json => console.log(json));
// {message: "return message"}
```

`DELETE` and `PUT` methods throw a CORS error.

```javascript
fetch("http://127.0.0.1:8000/", { method: "delete" }).then(r => r.json()).then(json => console.log(json));
// Access to fetch at 'http://127.0.0.1:8000/' from origin 'http://127.0.0.1:5500' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource. If an opaque response serves your needs, set the request's mode to 'no-cors' to fetch the resource with CORS disabled.
// DELETE http://127.0.0.1:8000/ net::ERR_FAILED
// Uncaught (in promise) TypeError: Failed to fetch
```

```javascript
fetch("http://127.0.0.1:8000/", { method: "put" }).then(r => r.json()).then(json => console.log(json));
// Access to fetch at 'http://127.0.0.1:8000/' from origin 'http://127.0.0.1:5500' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource. If an opaque response serves your needs, set the request's mode to 'no-cors' to fetch the resource with CORS disabled.
// PUT http://127.0.0.1:8000/ net::ERR_FAILED
// Uncaught (in promise) TypeError: Failed to fetch
```

**Expected behavior**
The expected behaviour is that `DELETE` and `PUT` requests work in the same way `GET` and `POST` requests do, since the Genie config explicitly specifies `Access-Control-Allow-Method`.

**Additional context**
I suspect the error arises from the fact that the response headers do not get appropriately set for `DELETE` and `PUT` requests, e.g.

```
HTTP/1.1 200 OK
Content-Type: application/json; charset=utf-8
Server: Genie/1.9.0/Julia/1.4.2
Transfer-Encoding: chunked
```

is the header i get from `DELETE`. The access control headers from the Genie config are not added. I feel like the issue arises in

https://github.com/GenieFramework/Genie.jl/blob/14b93a29e395b9fc8a4d01198eebf8873990be68/src/Headers.jl#L15

I am running Julia version `1.4.2` and Genie version `1.9.0`.

**Comment by essenciary** [comment]
@p-gw Thank you for reporting this. I think you're right, CORS seems to be explicitly limited to OPTIONS, GET and POST methods. I'm not sure why, reading on it now my understanding is that it should be available for DELETE as well. Maybe we should just remove the the `if` and check CORS for every request?

**Comment by p-gw** [comment]
I just tried it and getting rid of the `if` clause in `set_headers!` results in the correct behaviour: 

```javascript
fetch("http://127.0.0.1:8000/", { method: "delete" }).then(r => r.json()).then(json => console.log(json));
// {message: "return message"}
```

**Comment by essenciary** [comment]
Thanks @p-gw I pushed an update to master. If all good, I'll tag a new release. Thanks!
