### ISSUE TITLE
Allow for non-string attributes

### ISSUE THREAD

**Issue by hhaensel** [GenieFramework/Genie.jl#329]
Currently, `Genie.Renderer.Html.attributes()` always prints all attribute values with double quotes.

In some situations, however, vue components require numbers or boolean values or objects to be supplied. Hence I propose to modify the routine to something like:
```
function attributes(attrs::Vector{Pair{Symbol,Any}} = Vector{Pair{Symbol,Any}}()) :: String
  a = IOBuffer()

  for (k,v) in attrs
    v === nothing && continue # skip nothing values

    if (isa(v, Bool) && v) || isempty(string(v))
      print(a, "$(k |> parseattr) ")
    elseif typeof(v) <: AbstractString
      print(a, "$(k |> parseattr)=\"$(v)\" ")
    elseif typeof(v) == Genie.Renderer.Json.JSONParser.JSONText
      print(a, "$(k |> parseattr)=$(v.s) ")
    else
      print(a, "$(k |> parseattr)=$(v) ")
    end
  end

  String(take!(a))
end
```
which only surrounds string types with double quotes. Furthermore, it accepts JSONText to suppress the quotes.
Alternatively, we could suppress quoting for Number types only ...

**Comment by hhaensel** [comment]
BTW, concerning [StippleUI PR5](https://github.com/GenieFramework/StippleUI.jl/pull/5):
I just realised, that here we have `parseattr` which does a "__"=>"-" replacement...

Maybe, we then don't need any addtional replacement rule in order not to confuse people?

**Comment by hhaensel** [comment]
Examples:
```
julia> Genie.Renderer.Html.attributes([:test=>3, :me=>[1,2]])
"test=3 me=[1, 2] "

julia> using Stipple, StippleUI
julia> vue(:newelem; test="me", options=JSONText("{x: 10px; y: 20px}"))
"<vue-newelem test=\"me\" options={x: 10px; y: 20px}></vue-newelem>"
```

**Comment by essenciary** [comment]
@hhaensel Thank you - makes sense! Is it breaking (seems not to be)?
Re "__"=>"-" agreed, to avoid duplication.

**Comment by hhaensel** [comment]
I don't think, it's breaking. If it is, in most cases JS will do the necessary conversion in the backend ...
So, I think you can merge 😉
