### ISSUE TITLE
Issues with "Using Genie With Docker"

### ISSUE THREAD

**Issue by MrBlenny** [GenieFramework/Genie.jl#330]
I've followed the ["Using Genie with Docker"](https://genieframework.github.io/Genie.jl/dev/tutorials/16--Using_Genie_With_Docker.html) guide and ran into a couple of issues.

## Issue 1 - Dockerfile
The generated dockerfile containts `RUN chmod +x bin/serverinteractive` but the generated `bin` folder does not. This causes the following error when building the docker container: `cannot access 'bin/serverinteractive': No such file or directory`

This can be resolved by removing this line from the dockerfile

## Issue 2 - Generated bin scripts
The generated bin scripts for `repl`, `runtask`, and `server` inside the `/bin` folder have a formatting issue.

For example, `repl` contains:

```#!/bin/sh\njulia --color=yes --depwarn=no --project=@. -q -L $(dirname $0)/../bootstrap.jl -- "$@"```

It should contain:
```
#!/bin/sh
julia --color=yes --depwarn=no --project=@. -q -L $(dirname $0)/../bootstrap.jl -- "$@"
```

This is fixed by replacing the `\n` string with an actual new line

**Comment by essenciary** [comment]
@MrBlenny Thanks I fixed Issue 1 and merged a PR which addressed Issue 2
On #master now, will tag a patch release (1.11.1)

**Comment by MrBlenny** [comment]
Fantastic, thanks!
