### ISSUE TITLE
QPS difference with HTTP.jl

### ISSUE THREAD

**Issue by Cyvadra** [GenieFramework/Genie.jl#333]
```julia
using HTTP, Genie
@async HTTP.serve() do request::HTTP.Request
  HTTP.Response("hello")
  end
#...
Genie.startup()
route("/ping";method="GET") do
  "pong"
  end
#...
down()
```

```bash
➜  ~ wrk -c 120 -d 10 -t 120 -H -–latency --timeout 3s http://127.0.0.1:8081 # @async HTTP.serve   
Running 10s test @ http://127.0.0.1:8081
  120 threads and 120 connections
  Thread Stats   Avg      Stdev     Max   +/- Stdev
    Latency    13.91ms    6.70ms 135.41ms   96.64%
    Req/Sec    74.75     13.57   161.00     72.64%
  90263 requests in 10.10s, 5.34MB read
Requests/sec:   8933.27
Transfer/sec:    541.28KB
➜  ~ 
➜  ~ wrk -c 120 -d 10 -t 120 -H -–latency --timeout 3s http://127.0.0.1:8000/ping # Genie.route  
Running 10s test @ http://127.0.0.1:8000/ping
  120 threads and 120 connections
  Thread Stats   Avg      Stdev     Max   +/- Stdev
    Latency    37.68ms    7.68ms 139.80ms   79.90%
    Req/Sec    26.48      5.53    40.00     62.68%
  32151 requests in 10.11s, 9.54MB read
Requests/sec:   3180.67
Transfer/sec:      0.94MB
➜  ~
➜  ~ wrk -c 120 -d 10 -t 120 -H -–latency --timeout 3s http://localhost:8000/some_404 # golang gin
Running 10s test @ http://localhost:8000/some_404
  120 threads and 120 connections
  Thread Stats   Avg      Stdev     Max   +/- Stdev
    Latency     3.36ms    3.55ms  69.08ms   91.34%
    Req/Sec   346.64     61.57     1.20k    78.29%
  416360 requests in 10.10s, 190.59MB read
  Non-2xx or 3xx responses: 416360
Requests/sec:  41206.52
Transfer/sec:     18.86MB
➜  ~
```

it seems we have more memory allocations than golang and thus slower

then how to maximize the advantage of WebChannels……

**Comment by Cyvadra** [comment]
benchmarking tool: [wrk](https://github.com/wg/wrk)

**Comment by essenciary** [comment]
1. There is room for performance optimizations in both Genie and HTTP. 
2. What does "some_404" do/output? 
3. For Genie it's expected as it does a lot more work compared to HTTP to server a request (Genie runs off HTTP and adds features/computations) - though like I said, I'm sure more performance can be squeezed out. 
4. How can Genie transfer 2x more than HTTP while handling1/3 req/s? That looks weird.

**Comment by Cyvadra** [comment]
Maybe.. I've been trying these days to figure out
Then I established an http server directly on Sockets.jl:
```julia
using Sockets
server = Sockets.TCPServer(; delay=false)
inet = Sockets.InetAddr("0.0.0.0",8081)
Sockets.bind(server, inet.host, inet.port; reuseaddr=true)
Sockets.listen(server)
d = Vector{UInt8}("""HTTP/1.1 200 OK\nDate: Wed, 27 Jan 2021 21:16:00 UTC
Content-Length: 80\nContent-Type: text/plain\n
3.141592653589793238462643383279502884197169399375105820974944592307816406286198""");
function lambda(conn::TCPSocket)::Nothing
  try
    #line = readline(conn)
    write(conn,d)
    close(conn)
  catch err
    print("connection ended with error $err")
  end
  return nothing
  end
while true
  conn = accept(server)
  async lambda(conn)
  end
```
```bash
➜  ~ wrk -c 100 -d 10 -t 100 -H -–latency --timeout 3s http://127.0.0.1:8081
Running 10s test @ http://127.0.0.1:8081
  100 threads and 100 connections
  Thread Stats   Avg      Stdev     Max   +/- Stdev
    Latency     8.61ms   13.44ms 144.44ms   95.28%
    Req/Sec   145.78     37.11   191.00     84.20%
  145521 requests in 10.21s, 24.56MB read
  Socket errors: connect 0, read 138869, write 6652, timeout 0
Requests/sec:  14248.27
Transfer/sec:      2.41MB
```

It seems Sockets.jl itself is not optimized for http use..
Other frameworks might have some tricks to improve performance, which I'm not quite familiar with.

**Comment by Cyvadra** [comment]
2. "some_404" output like usual. I later tried normal requests to gin and got roughly same results.
3. 3k has been enough for common use I think... I'm just confused about the difference
4. Genie transfer more than HTTP.jl when using headers, which doesn't affect the performance much.

> Thanks
> 
> 1. There is room for performance optimizations in both Genie and HTTP.jl.
> 2. What does "some_404" do/output?
> 3. For Genie it's expected as it does a lot more work compared to HTTP.jl to serve a request (Genie runs off HTTP.jl and adds features/computations) - though like I said, I'm sure more performance can be squeezed out.
> 4. How can Genie transfer 2x more than HTTP.jl while handling1/3 req/s? That looks weird.

**Comment by Cyvadra** [comment]
15000 qps is the maximum of libuv, which Sockets.jl used for handling requests. Well enough.
