### ISSUE TITLE
Genie on Repl.it

### ISSUE THREAD

**Issue by schnetzlerjoe** [GenieFramework/Genie.jl#339]
I am trying to run Genie on repl.it (found here https://repl.it/@JoeSchnetzler/Genie#main.jl) and I can not get it to work for the death of me. I can get it to download but it refuses to compile. Any help? Truly appreciate it!

Best,
Joe

**Comment by essenciary** [comment]
I tried it too a while ago - I think a REPL.it VM/container is just too tiny and precompilation times out. I've also been running some tests on the free Heroku instances and at 512MB RAM and tiny CPU resurces, precompilation was a nightmare. I had to do some precompilation tricks as part of the image setup (on Heroku) but I don't think this is an option on REPL. Maybe with Julia 1.6 things will improve.

**Comment by schnetzlerjoe** [comment]
> I tried it too a while ago - I think a REPL.it VM/container is just too tiny and precompilation times out. I've also been running some tests on the free Heroku instances and at 512MB RAM and tiny CPU resurces, precompilation was a nightmare. I had to do some precompilation tricks as part of the image setup (on Heroku) but I don't think this is an option on REPL. Maybe with Julia 1.6 things will improve.

I got it compiled finally with the new version! Great work. Excited to start using this with repl.it. it's my go to ide with my team!

**Comment by essenciary** [comment]
@schnetzlerjoe Yeee, thanks for letting me know!
