### ISSUE TITLE
POST params not found

### ISSUE THREAD

**Issue by wadehenning** [GenieFramework/Genie.jl#341]
**Describe the bug**
I am calling a POST route from JavaScript but my Genie server does not see the parameters I am sending.  

**Error stacktrace**
For  parameter named `dim`:, the JavaScript console returns:
`error: "500 Internal Error - KeyError: key :dim not found↵getindex at`

**To reproduce**
***Relevant JavaScript***
```
let params = {
    dim: '2',
    num: '6'
  }  
  const url = 'http://127.0.0.1:8000/random'
  fetch(url, 
    {         method: 'POST',
              mode: "cors",             
              headers: { 
                'Accept': 'application/json',
                'Content-type': 'application/json' } ,          
              body: JSON.stringify({params})                       
            })
  .then(response => response.json())
  .then(data => console.log(data))
  .catch(()=>console.log('Wade- you cant access the url response'));
```
***Relevant Julia***
```
using Genie.Router, Genie.Renderer.Json, Genie.Requests, HTTP
using DFRController

Genie.config.run_as_server = true
Genie.config.cors_allowed_origins = ["*"]

route("/random", method="POST") do
  dim=  parse(Int,postpayload(:dim)) 
  num=  parse(Int,postpayload(:num))  
  #dim= haskey(@params, :dim) ? parse(Int,@params(:dim)) : 3 
  #num= haskey(@params, :num) ? parse(Int,@params(:num)) : 5 
  #dim = parse(Int, get(@params, :dim, "1"))
  #num = parse(Int, get(@params, :num, "2"))
  (:random => rand(dim,num)) |> json
end

```

**Expected behavior**
Expect a JSON object to be returned containing an array of random numbers.  Note: a JSON object is returned based on default parameters when they are included.

**Additional context**
Please include the output of 
`julia> versioninfo()`
```
Julia Version 1.5.2
Commit 539f3ce943 (2020-09-23 23:17 UTC)        
Platform Info:
  OS: Windows (x86_64-w64-mingw32)
  CPU: Intel(R) Core(TM) i5-10210U CPU @ 1.60GHz
  WORD_SIZE: 64    
  LIBM: libopenlibm
  LLVM: libLLVM-9.0.1 (ORCJIT, skylake)
Environment:
  JULIA_EDITOR = "C:\Users\FAMU\AppData\Local\Programs\Microsoft VS Code\Code.exe"
  JULIA_NUM_THREADS =
```
and
```
Status `C:\Users\FAMU\Desktop\wade\repos\FisherRaoApp\Project.toml`
  [c43c736e] Genie v1.12.0
  [cd3eb016] HTTP v0.9.3
  [e6f89c97] LoggingExtras v0.4.4
  [739be429] MbedTLS v1.0.3
  [ade2ca70] Dates
  [56ddb016] Logging
```

**Comment by essenciary** [comment]
@wadehenning Strange, I'll take a look, thanks for reporting this.

**Comment by Cyvadra** [comment]
try jsonpayload() with post method

**Comment by wadehenning** [comment]
@Cyvadra  I am using `jsonpayload`.  Am I misusing it?

**Comment by essenciary** [comment]
@wadehenning What @Cyvadra means is the `jsonpayload()` method in `Genie.Requests`. 

![image](https://user-images.githubusercontent.com/11292378/108728268-b4a8c380-7529-11eb-8823-3765534a4f8c.png)

That seems to work ok although I see your point, potentially `postpayload()` should also return the raw string value or something like that, as now it seems like there is no POST payload at all...

**Comment by essenciary** [comment]
@wadehenning Ah sorry, I missed your comment - yes, that looks good.
