### ISSUE TITLE
HTMX / _hyperscript support/plugin

### ISSUE THREAD

**Issue by essenciary** [GenieFramework/Genie.jl#353]
https://hyperscript.org/

**Comment by ProvocaTeach** [comment]
I’m not sure this is needed. HTMX just a frontend JavaScript library; you can make it work with Genie already.

For example, in the default Genie structure, we can rewrite `public/welcome.html` to read:
```html
<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en">
<head>
  <meta charset="utf-8"/>
  <script src="https://unpkg.com/htmx.org@1.7.0" integrity="sha384-EzBXYPt0/T6gxNp0nuPtLkmRpmDBbjg6WmCUZRLXBBwYYmwAUxzlSGej0ARHX0Bo" crossorigin="anonymous" defer></script>
</head>
<body>
  <section hx-get="/hello">
    <p>This content will be replaced by “Hello, world!”</p>
  </section>
</body>
</html>
```
(The [`hx-get` attribute](https://htmx.org/attributes/hx-get/) tells HTMX to send a GET request – in this case, to `/hello` – and replace the `innerHTML` of the `<section/>` with whatever it gets back.)

If we set up the `/hello` endpoint in our `routes.jl`:
```julia
route("/") do
  serve_static_file("welcome.html")
end

route("/hello") do
  html("<p>Hello, world!</p>")
end
```
The homepage, when visited, will replace the original text with “Hello, world!” You can probably already make this work in Genie templates too.
