### ISSUE TITLE
`get` parameters that have spaces encoded as `+` do not seem to be parsed correctly.

### ISSUE THREAD

**Issue by Krastanov** [GenieFramework/Genie.jl#357]
For `localhost:8000?c=a+b` I am expecting to get `@params(:c) == "a b"`, but I am getting "a+b".

As an example where this happens: the form parameter encodes whitespaces as "+" in some `textarea` tags in forms with `method=get`. I can not simply use `replace(..., "+"=>" ")` manually to fix that, because `@params` does not give you the raw `get` parameters.

Python seems to solve that by having both `unquote` and `unquote_plus` in its `urllib.parse` standard library. How do I properly unquote/unescape "+" signs in URI parameters in Genie?

**Comment by essenciary** [comment]
Thanks. How do you get/generate the `localhost:8000?c=a+b` link? Is it the value of an input field "a b" submitted through a form? How is the form encoded?

**Comment by Krastanov** [comment]
Here is a code example
```julia
route("/form") do
  if haskey(@params, :c)
    Logging.@info (@params(:c))
    Logging.@info (typeof(@params(:c)))
    c = @params(:c)
  else
    c = "no form submitted"
  end
  return """
  <pre>
  $(c)
  </pre>
  <form method="get" action="/form" id="form">
  <textarea name="c" form="form">
  some text
  more text
    text with leading whitespace
  </textarea> 
  <input type="submit">
  </form>
  """
end
```

And here is what it does (I do not think the pluses should be there):

![image](https://user-images.githubusercontent.com/705248/114421370-3c529c00-9b83-11eb-9f9f-da429ef41812.png)

**Comment by Krastanov** [comment]
To answer the questions: the default encoding for the form (my understanding is that I do not need to explicitly specify an encoding, but I am not very knowledgeable on this topic and might be wrong), a `get` method, and submission through the form by clicking the submit button (i.e., not some programmatic submission done from CLI or JS).

**Comment by ProvocaTeach** [comment]
Hi, I am new to Genie, but I am also having this problem while just going through the tutorial:
![image](https://user-images.githubusercontent.com/68936059/114788652-b8411580-9d36-11eb-9b85-57475b325ca8.png)

**Comment by essenciary** [comment]
Thanks @Krastanov @ProvocaTeach - I did some research into form encoding, it's pretty messy. I'll look into a fix today.

**Comment by Krastanov** [comment]
This is only partially related, but I was wondering whether there is a way to get the parameters as raw byte arrays? I am used to that from some other frameworks, and it has been helpful when dealing with forms containing weird unicode.

**Comment by essenciary** [comment]
Take a look at the Input module - maybe there is anything useful there or we can extend the API.

**Comment by essenciary** [comment]
Should be fixed on the latest master (Genie v2)
