### ISSUE TITLE
Don't notify me about github actions for issues

### ISSUE THREAD

**Issue by jtrakk** [GenieFramework/Genie.jl#364]
Whenever I open an issue on this repo, it triggers a workflow in GitHub Actions and I get an email about it.

For example https://github.com/GenieFramework/Genie.jl/actions/runs/805679770

**Comment by essenciary** [comment]
No idea why that is - please feel free to review the setup and send a PR for the actions on Genie's repo.

**Comment by essenciary** [comment]
Merged, thanks for the PR!
