### ISSUE TITLE
`KeyError: key :__vars not found' when using `@vars'

### ISSUE THREAD

**Issue by SimonCoste** [GenieFramework/Genie.jl#368]
Hi, in the Genie doc there's a little example on how to use the [Genie.Renderer.Html.html](https://genieframework.github.io/Genie.jl/dev/API/renderer_html.html#Genie.Renderer.Html.html) function :

```julia
html("<h1>Welcome $(@vars(:name))</h1>", 
layout = "<div><% @yield %></div>", 
name = "Adrian")
```

However from this command I get back a 

 ```ERROR: KeyError: key :__vars not found
 Stacktrace: 
 [1] getindex at ./iddict.jl:92 [inlined] 
 [2] task_local_storage(::Symbol) at ./task.jl:204 
 [3] top-level scope at REPL[11]:1
``` 
I guess this has to be a problem with the `@vars` macro ?

https://github.com/GenieFramework/Genie.jl/blob/28506eed85aca99521ff1943ebd1dd67ece36cc0/src/Renderer.jl#L419-L423

**Comment by essenciary** [comment]
Thanks for reporting this - yes, something is off. 

You can call `Genie.Renderer.init_task_local_storage()` manually to initialize it until I release a fix.

**Comment by essenciary** [comment]
Actually I got it wrong. `@vars` (or just `vars` in v2) is meant to be used inside the view files (in the view templates). If you pass it like this, as a string, it gets evaluated eagerly by Julia - while the code is meant to be evaluated at runtime (when a request is made and the HTML is returned). 

To make that work you need: 
1 - to add `using Renderer`
2 - to convert the view to a raw string: `raw"<h1>Welcome $(@vars(:name))</h1>"`

This works: 

```julia
julia> html(raw"<h1>Welcome $(@vars(:name))</h1>",
       layout = "<div><% @yield %></div>",
       name = "Adrian")
HTTP.Messages.Response:
"""
HTTP/1.1 200 OK
Content-Type: text/html; charset=utf-8

<!DOCTYPE html><html><head></head><body><div><h1>Welcome Adrian</h1></div></body></html>"""
```
