### ISSUE TITLE
Better error than 404 for routes.jl 

### ISSUE THREAD

**Issue by jtrakk** [GenieFramework/Genie.jl#370]
When there is an error at the top level of routes.jl, for example referring to a variable that isn't defined, going to a page gives 404. I would like a better error message.

**Comment by essenciary** [comment]
OK, I see it. Yes, good point. Because the routes file is loaded async and this throws an error, it doesn't get to the point of loading the actual routes definitions so it's 404. We should throw some exception into the main thread.

**Comment by essenciary** [comment]
I can't reproduce this - please provide a MWP that I can run.

**Comment by essenciary** [comment]
I will close due to being unable to reproduce - please reopen if you can provide a MWE.
