### ISSUE TITLE
Genie app not working in docker

### ISSUE THREAD

**Issue by victorgarcia98** [GenieFramework/Genie.jl#373]
Hello!!

I'm going through the genie [tutorial](https://genieframework.github.io/Genie.jl/dev/tutorials/16--Using_Genie_With_Docker.html) to set up a web api inside docker but it's not starting. In my local computer it worked just fined but when I launched it with docker it didn't seem to work. I attach you the error stackstrace below:

---

ERROR: LoadError: ArgumentError: invalid base 10 digit 't' in "true"
Stacktrace:
 [1] tryparse_internal(#unused#::Type{Int64}, s::String, startpos::Int64, endpos::Int64, base_::Int64, raise::Bool)
   @ Base ./parse.jl:137
 [2] parse(::Type{Int64}, s::String; base::Nothing)
   @ Base ./parse.jl:241
 [3] parse
   @ ./parse.jl:241 [inlined]
 [4] execute(config::Genie.Configuration.Settings; server::Nothing)
   @ Genie.Commands ~/.julia/packages/Genie/Uvtzb/src/Commands.jl:21
 [5] #run#31
   @ ~/.julia/packages/Genie/Uvtzb/src/Genie.jl:231 [inlined]
 [6] genie(; context::Module)
   @ Genie ~/.julia/packages/Genie/Uvtzb/src/Genie.jl:269
 [7] main()
   @ Starke ~/app/src/Starke.jl:8
 [8] top-level scope
   @ ~/app/bootstrap.jl:4
in expression starting at /home/genie/app/bootstrap.jl:4

---

**Versions**
Computer: Mac M1
Julia: version 1.5.3
Genie: version 1.18.1
Docker: version 20.10.6, build 370c289

**Additional context**
Apart from starting the server using Deploy.Docker.run(), I connected directly to the container and run the ./server script in order to launch the server and It didn't work.

Please, let me know any detail that could be useful to fix this :).

Thank you in advanced.

**Comment by essenciary** [comment]
@victorgarcia98 Looks like a boolean ("true") is passed instead of the port number. What's in the Dockerfile ?

**Comment by victorgarcia98** [comment]
FROM julia:latest

# user
RUN useradd --create-home --shell /bin/bash genie

# app
RUN mkdir /home/genie/app
COPY . /home/genie/app
WORKDIR /home/genie/app

RUN chown genie:genie -R *

RUN chmod +x bin/repl
RUN chmod +x bin/server
RUN chmod +x bin/runtask

USER genie

RUN julia -e "using Pkg; Pkg.activate(\".\"); Pkg.instantiate(); Pkg.precompile(); "

# ports
EXPOSE 8000
EXPOSE 80

# websockets ports
EXPOSE 8000
EXPOSE 80

ENV JULIA_DEPOT_PATH "/home/genie/.julia"
ENV GENIE_ENV "dev"
ENV HOST "0.0.0.0"
ENV PORT "8000"
ENV PORT "true"

CMD ["bin/server"]

**Comment by essenciary** [comment]
The ENV PORT "true" part should not be there - how was this generated?

**Comment by victorgarcia98** [comment]
I checked the [docker file generation](https://github.com/GenieFramework/Genie.jl/blob/master/src/FileTemplates.jl) and it does not seem right (bold):
---
function dockerfile(; user::String = "genie", supervisor::Bool = false, nginx::Bool = false, env::String = "dev",
                      filename::String = "Dockerfile", port::Int = 8000, dockerport::Int = 80, host::String = "0.0.0.0",
                      websockets_port::Int = port, websockets_dockerport::Int = dockerport, earlybind::Bool = true)
  appdir = "/home/$user/app"

  """
  FROM julia:latest

  # user
  RUN useradd --create-home --shell /bin/bash $user

  # app
  RUN mkdir $appdir
  COPY . $appdir
  WORKDIR $appdir

  RUN chown $user:$user -R *

  RUN chmod +x bin/repl
  RUN chmod +x bin/server
  RUN chmod +x bin/runtask

  USER $user

  RUN julia -e "using Pkg; Pkg.activate(\\".\\"); Pkg.instantiate(); Pkg.precompile(); "

  # ports
  EXPOSE $port
  EXPOSE $dockerport

  # websockets ports
  EXPOSE $websockets_port
  EXPOSE $websockets_dockerport

  ENV JULIA_DEPOT_PATH "/home/$user/.julia"
  ENV GENIE_ENV "$env"
  ENV HOST "$host"
  ENV PORT "$port"
  **ENV PORT "$earlybind"**

  CMD ["bin/server"]
  """
end

---

Thank you a lot for your help!!

**Comment by essenciary** [comment]
Thank you - now I need to fix the generator :) Please don't close the issue until I fix that, I'll close it myself.
