### ISSUE TITLE
Export HTTP status code

### ISSUE THREAD

**Issue by mdsa3d** [GenieFramework/Genie.jl#383]
I would like to know, is there any way to export the `HTTP` status code (i.e 200, 404 etc)?

**Comment by essenciary** [comment]
@mdsa3d Can you please be more specific? Export it where / use it how?

**Comment by mdsa3d** [comment]
@essenciary  thanks for the response! I want to collect the response status as a variable. 

For example:
```
HTTP.ExceptionRequest.StatusError(500, "POST", "/check", HTTP.Messages.Response:
"""
HTTP/1.1 500 Internal Server Error
Content-Type: application/json; charset=utf-8
Transfer-Encoding: chunked
```
For the above response, I could collect `resp_status=500` for analyzing the response data later.

**Comment by essenciary** [comment]
@mdsa3d Sorry, I'm afraid I still don't understand. Collect it from where? Aren't you constructing and sending the response?

**Comment by mdsa3d** [comment]
@essenciary sorry for late response! The user cannot see the response from the call, hence i would like to export the response to the user as a string variable, to inform the user about the status. For example, if the response is successful then I want to push a string saying `200` and likewise for different status different variable. And this `200` or `500` is the HTTP response status. I would like to collect this value from the response. Is it possible?
Hopefully, it is clear now.

**Comment by essenciary** [comment]
Something like this? 

```julia
using Genie.Renderer.Json
resp = json( Dict("foo" => "bar") )
@debug resp.status
resp
```

**Comment by mdsa3d** [comment]
@essenciary Thanks, this works perfectly. Highly, appreciate your patience and help on this matter!

**Comment by essenciary** [comment]
@mdsa3d Great! No problem! Did you mean to reopen it?
