### ISSUE TITLE
Unable to use @foreach inside dynamic html tag

### ISSUE THREAD

**Issue by mach512** [GenieFramework/Genie.jl#385]
Hi, 

I have been trying to learn Genie and with dynamic HTML tags I ran into an error. 

<h1>Bill Gates' top $(length(books)) recommended books</h1>
<ul>
  <% @foreach(books) do book %>
    <li>$(book.title) by $(book.author)</li>
  <% end %>
</ul>

I have used the above code but it doesn't display the items inside foreach loop. It returns like this "Welcome to top books
Bill Gates' top 5 recommended books
Task (runnable) @0x000000004a597c70"

Can you kindly help me in this regard? Thank you.

**Comment by essenciary** [comment]
Can you please pass me the output of `pkg> status` and `julia> versioninfo()`?

**Comment by mach512** [comment]
I have tried installing Julia 1.6 but  still the same error. It says "500 Internal Server Error
LoadError: LoadError: UndefVarError: @foreach not defined"

**Comment by essenciary** [comment]
@foreach has been removed in v2 (v2 is a new major version which is breaking and this is one of the changes). Please use `for_each` (function not macro). The docs have been updated but I'll add a v1 to v2 migration guide asap.

**Comment by mach512** [comment]
Hi, Thank you. It worked.

**Comment by essenciary** [comment]
@mach512 Thank you. I have updated the docs.
