### ISSUE TITLE
Add MIME subtype vnd.api+json

### ISSUE THREAD

**Issue by UniqueTokens** [GenieFramework/Genie.jl#387]
First, thanks for the Genie Framework! It feels very familiar and comfortable, especially for a experienced Ruby on Rails developer like me.

I'm considering developing a [JSON:API](https://jsonapi.org/format/) compatible API using the Genie Framework. The endpoint should accept and send the [MIME subtype](https://www.iana.org/assignments/media-types/application/vnd.api+json) **application/vnd.api+json** as the content type. However, the `jsonpayload()` function does not return any data for a POST request that uses this media type.

The media type **application/json** works as expected. I would be very grateful for any suggestions for a solution!

**Comment by essenciary** [comment]
@UniqueTokens Thanks for reporting this. 

What would be the best way to handle this? Should we treat anything that has `+json` as a JSON request?

**Comment by UniqueTokens** [comment]
First guess, add the subtype to `minetypes.jl`? Today `file_headers(f)` defaults to application/octet-stream:
https://github.com/GenieFramework/Genie.jl/blob/54e595767ca7bf6684dbc2d2ba7ca05ddc179ea7/src/Router.jl#L1151

But, in [MIME subtype](https://www.iana.org/assignments/media-types/application/vnd.api+json) the `File extension(s) : .json` is `json` too because is a registered subtype and there is no alternative.
https://github.com/GenieFramework/Genie.jl/blob/54e595767ca7bf6684dbc2d2ba7ca05ddc179ea7/src/mimetypes.jl#L183

Adding `("json", "application/vnd.api+json")` to `mimetypes.jl` is impossible because is a Dict and the key is given.

Maybe we can learn from related issue for RoR:
[Adding custom mime type for 'application/vnd.api+json' seems to be required to receive data from clients using JSON API](https://github.com/rails-api/active_model_serializers/issues/1027#issuecomment-126543577)

**Comment by essenciary** [comment]
@UniqueTokens Thanks - can you please provide a MWE/failing test that I can work off?

**Comment by essenciary** [comment]
A very simple test is to replace 
```julia
julia> Router.mimetypes["json"]
"application/json"
```
and run the request through your app. 

But I'm not convinced the issue is there so I'd need a failing test please, to make sure I'm looking at the right problem.

**Comment by UniqueTokens** [comment]
> can you please provide a MWE/failing test that I can work off?

My approach was to just go through the Genie Tutorial [Using JSON payloads](https://genieframework.github.io/Genie.jl/dev/tutorials/7--Using_JSON_Payloads.html) and replace `application/json` with `application/vnd.api+json` for the HTTP.request. jsonpayload() should get the same Dict in both cases.

The RoR way in https://github.com/GenieFramework/Genie.jl/issues/387#issuecomment-878366127 seems interesting. Maybe that's points to the solution for the OP?

```
julia> Genie.Renderer.CONTENT_TYPES[:json] = "application/vnd.api+json; application/json; charset=utf-8"
"application/vnd.api+json; application/json; charset=utf-8"

julia> Genie.Renderer.CONTENT_TYPES
Dict{Symbol, String} with 9 entries:
  :fontwoff2  => "font/woff2"
  :javascript => "application/javascript; charset=utf-8"
  :xml        => "text/xml; charset=utf-8"
  :markdown   => "text/markdown; charset=utf-8"
  :text       => "text/plain; charset=utf-8"
  :json       => "application/vnd.api+json; application/json; charset=utf-8"
  :css        => "text/css; charset=utf-8"
  :favicon    => "image/x-icon"
  :html       => "text/html; charset=utf-8"
```

```

julia> HTTP.request("POST", "http://localhost:8000/jsonpayload", [("Content-Type", "application/vnd.api+json")], """{"name":"Adrian"}""")
jsonpayload() = nothing
rawpayload() = "{\"name\":\"Adrian\"}"
Error: MethodError: no method matching getindex(::Nothing, ::String)
...
```

**Comment by UniqueTokens** [comment]
Any news on this?

**Comment by AbhimanyuAryan** [comment]
@UniqueTokens if I understand this correctly. You want `JSON parser` to process custom vendor requests as mentioned here: https://jsonapi.org/#mime-types?

What are you trying to achieve? Are you trying to do `mime type versioning` for REST API instead of `url versioning` or `parametric versioning` for different users? 

Let's say this generic example:

```
@RestController
public class PersonController {
    
    @GetMapping(path = "/person", produces = "application/vnd.company.api-v1+json")
    public Person getPersonV1() {
        return new Person("Mr. ABC", "abc@gmail.com");
    }

    @GetMapping(path = "/person", produces = "application/vnd.company.api-v2+json")
    public Person getPersonV2() {
        return new Person("Mr. XYZ", "xyz@gmail.com");
    }
}
```

**Comment by UniqueTokens** [comment]
@AbhimanyuAryan, no kind of controller-based versioning was intended.

*application/vnd.api+json* is a registered MIME Subtype. The MIME Type of a HTTP(S) request is sent from the client as *Content-Type* field in the request header to the server.

Content typed with *application/vnd.api+json* says to the server: "Here comes a fully JSON compatible body with some vendor-specific JSON content in it. Please handle it at any API endpoint in the same way as intended for *application/json* and let the backend do all the vendor specific stuff".

This includes the server potentially responding the client with a JSON body with *application/vnd.api+json* compatible content inside.

**Comment by AbhimanyuAryan** [comment]
Sorry to bother again but you are trying to achieve something like this right: https://github.com/django/django/blob/7119f40c9881666b6f9b5cf7df09ee1d21cc8344/tests/test_client/tests.py#L164         

"/json_view/", {"value": 37}, content_type="application/vnd.api+json"

**Comment by AbhimanyuAryan** [comment]
Cool I am looking into possible implementation. Thanks for reconfirming

**Comment by UniqueTokens** [comment]
Any news on this?

**Comment by AbhimanyuAryan** [comment]
> Any news on this?

Sadly I haven't had a chance to look at it. Also, Adrian is super busy with GenieBuilder and JuliaCon 


I have two priorities right now. I can look at it after finishing them. Sorry that you have to wait so long @UniqueTokens

**Comment by essenciary** [comment]
@UniqueTokens This is now available in the Genie#v5 branch which will be come the new master in a week or so. https://github.com/GenieFramework/Genie.jl/blob/v5/test/tests_json_encodings.jl

The Genie v5 release will be breaking but we'll release a migration guide.

**Comment by UniqueTokens** [comment]
Great!

**Comment by UniqueTokens** [comment]
@essenciary The `extract_request_params` function does not extract the `vnd.api+json` content due to the hard-coded content type `:json`.

https://github.com/GenieFramework/Genie.jl/blob/6268491086c1d73dba0fdd7e5777b131700eff80/src/Router.jl#L804

**Comment by essenciary** [comment]
Can you review the corresponding passing test at the URL above and explain what the issue is with code (ie a failing test)? The current passing test implements your initial example.

**Comment by UniqueTokens** [comment]
`vnd.api+json` payload appears to be correctly identified and accepted by the Router, but cannot be extracted due to the hard-coded content-type `:json`. Adding a test for `extract_request_params` with `:(vnd.api+json)` content should help.

**Comment by UniqueTokens** [comment]
Tested with Genie v5.5.0 and Julia 1.8.1. Works as expected. Thanks for providing the feature!
