### ISSUE TITLE
newresource creates lowercase models file.

### ISSUE THREAD

**Issue by JulioBarros** [GenieFramework/Genie.jl#388]
**Describe the bug**
When running `Genie.newresource("Movie")` on a Mac a models file is created with a lowercase name: `resources/movies/movies.jl`. I believe it should be uppercase `Movies.jl`. I'm not sure about moviesValidator.jl also.

**To reproduce**

Run through the MVC tutorial as written and observe the filenames created.

**Additional context**

Commit 1b93d53fc4 (2021-07-14 15:36 UTC)
Platform Info:
  OS: macOS (x86_64-apple-darwin18.7.0)
  CPU: Intel(R) Core(TM) i9-9980HK CPU @ 2.40GHz
  WORD_SIZE: 64
  LIBM: libopenlibm
  LLVM: libLLVM-11.0.1 (ORCJIT, skylake)
Environment:
  JULIA_REVISE = auto

     Project Watchtonight v0.1.0
      Status `~/projects/Julia/Watchtonight/Project.toml`
  [c43c736e] Genie v2.0.1
  [6d011eab] Inflector v1.0.0
  [e6f89c97] LoggingExtras v0.4.7
  [739be429] MbedTLS v1.0.3
  [340e8cb6] SearchLight v1.0.0
  [21a827c4] SearchLightSQLite v1.0.0
  [ade2ca70] Dates
  [56ddb016] Logging

**Comment by essenciary** [comment]
Looks good for me (Windows): 
![image](https://user-images.githubusercontent.com/11292378/126043125-eda82ae9-efed-41e3-9895-2407cb152796.png)

Is your file system case sensitive?

**Comment by JulioBarros** [comment]
Yes. I believe Mac filesystems  are case sensitive (by default) or at least there are some issues around matching case.

**Comment by essenciary** [comment]
All good on linux as well - tomorrow I'll test on Mac. 

![image](https://user-images.githubusercontent.com/11292378/126049468-761b68c9-7f28-4da7-bc53-df05b3752bc8.png)

**Comment by JulioBarros** [comment]
Sorry, just realized your response was about MoviesController.  My issue is with movies.jl


[ Info: 2021-07-17 15:32:45 New MoviesController.jl created at /Users/julio/projects/Julia/footest/app/resources/movies/MoviesController.jl
[ Info: 2021-07-17 15:32:45 New model created at /Users/julio/projects/Julia/footest/app/resources/movies/movies.jl
[ Info: 2021-07-17 15:32:46 New table migration created at /Users/julio/projects/Julia/footest/db/migrations/2021071722324599_create_table_movies.jl
[ Info: 2021-07-17 15:32:46 New validator created at /Users/julio/projects/Julia/footest/app/resources/movies/moviesValidator.jl
[ Info: 2021-07-17 15:32:46 New unit test created at /Users/julio/projects/Julia/footest/test/movies_test.jl

**Comment by essenciary** [comment]
@JulioBarros Ah, great catch! I fixed it - please make sure you're on the latest SearchLight (1.0.2).
