### ISSUE TITLE
Handling query params do not work for me: MethodError: no method matching haskey(::typeof(params), ::Symbol)

### ISSUE THREAD

**Issue by JulioBarros** [GenieFramework/Genie.jl#392]
I added the code from the documentation to get query parameters and got an exception when accessing the page.

MethodError: no method matching haskey(::typeof(params), ::Symbol)

Though the code from the 'The Requests module` does work:  "Hello $(getpayload(:name, "Anon"))"

I cut an pasted the code from the docs into my current project.  The routes table looks like: 

using Genie, Genie.Router, Genie.Requests

using MoviesController, AdminController

route("/admin/movies", AdminController.index, named=:get_home)
route("/movies/search_api", MoviesController.search_api)
route("/movies/search", MoviesController.search, named = :search_movies)
route("/movies", MoviesController.index)

route("/hi") do
  name = haskey(params, :name) ? params(:name) : "Anon"

  "Hello $name"
end

route("/") do
  "My app"
end

The exception is:

[ Info: 2021-07-17 09:58:13 GET /hi?name=Julio 200
┌ Error: 2021-07-17 09:59:04 MethodError: no method matching haskey(::typeof(params), ::Symbol)
│ Closest candidates are:
│   haskey(!Matched::Union{Tables.AbstractColumns, Tables.AbstractRow}, ::Symbol) at /Users/julio/.julia/packages/Tables/gg6Id/src/Tables.jl:183
│   haskey(!Matched::DataStructures.AVLTree{K}, ::K) where K at /Users/julio/.julia/packages/DataStructures/ixwFs/src/avl_tree.jl:120
│   haskey(!Matched::DataStructures.PriorityQueue, ::Any) at /Users/julio/.julia/packages/DataStructures/ixwFs/src/priorityqueue.jl:117
│   ...
│ Stacktrace:
│   [1] (::Watchtonight.var"#51#52")()
│     @ Watchtonight ~/projects/Julia/Watchtonight/routes.jl:11
│   [2] #invokelatest#2
│     @ ./essentials.jl:708 [inlined]
│   [3] invokelatest
│     @ ./essentials.jl:706 [inlined]
│   [4] match_routes(req::HTTP.Messages.Request, res::HTTP.Messages.Response, params::Genie.Router.Params{Any})
│     @ Genie.Router ~/.julia/packages/Genie/nRyBN/src/Router.jl:476
│   [5] route_request(req::HTTP.Messages.Request, res::HTTP.Messages.Response)
│     @ Genie.Router ~/.julia/packages/Genie/nRyBN/src/Router.jl:155
│   [6] handle_request(req::HTTP.Messages.Request, res::HTTP.Messages.Response)
│     @ Genie.AppServer ~/.julia/packages/Genie/nRyBN/src/AppServer.jl:183
│   [7] #22
│     @ /Users/julia/buildbot/worker/package_macos64/build/usr/share/julia/stdlib/v1.6/Distributed/src/macros.jl:127 [inlined]
│   [8] run_work_thunk(thunk::Genie.AppServer.var"#22#23"{HTTP.Messages.Request, HTTP.Messages.Response}, print_error::Bool)
│     @ Distributed /Users/julia/buildbot/worker/package_macos64/build/usr/share/julia/stdlib/v1.6/Distributed/src/process_messages.jl:63
│   [9] remotecall_fetch(::Function, ::Distributed.LocalProcess; kwargs::Base.Iterators.Pairs{Union{}, Union{}, Tuple{}, NamedTuple{(), Tuple{}}})
│     @ Distributed /Users/julia/buildbot/worker/package_macos64/build/usr/share/julia/stdlib/v1.6/Distributed/src/remotecall.jl:379
│  [10] remotecall_fetch(::Function, ::Distributed.LocalProcess)
│     @ Distributed /Users/julia/buildbot/worker/package_macos64/build/usr/share/julia/stdlib/v1.6/Distributed/src/remotecall.jl:379
│  [11] remotecall_fetch(::Function, ::Int64; kwargs::Base.Iterators.Pairs{Union{}, Union{}, Tuple{}, NamedTuple{(), Tuple{}}})
│     @ Distributed /Users/julia/buildbot/worker/package_macos64/build/usr/share/julia/stdlib/v1.6/Distributed/src/remotecall.jl:421
│  [12] remotecall_fetch(::Function, ::Int64)
│     @ Distributed /Users/julia/buildbot/worker/package_macos64/build/usr/share/julia/stdlib/v1.6/Distributed/src/remotecall.jl:421
│  [13] setup_http_listener(req::HTTP.Messages.Request, res::HTTP.Messages.Response)
│     @ Genie.AppServer ~/.julia/packages/Genie/nRyBN/src/AppServer.jl:210
│  [14] setup_http_listener
│     @ ~/.julia/packages/Genie/nRyBN/src/AppServer.jl:209 [inlined]
│  [15] handle
│     @ ~/.julia/packages/HTTP/4AvE2/src/Handlers.jl:254 [inlined]
│  [16] handle(::HTTP.Handlers.RequestHandlerFunction{typeof(Genie.AppServer.setup_http_listener)}, ::HTTP.Streams.Stream{HTTP.Messages.Request, HTTP.ConnectionPool.Transaction{Sockets.TCPSocket}})
│     @ HTTP.Handlers ~/.julia/packages/HTTP/4AvE2/src/Handlers.jl:277
│  [17] setup_http_streamer(http::HTTP.Streams.Stream{HTTP.Messages.Request, HTTP.ConnectionPool.Transaction{Sockets.TCPSocket}})
│     @ Genie.AppServer ~/.julia/packages/Genie/nRyBN/src/AppServer.jl:199
│  [18] (::Genie.AppServer.var"#6#13"{Int64})(http::HTTP.Streams.Stream{HTTP.Messages.Request, HTTP.ConnectionPool.Transaction{Sockets.TCPSocket}})
│     @ Genie.AppServer ~/.julia/packages/Genie/nRyBN/src/AppServer.jl:90
│  [19] macro expansion
│     @ ~/.julia/packages/HTTP/4AvE2/src/Servers.jl:413 [inlined]
│  [20] (::HTTP.Servers.var"#13#14"{Genie.AppServer.var"#6#13"{Int64}, HTTP.ConnectionPool.Transaction{Sockets.TCPSocket}, HTTP.Servers.Server{Nothing, Sockets.TCPServer}, HTTP.Streams.Stream{HTTP.Messages.Request, HTTP.ConnectionPool.Transaction{Sockets.TCPSocket}}})()
│     @ HTTP.Servers ./task.jl:411
│ 
└ @ Genie.AppServer ~/.julia/packages/Genie/nRyBN/src/AppServer.jl:222

**Comment by essenciary** [comment]
Looks like the guide has some compatibility issues with Genie v2. In this case it should be `params()` not `params`.

**Comment by essenciary** [comment]
The recommended approach in v2 for that code is: 

```julia
name = params(:name, "Anon")
```

I have updated the docs and will be live at the next release.

**Comment by essenciary** [comment]
Closing - please reopen is the proposed code still does not work.
