### ISSUE TITLE
Using module from /lib in initializer

### ISSUE THREAD

**Issue by stonepreston** [GenieFramework/Genie.jl#395]
It looks like its not possible to use a module defined in /lib in an initializer. Does the LOAD_PATH get modifed after the intitializers are run? after the call to bin/repl finishes and before I run up() I can call using MyModule and it works fine, but the intializers get run before that. 

Ive got some code I need to run once and only once on server startup, but its in a module defined in /lib. I also reference this lib elsewhere in the application so its not feasible to just move it into the initializer file itself. Is there any sort of work around for this? I could move it into a bonafide package and install that into my env but the amount of code doesnt really warrant that

**Comment by essenciary** [comment]
@stonepreston It's a chicken and egg type of situation and has to do with the load order. Something needs to be loaded before the other, and in this case, initializers are loaded before /lib. Which I think it makes sense as /lib contains user defined logic and modules, while initializers contain lower level configuration and resources (db connections, app wide settings, etc) to be used in user code. 

Just don't wait for Genie to load the /lib - do it yourself in the initializer. Either directly include the file in /lib or push /lib to LOAD_PATH.

**Comment by stonepreston** [comment]
alright I got it working just including the file in the initializer. Thank you!
