### ISSUE TITLE
Loading custom module in jl.html

### ISSUE THREAD

**Issue by ChenZhao44** [GenieFramework/Genie.jl#398]
**Is your feature request related to a problem? Please describe.**
In the jl.html, I want to display
```
<% baz(bar) %>
```
Here `bar` is a object of type `Bar` defined in `resources/foo/Foo.jl`.
And `baz` is function also defined in `resources/foo/Foo.jl`.

The file `resources/foo/Foo.jl` is like
```julia
module Foo

struct Bar
    ...
end

function baz(bar::Bar)
    ...
end

end
```

It seems that the html.jl file will not load this module.

**Comment by essenciary** [comment]
How do you render the `html.jl` view file? 

Most likely you need to pass `Foo` as the `context` variable/module. 

Something like: 
`html(:foo, "html.jl"; context = Foo)` 

If you call the above in `Foo` you can just pass `context = @__MODULE__`

**Comment by ChenZhao44** [comment]
@essenciary Thanks for your help. 
I'm using `html(:foo, "...")` in `FooController.jl`.
If I use `context = Foo`, there will be the following error
```
LoadError: LoadError: UndefVarError: @yield not defined
```

But if I use `context = @__MODULE__`, and add `using Foo` in the `FooController`,  I can access `Foo.baz` in the `jl.html` file.

**Comment by essenciary** [comment]
Perfect yes, that's the way to go
