### ISSUE TITLE
Genie.Toolbox.tasks fails due to undefined ROOT_PATH

### ISSUE THREAD

**Issue by jarlela** [GenieFramework/Genie.jl#401]
I am unable to run `Genie.Toolbox.tasks` to list registered tasks. It fail with an error complaining about undefined variable `ROOT_PATH`. This can be traced back to `src/Toolbox.jl:33` which is `f = readdir(joinpath(Main.UserApp.ROOT_PATH, Genie.config.path_tasks))`. The `ROOT_PATH` variable is not present in the `UserApp` module.

The source files were generated by calling: `Genie.newapp_mvc` and later `Genie.newtask`. 

Genie version: #master commit '1980b48'

**Comment by AbhimanyuAryan** [comment]
quick fix 

```
pkg> dev Genie
shell> code ~/.julia/dev/Genie
```
edit this line 

https://github.com/GenieFramework/Genie.jl/blob/5e2337724118009165040f0b833cc70b6d22840f/src/Toolbox.jl#L33

to 

```
f = readdir(joinpath(pwd(), Genie.config.path_tasks))
```

will create pull request after review

**Comment by AbhimanyuAryan** [comment]
`pwd()` is of course a hack which would cause problems when the user is not in `root` of project and should not be added to Genie's codebase as fix. But should work for you meanwhile I find a permanent fix

**Comment by AbhimanyuAryan** [comment]
@jarlela it's fixed. I'm closing the issue feel free to re-open another issue if you see any other new problems with toolbox
