### ISSUE TITLE
running local module code within route

### ISSUE THREAD

**Issue by RoyCCWang** [GenieFramework/Genie.jl#403]
I'm modifying the file upload Genie tutorial [here](https://genieframework.github.io/Genie.jl/dev/tutorials/8--Handling_File_Uploads.html). I ran into an issue that ```route``` does not recognise a local submodule that was loaded.

**Setup:** I have a project called ```MyModule```, i.e., the ```MyModule``` module is defined in ```./src/MyModule.jl```. For convinence of testing without formally packaging up ```MyModule``` into a package, I tend to use ```import .MyModule``` in my verification scripts in the ```./examples``` folder. 

Here are the contents of the script I have problems with, located in the ```./examples``` folder:
```
using Genie, Genie.Router, Genie.Renderer.Html, Genie.Requests
import InfoZIP, Dates

import .MyModule

form = """
<form action="/" method="POST" enctype="multipart/form-data">
  <input type="file" name="exp_file" /><br/>
  <input type="submit" value="Submit" />
</form>

"""

route("/") do
  html(form)
end

route("/", method = POST) do
  if infilespayload(:exp_file)
    write(filespayload(:exp_file))
    f_name = filename(filespayload(:exp_file))
 
    # process unzipped folder with custom code.
    MyModule.myfunc(f_name)

    "Done"

  else
    "No file uploaded"
  end
end

up()
```

**Issue:** I get a ```Error: UndefVarError: MyModule not defined``` error after I upload a file.

The following works:
```
test_tag = 1
f_name = "my_file.txt"

if test_tag == 1
    MyModule.myfunc(f_name)
end 
```

**Current workaround:** I made ```MyModule``` into a Julia package, installed it, then I use ```import MyModule``` instead of ```import .MyModule``` to proceed without errors.

**Request for help:** I was wondering if there is a solution to allow me to use  ```import .MyModule``` or use code in my project without having to include all the files of my project in a full-blown Genie app, which was suggested [here](https://genieframework.github.io/Genie.jl/dev/tutorials/9--Publishing_Your_Julia_Code_Online_With_Genie_Apps.html)?

**Comment by essenciary** [comment]
Closing for lack of feedback.
