### ISSUE TITLE
Asking  function for obtaining remote (client side) ip, and web-browser information.

### ISSUE THREAD

**Issue by Shum88** [GenieFramework/Genie.jl#425]
Asking  function for obtaining remote (client side) ip, and web-browser information.

**Comment by essenciary** [comment]
Thanks - I found it but I'm not sure if it's fully implemented/work correctly. Can you please try and lmk if it returns the correct IP? 

So:
* it's disabled by default (to skip the computation if not needed)
* you must enable it by setting `features_peerinfo = true` in the `Genie.config` object
* then use `Genie.Requests.peer()` to get the info within the route handler

This test should serve as an example: 
https://github.com/GenieFramework/Genie.jl/blob/master/test/tests_peer_info.jl

**Comment by essenciary** [comment]
Can you please detail what are you getting (and what are you expecting)?

**Comment by essenciary** [comment]
Closing for lack of feedback. Please reopen if you have more info.
