### ISSUE TITLE
Optional skipping of using sudo for Docker on Linux

### ISSUE THREAD

**Issue by UniqueTokens** [GenieFramework/Genie.jl#426]
For automated tests, it would be nice if the use of sudo for Docker on Linux could be skipped (because the current user may a member of the docker group). Perhaps as a named parameter for `Genie.Deploy.Docker.build(; sudo=false)` and `Genie.Deploy.Docker.run(; sudo=false)` with the default value `true`?

**Comment by AbhimanyuAryan** [comment]
> For automated tests, it would be nice if the use of sudo for Docker on Linux could be skipped (because the current user may a member of the docker group). Perhaps as a named parameter for `Genie.Deploy.Docker.build(; sudo=false)` and `Genie.Deploy.Docker.run(; sudo=false)` with the default value `true`?

Noted 👍

**Comment by essenciary** [comment]
@UniqueTokens This is now available in v4.4.0 - please try and let me know if it works as expected.

**Comment by UniqueTokens** [comment]
`Deploy.Docker.build` not working in Genie v4.4.1. DOCKER function is returning a `Cmd` type instead of the `String` type.

https://github.com/GenieFramework/Genie.jl/blob/f6ff591384f372f102e5f3d691db3ab398bef8a8/src/Deploy.jl#L21

```julia
julia> using Genie
# output omitted
julia> Genie.newapp("DockerTest")
# output omitted
julia> using Genie.Deploy
# output omitted
julia> Deploy.Docker.dockerfile()
# output omitted
julia> Deploy.Docker.build()
┌ Error: 2021-12-02 08:33:11 Can not find sudo docker. Please make sure that sudo docker is installed and accessible.
└ @ Genie.Deploy ~/.julia/packages/Genie/MQlbP/src/Deploy.jl:9
ERROR: IOError: could not spawn `'sudo docker' build --no-cache -t genie .`: no such file or directory (ENOENT)
# output omitted
```
Maybe this will fix the bug
```julia
DOCKER(; sudo::Bool = Sys.islinux()) = sudo ? "sudo docker" : "docker"
```

**Comment by essenciary** [comment]
Hmmm.... I don't have a Linux with me, but on macOS (the non sudo version) worked fine...

**Comment by essenciary** [comment]
Oh, need more coffee - I can just pass the sudo argument to force it on macOS too :)

**Comment by essenciary** [comment]
Should be fixed in v4.4.2

**Comment by UniqueTokens** [comment]
Primary issue seems be fixed in v4.4.2. But now `Deploy.Docker.run()` is broken:

```julia
julia> Deploy.Docker.run()
ERROR: UndefVarError: System not defined
Stacktrace:
 [1] run()
   @ Genie.Deploy.Docker ~/.julia/packages/Genie/U7ZwI/src/Deploy.jl:92
 [2] top-level scope
   @ REPL[7]:1
```
`System.islinux()` should be `Sys.islinux()`

https://github.com/GenieFramework/Genie.jl/blob/0ab1f8dc3caf40057b63cc8acc781f70902b5c70/src/Deploy.jl#L91

BTW, how about automated unit tests before the next version is released? ;-)

**Comment by essenciary** [comment]
Damn! 
We have some 350 unit tests hooked in CI. If you know how to unit test the docker integration (with CI support) please add them, happy to merge them.

**Comment by essenciary** [comment]
OK - tagged v4.4.3 - hopefully this is the last of the fixes.

**Comment by UniqueTokens** [comment]
v4.4.3 tested with `sudo = false`. Works as expected. Thank you very much!

**Comment by essenciary** [comment]
🥳
