### ISSUE TITLE
Is a global dictionary threadsafe in Genie?

### ISSUE THREAD

**Issue by BrettRToomey** [GenieFramework/Genie.jl#429]
If I have a global dictionary, is it safe to insert values or do I need some sort of synchronisation primitive? As far as I can tell, Julia's tasks run on a single thread using a form of cooperative multitasking, meaning that I shouldn't require a primitive, but I want to be sure that I am correct here.

Thanks!

**Comment by essenciary** [comment]
That's correct

**Comment by BrettRToomey** [comment]
Cool! Thanks!
