### ISSUE TITLE
Integration with new Interact family?

### ISSUE THREAD

**Issue by datnamer** [GenieFramework/Genie.jl#43]
One of the things which excite me most about Julia is solving the web  two language problem. This won't go away completely until compilation to WASM is improved, but there are really meaningful steps in the new Interact work  by @piever: https://discourse.julialang.org/t/ann-interactbase-a-redesign-of-interact-to-create-and-style-web-apps-in-julia/11471/2 

Have you thought about integration with Genie? Doing both UI and backend in julia would be a real advantage over say Django for data scientist types and amateur webdevs.

**Comment by piever** [comment]
On the technical side, Interact* is based on WebIO to actually render and serve the widgets, so the integration would have to be Genie / WebIO (the only library Interact* uses is knockoutjs to sync observables to widget values). To render WebIO nodes in the browser, normally one can use Mux.jl, which has support defined [here](https://github.com/JuliaGizmos/WebIO.jl/blob/master/src/providers/mux.jl).

Genie seems to provide features that Mux does not provide so I imagine it could make sense to add Genie integration to WebIO.

**Comment by essenciary** [comment]
Yes, I've been thinking about the idea. And I've also had something similar in mind for many months now. I'm working on something similar, but I'm not sure I'd go this way (with WebIO and Julia Gizmos). My focus at the moment is on building something very similar to Ploty's Dash. I have most of the pieces lined up in Genie's MVC stack already.

**Comment by essenciary** [comment]
> Are there any specific concerns with respect to WebIO?
Not at all, I just have a different vision, that's all. 

I want to wrap web components into Julia modules and provide a protocol for communication over websockets. Thus I'm thinking Polymer 2, probably with a dash of React on the front. This plays nicely with Genie's narrative (the existing MVC stack and assets [JS, CSS, HTML] management strategy via Webpack). 

The downside is that it won't display widgets inside IDEs -- but my focus is on building data dashboards which run in their own web pages and can be hosted. 

Other than that, I'd be more than happy to have Genie working with the UI system you're building. Looking at the Mux integration file it looks like what's needed is a web server with web sockets support and routing -- in which case Genie would be overkill. However, if we could use Genie's compiled view templates, or caching, or advanced routing, that'd be useful.  What kind of use case do you have in mind?

**Comment by datnamer** [comment]
As a web naive end user, the overhead would be significantly lower for me if the web packages coalesced around common components as proposed here by @piever. 

Unless there are significant technical or philosophical challenges, I  see only benefits from the maintenance, code reuse  and community/ innovation perspectives if interact/webio et al is used.

**Comment by essenciary** [comment]
@piever Thanks for the details, I'll take a look. Just as heads up, there's also been a lot of progress with HTTP.jl -- which provides the web server, web sockets integration and a few auth schemes. Dataset upload should be straightforward. 

"Some way to prevent the app from making major damage on the server" can be quite tricky, I thought about it myself. I'm thinking something heavily inspired by JuliaBox. 

@datnamer Sure, that makes sense. Can't comment more -- I'll have to dig into WebIO as I'm not familiar with the codebase.

**Comment by essenciary** [comment]
Yes, it's tricky, but Polymer and web components have come a long way. Polymer is now at v3 and there is much better support for web components. 

It's not that I'm a fan of it -- but Predix-UI looks like a low hanging fruit: a large collection of powerful UI elements, distributed under permissive licensing and with an architecture which lends itself to backend integration with the current Genie stack.  

My latest thoughts are to set up a custom integration for web components (Predix) and Twitter Bootstrap (for layouts) and separately support Interact.jl (which seems straightforward). 

At a more philosophical level, it's good that multiple options emerge. It's a sign of a growing, healthy ecosystem which will benefit both users and developers. However it does feel like a lot of duplication - and that some of the lessons of the past are lost and the same mistakes are being made all over again. We seem to be stuck in a cycle and it's not very clear where each framework is going and when will it get there.
