### ISSUE TITLE
Set headers for JSON view

### ISSUE THREAD

**Issue by tpoisot** [GenieFramework/Genie.jl#440]
**Is your feature request related to a problem? Please describe.**
I'm trying to write a RESTful API with pagination, and for this reason I'd like to put the number of elements in the headers

**Describe the solution you'd like**
Not sure - something in the route, maybe?

**Describe alternatives you've considered**
I might also add a metadata block to the response but it seems less elegant

**Comment by essenciary** [comment]
I suggest trying one of the `Responses.setheaders` methods: 

```julia
function setheaders(header::Pair{String,String}) :: HTTP.Response
  setheaders(Dict(header))
end
```

Let me know if that works. If not, it might need a bit of tweaking ;-)

**Comment by tpoisot** [comment]
So, where should I be putting this? I'm a little unclear still about the "flow" of what should be a function, the result of a function, or a response.

**Comment by essenciary** [comment]
You should put it in the same place where you get the info about the data you're sending as JSON. Something like:

```julia
using Genie.Responses

data = get_the_data()
setheaders("X-Number-Of-Elements" => size_of_data(data))
json(data)
```

**Comment by tpoisot** [comment]
Oh I see! So headers are in the... scope of the function returning the response?

I'll try with this before calling the JSON renderer and let you know.

**Comment by tpoisot** [comment]
OK that works - I dropped it in a function in the controller class:

~~~julia
function list()
  datasets = all(MgDataset)
  Genie.Responses.setheaders("X-Number-Of-Elements" => string(length(datasets)))
  json(:mgdatasets, :all, datasets = datasets)
end
~~~

**Comment by essenciary** [comment]
> Oh I see! So headers are in the... scope of the function returning the response?

Yes and know - the Genie code executes in the context of a HTTP.jl thread where the handler function receives a request and returns a response. The response object is available throughout the lifetime of the code's execution and can be manipulated, for instance by adding more headers manually. ;-)

**Comment by tpoisot** [comment]
That broke my brain a little, but in a good way.
