### ISSUE TITLE
Running app on JuliaHub

### ISSUE THREAD

**Issue by jeremiedb** [GenieFramework/Genie.jl#450]
I'd like to be able to launch a Genie app directly as an app on JuliaHub. 
Requirement for a JuliaApp is to have a `bin/main.jl` entrypoint script. 

However, when trying to launch such app, there appear to be issues related to the path environments. 
For example, the `pwd()` points to  `/home/jrun` and `@__DIR__` to `/home/jrun/.julia/packages/GenieExperiments/QlQOS/bin`. 
It results in a Genie app that is launched, but where the setup environment appears to be ignored (Genie launched in DEV, although GENIE_ENV is to prod, and port is 127.0.0.1 instead of 0.0.0.0 as set in the conf.

The same behavior was observed is setting the working directory to `__DIR__` in the `main.jl` script: `cd(@__DIR__)`.

These test can be seen reproduced with this [repo](https://github.com/jeremiedb/GenieExperiments.jl/tree/test-dir).

Is there extra step can needs to be done within Genie to be able to launch properly the app, or is it more related to how the JuliaHub env is setup?

**Comment by essenciary** [comment]
Hey @jeremiedb - thanks for raising this. No probs, I'm sure we can fix it - however, I'm thinking if maybe it makes sense to have a `Genie.Deploy` API for JuliaHub (like we have for Heroku for example). Can you please explain what's the "official"/standard deployment procedure on JuliaHub (is there a JuliaHub API already, do you connect GitHub, etc)? 

Happy to have a quick call if easier to communicate.

**Comment by jeremiedb** [comment]
Hi @essenciary. Regarding the standard deployment procedure, it is quite lightweight and comes down pretty to having a Julia package that includes a `bin/main.jl` script in the root path as described [here](https://help.juliahub.com/run/applications/). 
Given those lightweight requirements, I'd assume that a dedicated deployment API wouldn't be needed.

**Comment by essenciary** [comment]
Thanks @jeremiedb - we could have a small generator to create the `bin/main.jl` file. What should the file do? Load the app and start the web server in the production environment?

**Comment by jeremiedb** [comment]
From my understanding, that's effectively all that should be done. My issue so far, is that such `main.jl` seems not to result in a proper starting of the app (I had essentially copied the `bootstrap.jl` code). I suspect it's a matter on environment configuration (GENIE_ENV showing as prod but Genie starting in DEV mode), but I'm not sure whether the root issue is related to something to fix in the `main.jl` or with the JuliaHub startup settings per se. Anything I could look at to clarify this?

**Comment by essenciary** [comment]
Let me run some quick tests on JuliaHub and follow up.

**Comment by essenciary** [comment]
@jeremiedb 
1/ I've added some new features to support this, just released Genie v4.5 will be necessary
2/ I have a demo app here: https://github.com/GenieFramework/whats-your-number 
3/ running `julia --project -- bin/main.jl` works perfectly for me
4/ however on JuliaHub it still fails
5/ unfortunately I can't see any logs and I don't know what command does JuliaHub execute. 

Can you please find out re #5?

**Comment by essenciary** [comment]
@jeremiedb Found the logs which present this exception - but I don't know what to do about it: 

```julia
File: /opt/juliahub/master_startup.jl:298
Timestamp: 8 Dec 2021, 20:10-1638990604616
Worker: jr-xutybap2rz-hjf2t, id: 1
Thread: 1
Module: Main.JuliaRunJob
Level: Error
Group: master_startup
Exception:
MethodError: no method matching joinpath(::Nothing, ::String)
Closest candidates are:
  joinpath(!Matched::AbstractString, ::AbstractString...) at path.jl:296
  joinpath(!Matched::URIs.URI, ::String...) at /home/jrun/.julia/packages/URIs/o9DQG/src/URIs.jl:509
Stacktrace:
  [1] install_packages(; code_script::String, mode::String, juliarun_run_mode::String)
    @ Main.JuliaRunJob /opt/juliahub/common_startup.jl:255
  [2] (::Main.JuliaRunJob.var"#23#28"{String, String})()
    @ Main.JuliaRunJob /opt/juliahub/master_startup.jl:277
  [3] macro expansion
    @ ~/.julia/packages/Logging2/5fG3t/src/Logging2.jl:24 [inlined]
  [4] macro expansion
    @ ./task.jl:387 [inlined]
  [5] redirect_stderr(f::Main.JuliaRunJob.var"#23#28"{String, String}, logger::LoggingExtras.EarlyFilteredLogger{JuliaRunLoggers.JuliaRunLogger, CloudWatchLogging.var"#40#42"{Float64, Base.CoreLogging.LogLevel, CloudWatchLogging.TokenBucket}}; level::Base.CoreLogging.LogLevel)
    @ Logging2 ~/.julia/packages/Logging2/5fG3t/src/Logging2.jl:21
  [6] redirect_stderr
    @ ~/.julia/packages/Logging2/5fG3t/src/Logging2.jl:16 [inlined]
  [7] #22
    @ /opt/juliahub/master_startup.jl:256 [inlined]
  [8] macro expansion
    @ ~/.julia/packages/Logging2/5fG3t/src/Logging2.jl:24 [inlined]
  [9] macro expansion
    @ ./task.jl:387 [inlined]
 [10] redirect_stdout(f::Main.JuliaRunJob.var"#22#27"{String, String, LoggingExtras.EarlyFilteredLogger{JuliaRunLoggers.JuliaRunLogger, CloudWatchLogging.var"#40#42"{Float64, Base.CoreLogging.LogLevel, CloudWatchLogging.TokenBucket}}}, logger::LoggingExtras.EarlyFilteredLogger{JuliaRunLoggers.JuliaRunLogger, CloudWatchLogging.var"#40#42"{Float64, Base.CoreLogging.LogLevel, CloudWatchLogging.TokenBucket}}; level::Base.CoreLogging.LogLevel)
    @ Logging2 ~/.julia/packages/Logging2/5fG3t/src/Logging2.jl:21
 [11] redirect_stdout
    @ ~/.julia/packages/Logging2/5fG3t/src/Logging2.jl:16 [inlined]
 [12] (::Main.JuliaRunJob.var"#21#26"{String, String, LoggingExtras.EarlyFilteredLogger{JuliaRunLoggers.JuliaRunLogger, CloudWatchLogging.var"#40#42"{Float64, Base.CoreLogging.LogLevel, CloudWatchLogging.TokenBucket}}})()
    @ Main.JuliaRunJob /opt/juliahub/master_startup.jl:255
 [13] with_logstate(f::Function, logstate::Any)
    @ Base.CoreLogging ./logging.jl:491
 [14] macro expansion
    @ ~/.julia/packages/CloudWatchLogging/Ixju9/src/logger.jl:228 [inlined]
 [15] macro expansion
    @ ./task.jl:387 [inlined]
 [16] with_logger(f::Function, logger::CloudWatchLogging.CloudWatchLogger, logstate::Base.CoreLogging.LogState; nretries::Int64, reset_error_count_secs::Int64, kwargs::Base.Iterators.Pairs{Union{}, Union{}, Tuple{}, NamedTuple{(), Tuple{}}})
    @ CloudWatchLogging ~/.julia/packages/CloudWatchLogging/Ixju9/src/logger.jl:218
 [17] with_logger
    @ ~/.julia/packages/CloudWatchLogging/Ixju9/src/logger.jl:211 [inlined]
 [18] with_logger(f::Function, logger::LoggingExtras.TransformerLogger{CloudWatchLogging.CloudWatchLogger, JuliaRunLoggers.var"#2#4"{Dict{Symbol, Any}, Dict{Symbol, Function}}}, logstate::Base.CoreLogging.LogState)
    @ JuliaRunLoggers ~/.julia/packages/JuliaRunLoggers/ymXlf/src/JuliaRunLoggers.jl:52
 [19] with_logger(f::Function, logger::JuliaRunLoggers.JuliaRunLogger, logstate::Base.CoreLogging.LogState)
    @ JuliaRunLoggers ~/.julia/packages/JuliaRunLoggers/ymXlf/src/JuliaRunLoggers.jl:93
 [20] #with_logger#6
    @ ~/.julia/packages/JuliaRunLoggers/ymXlf/src/JuliaRunLoggers.jl:51 [inlined]
 [21] with_logger(f::Function, logger::LoggingExtras.EarlyFilteredLogger{JuliaRunLoggers.JuliaRunLogger, CloudWatchLogging.var"#40#42"{Float64, Base.CoreLogging.LogLevel, CloudWatchLogging.TokenBucket}})
    @ JuliaRunLoggers ~/.julia/packages/JuliaRunLoggers/ymXlf/src/JuliaRunLoggers.jl:51
 [22] main()
    @ Main.JuliaRunJob /opt/juliahub/master_startup.jl:254
 [23] top-level scope
    @ /opt/juliahub/master_startup.jl:315
 [24] include(mod::Module, _path::String)
    @ Base ./Base.jl:386
 [25] exec_options(opts::Base.JLOptions)
    @ Base ./client.jl:285
 [26] _start()
    @ Base ./client.jl:485
```

**Comment by essenciary** [comment]
I see that you provide the Manifest.toml in the Github repo - is that expected?

**Comment by essenciary** [comment]
@jeremiedb looks like a JuliaHub error, please see the Slack thread here: https://julialang.slack.com/archives/C01FHUY9X96/p1638990836023000

**Comment by jeremiedb** [comment]
Thanks Adrian for looking into this! I'll follow up on this JuliaHub launching script.

**Comment by essenciary** [comment]
Thanks Jeremie - I'll also keep chasing for a fix in JuliaHub (or at least a workaround). But if you can also chase this on your side to get it fixed faster, that'd be awesome.

**Comment by jeremiedb** [comment]
Hi @essenciary, I gave another shot to the app and still got the `HOST` error. 
Could you give another try to https://github.com/jeremiedb/WhatsYourNumber on JuliaHub and see whether you reproduce that error message (key HOST not found and Genie app spinning up in DEV rather than PROD)?

**Comment by essenciary** [comment]
Hi @jeremiedb - but the apps don't run due to the bug in JuliaHub: https://discourse.julialang.org/t/issues-running-genie-apps-on-juliahub/72809/3

**Comment by jeremiedb** [comment]
@essenciary Regarding the above issue, I think the bug is limited to a situation where the julia peoject/package name doesn't match that of the app git repo.  
So if you launch an app on JuliaHub with  https://github.com/jeremiedb/WhatsYourNumber, you shouldn't get the `MethodError: no method matching joinpath(::Nothing, ::String)` error. 

What I was curious to get your insight on was the error message that is thrown with `WhatsYourNumber`. The thing that really puzzles me is that the environment variable such as GENIE_ENV seems to be ignored when the Genie app is launched, even though they are hard coded in `bain/main.jl`. For example, if I add a @info ENV["GENIE_ENV"] at the beginning of `bin/main.jl`, it will print "prod" as expected, yet the Genie App will be launched with `Active Env: DEV`, rather than PROD as it would be the case when GENIE_ENV is set to prod. 
When launching locally, with a Julia REPL, `; cd bin`, then `include("main.jl"), it does launch in PROD mode. 

There's also an open issue internally with JuliaHub, looking into what may be causing this.

**Comment by jeremiedb** [comment]
It seems that by using the following in `bootstrap.jl` got the app to launch properly: 
```
(pwd() != @__DIR__) && cd(@__DIR__) # allow starting app from bin/ dir
```
As brought by https://github.com/jeremiedb/WhatsYourNumber/commit/4aedb07eded998c289679b752065d8e01b97e18b
Would that remains compatible with the other means for app launching?

**Comment by essenciary** [comment]
@jeremiedb The change in bootstrap should be compatible with the original intent, thank you for the contribution! I'll release a new version to use it.

**Comment by essenciary** [comment]
@jeremiedb Can we close this, looks like there are no more issues. Anything still breaking on your side? As an extra, I'm thinking about adding a "Hosting on JuliaHub" section to the Genie docs.

**Comment by jeremiedb** [comment]
@essenciary Closing. I'll be adding a "launch Genie app" tutorial in the JuliaHub tutorial section (something like the Iris dashboard on plotly).

**Comment by essenciary** [comment]
@jeremiedb Fabulous, thank you! 

Can you also please add to that the fact that running `Genie.Deploy.JuliaHub.mainjl()` will create the `main.jl` file inside the `bin/` dir of the app?
