### ISSUE TITLE
Minor bootstrap improvements

### ISSUE THREAD

**Issue by attdona** [GenieFramework/Genie.jl#455]
I find a little bit difficult to start a genie server with repl. At first I tried:

    > julia bootstrap.jl si

but it does not work as expected, it just start the server like `julia bootstrap.jl s` or any other argument value `julia bootstrap.jl xyz`.

I've worked out a patch that add interactivity using the `-i` julia command line flag and start the server with a `-s` flag.

    app_root> julia bootstrap.il -s # start the server
    app_root> julia -i bootstrap.jl -s # start the server and open a repl

    app_root> bin/server # start the server
    app_root> bin/repl    # start the server and open a repl (no need for up() invocation)

If you are positive about that I may eventually create a PR.

**Comment by tecosaur** [comment]
Is there something wrong with `bin/repl` ?

**Comment by attdona** [comment]
There is nothing wrong with `bin/repl`.

As said this patch could be (in my option) a minor improvement with the
effect on `bin/repl`  of get rid of  calling `up()` to start the server.

I think the only  "problem" is that `si` [bootstrap argument](https://github.com/GenieFramework/Genie.jl/blob/master/src/Commands.jl#L74) does not work.

**Comment by essenciary** [comment]
@attdona oh yes, the `si` support has been removed a while ago, looks like we forgot to remove the argument from the list of accepted arguments. 

We like to keep things as simple as possible and in this case, if you want to start the repl and automatically start the server, just add `up()` in your app's files and that will start the server. 

Like here (last line): https://github.com/GenieFramework/StippleDemos/blob/master/AdvanceExamples/MultiUserApp.jl

**Comment by essenciary** [comment]
I have removed the `si` option from the list or arguments as well, will show up in the next release, thanks for flagging this.
