### ISSUE TITLE
Access violation error in Julia

### ISSUE THREAD

**Issue by eisthfroyalblue** [GenieFramework/Genie.jl#507]
**Describe the bug**
Julia crashes when run `repl.bat` or `loadapp()`

**Error stacktrace**
debugger is looking for a file `/buildbot/worker/package_win64/build/src/jitlayers.cpp`
with the following message:
`Unhandled exception 0x000000000100CC8D(libjulia-internal.dll) (julia.exe). access violation at 0xC0000005: 0x0000000009682008`

**To reproduce**
1. `using Genie`
2. `Genie.newapp("MyTestApp")` or `Genie.newapp_webservice("MyTestApp")`
   Most of time, this step passes. But sometimes it fails even at this point.
3. Exit julia and come back to `MyTestApp` folder
4. Run `repl.bat` or `loadapp()`
  Most of time, this step fails. I have to repeat for 10 to 20 times until the service is up and running by good luck.

**Expected behavior**
Active env: DEV

Ready! 

┌ Info: 2022-03-29 13:47:03 
└ Web Server starting at http://127.0.0.1:8000

**Additional context**
For Windows PC #1
```
julia> versioninfo()
Julia Version 1.7.2
Commit bf53498635 (2022-02-06 15:21 UTC)
Platform Info:
  OS: Windows (x86_64-w64-mingw32)
  CPU: Intel(R) Core(TM) i7-9850H CPU @ 2.60GHz
  WORD_SIZE: 64
  LIBM: libopenlibm
  LLVM: libLLVM-12.0.1 (ORCJIT, skylake)
Environment:
  JULIA_DEPOT_PATH = E:\.julia
  JULIA_EDITOR = "C:\Users\sijun.cho\AppData\Local\atom\app-1.60.0\atom.exe"  -a
  JULIA_NUM_THREADS = 6
  JULIA_REVISE = auto
  JULIA_SSL_CA_ROOTS_PATH =
```
```

(@v1.7) pkg> st
      Status `E:\.julia\environments\v1.7\Project.toml`
  [c52e3926] Atom v0.12.36
  [6e4b80f9] BenchmarkTools v1.3.1
  [336ed68f] CSV v0.10.2
  [8be319e6] Chain v0.4.10
  [534720e6] CompositeStructs v0.1.2
  [a93c6f00] DataFrames v1.3.2
  [864edb3b] DataStructures v0.18.11
  [31c24e10] Distributions v0.25.49
  [e30172f5] Documenter v0.26.3
  [35a29f4d] DocumenterTools v0.1.13
  [7876af07] Example v0.5.4 `E:\.julia\dev\Example`
  [38e38edf] GLM v1.6.1
  [c43c736e] Genie v4.17.0
  [0e44f5e4] Hwloc v2.0.0
  [e5e0dc1b] Juno v0.8.4
  [06ab140a] MyAwesomePackage v0.1.0 `E:\.julia\dev\MyAwesomePackage`
  [d92e12fc] NPFinancial v0.3.2 `https://github.com/tk3369/NPFinancial.jl#master`
  [5fb14364] OhMyREPL v0.5.12
  [d96e819e] Parameters v0.12.3
  [14b8a8f1] PkgTemplates v0.7.26
  [91a5bcdd] Plots v1.25.11
  [49802e3a] ProgressBars v1.4.1
  [92933f4c] ProgressMeter v1.7.1
  [295af30f] Revise v3.3.2
  [01f1e0e4] SmallTest v0.1.0 `E:\.julia\dev\SmallTest`
  [09ab397b] StructArrays v0.6.5

```

For Windows PC #2 
```
julia> versioninfo()
Julia Version 1.7.2
Commit bf53498635 (2022-02-06 15:21 UTC)
Platform Info:
  OS: Windows (x86_64-w64-mingw32)
  CPU: Intel(R) Core(TM) i7-6700K CPU @ 4.00GHz
  WORD_SIZE: 64
  LIBM: libopenlibm
  LLVM: libLLVM-12.0.1 (ORCJIT, skylake)
Environment:
  JULIA_DEPOT_PATH = D:\.julia
  JULIA_EDITOR = "C:\Users\Earth\AppData\Local\atom\app-1.60.0\atom.exe"  -a
  JULIA_NUM_THREADS = 4
```

```
(@v1.7) pkg> st
      Status D:\.julia\environments\v1.7\Project.toml
  [c52e3926] Atom v0.12.36
  [a93c6f00] DataFrames v1.3.2
  [c43c736e] Genie v4.17.0
  [e5e0dc1b] Juno v0.8.4
  [5fb14364] OhMyREPL v0.5.12
  [14b8a8f1] PkgTemplates v0.7.26
  [91a5bcdd] Plots v1.27.2
  [295af30f] Revise v3.3.3
```

**Comment by essenciary** [comment]
@eisthfroyalblue Thanks for reporting this though not sure we can do anything about it. Julia segfaults are Julia issues. Do other things work for you? For instance a couple of years ago I reported a windows issue where I couldn't use Julia while having Julia installed on one drive and the app on another (like in your case).

**Comment by eisthf** [comment]
@essenciary 
_I couldn't use Julia while having Julia installed on one drive and the app on another (like in your case)._
: Actually I tried both cases. On one PC, Julia and Genie app are on the same drive. On the other PC, they are located on different drives.

I observed the error did not occur on Linux and macOS. So it seems that the error is somehow related only to Windows.

Today I tried Julia v1.8.0-beta1 on Windows PC. The Julia error are gone. But `Base.modules_warned_for` does not exist anymore in the newer version of Julia. So I had to remove it from `bootstrap.jl`. But when I removed it, then files in `\lib\` folder are not recognized as packages anymore. In order to workaround, I tried adding `path/to/lib`  to `LOAD_PATH` but strangely `router.jl` fail to load with the following error message:

```
Loading routesERROR: ArgumentError: Package TestApp does not have Logic in its dependencies:
- You may have a partially installed environment. Try `Pkg.instantiate()`
  to ensure all packages in the environment are installed.
- Or, if you have TestApp checked out for development and have
  added Logic as a dependency but haven't updated your primary
  environment's manifest file, try `Pkg.resolve()`.
- Otherwise you may need to report an issue with TestApp
Stacktrace:
```

**Comment by eisthf** [comment]
Anyway, I can work around the problem by doing this way:

1) Enclose the routes.jl in a module and put the content inside a function (say `init()`)
2) `inlude("lib/Logic.jl")`
```
module Routes
using Genie.Router

include("lib/Logic.jl") # include your additional module
using .Logic

function init()
    # register routes, etc
end
end # end of module
```
3) In `MyGenieApp` module, `include("../routes.jl")` and call `Routes.init()` defined above:
```
module MyGenieApp

using Genie, Logging, LoggingExtras
include("../routes.jl") # include routes.jl file

function main()
  Core.eval(Main, :(const UserApp = $(@__MODULE__)))

  Genie.genie(; context = @__MODULE__)

  Core.eval(Main, :(const Genie = UserApp.Genie))
  Core.eval(Main, :(using Genie))

  Routes.init() # call this to register routes, etc.
end

end

Revise now picks up changes in real time!


```

**Comment by ShoofLLC** [comment]
> Anyway, I can work around the problem by doing this way:
> 
>     1. Enclose the routes.jl in a module and put the content inside a function (say `init()`)
> 
>     2. `inlude("lib/Logic.jl")`
> 
> 
> ```
> module Routes
> using Genie.Router
> 
> include("lib/Logic.jl") # include your additional module
> using .Logic
> 
> function init()
>     # register routes, etc
> end
> end # end of module
> ```
> 
>     3. In `MyGenieApp` module, `include("../routes.jl")` and call `Routes.init()` defined above:
> 
> 
> ```
> module MyGenieApp
> 
> using Genie, Logging, LoggingExtras
> include("../routes.jl") # include routes.jl file
> 
> function main()
>   Core.eval(Main, :(const UserApp = $(@__MODULE__)))
> 
>   Genie.genie(; context = @__MODULE__)
> 
>   Core.eval(Main, :(const Genie = UserApp.Genie))
>   Core.eval(Main, :(using Genie))
> 
>   Routes.init() # call this to register routes, etc.
> end
> 
> end
> 
> Revise now picks up changes in real time!
> ```

Just for documentations, to anyone reading this: Make sure to call the Routes.init() function first, otherwise _routes will not be visible to the app.
