### ISSUE TITLE
Receive multi-files from post request.

### ISSUE THREAD

**Issue by deahhh** [GenieFramework/Genie.jl#538]
As describes in [document](https://docs.juliahub.com/Genie/8eazC/4.18.1/tutorials/8--Handling_File_Uploads.html),
What if the html is changed as follow:
```julia
form = """
<form action="/" method="POST" enctype="multipart/form-data">
  <input type="file" name="yourfile" multiple /><br/>
  <input type="submit" value="Submit" />
</form>
"""
```

**Comment by iskyd** [comment]
@deahhh  the filespayload(key) function return an Input.HttpFile so it seems there is no way to get multiple files for the same key (as in your example).

@essenciary could be this a feature request? What do you think?

**Comment by AbhimanyuAryan** [comment]
@iskyd if this is the same issue: https://github.com/GenieFramework/Genie.jl/issues/544 please let me know otherwise. You can open a new feature request

**Comment by deahhh** [comment]
Thanks for you!
Genie is great works.
