### ISSUE TITLE
cant start app on Windows

### ISSUE THREAD

**Issue by honghuzi** [GenieFramework/Genie.jl#542]
**Describe the bug**
can't run Genie app on windows, the julia program just exit after starting the app.
```cmd
D:\lab\julia\MultiRoute\bin>repl

D:\lab\julia\MultiRoute\bin>"julia" --color=yes --depwarn=no --project=@. -q -i -- "D:\lab\julia\MultiRoute\bin\..\bootstrap.jl"

 _____         _
|   __|___ ___|_|___
|  |  | -_|   | | -_|
|_____|___|_|_|_|___|

| Web: https://genieframework.com
| GitHub: https://github.com/genieframework/Genie.jl
| Docs: https://www.genieframework.com/docs
| Discord: https://discord.com/invite/9zyZbD6J7H
| Twitter: https://twitter.com/GenieMVC

Active env: DEV

Loading initializers
D:\lab\julia\MultiRoute\bin>
```
- `julia> versioninfo()`
Julia Version 1.7.3
Commit 742b9abb4d (2022-05-06 12:58 UTC)
Platform Info:
  OS: Windows (x86_64-w64-mingw32)
  CPU: 11th Gen Intel(R) Core(TM) i9-11900K @ 3.50GHz
  WORD_SIZE: 64
  LIBM: libopenlibm
  LLVM: libLLVM-12.0.1 (ORCJIT, icelake-client)
Environment:
  JULIA_NUM_THREADS = 12
  JULIA_PKG_SERVER = https://pkg.julialang.org
- Genie version: v4.18.1

**Comment by essenciary** [comment]
What was the problem?

**Comment by honghuzi** [comment]
The issue occured when i tested [this demo](https://github.com/AbhimanyuAryan/MultiRoute). 
- The repl script just quit itself after "Loading initializers"

However, It worked fine if I tested [the official demos](https://github.com/GenieFramework/StippleDemos). 
I can't find the problem myself.
