### ISSUE TITLE
Question about bin/repl arguments to Julia

### ISSUE THREAD

**Issue by Amval** [GenieFramework/Genie.jl#543]
Hello,

one of the things I find more interesting about the `Genie` project is the developer ergonomics, in particular code autoloading. I have adapted it to one of my projects where it makes sense having a `/lib` folder with modules that  get shared between other modules in the package but do not warrant their own package. (The project is a framework with an equivalent concept to Genie's controllers).

This is the `bin/repl` generated by Genie for a Unix project:
```sh
#!/bin/sh
julia --color=yes --depwarn=no --project=@. -q -L $(dirname $0)/../bootstrap.jl -- "$@"
```
Unfortunately, this has the problem that when executing code in VS Code (`ctrl +  enter`), it gets sent to another Julia terminal. Is there a workaround for this?

I have tried to overcome it by modifying the `settings.json` in the project workspace, making it equivalent to this:
```json
{
  "julia.additionalArgs": [
    "--color=yes",
    "--depwarn=no",
    "--project=@.",
    "-q",
    "-L $(dirname $0)/../bootstrap.jl"
  ]
}
```

The *problem*:
- I cannot add the last argument `-- "$@"` to the list of arguments, and without it, it quite does not work as it should (enabling `using` of my `lib` modules).
- I have tried bot "-- $@" and  "-- \"$@\"".
- REPL fails to open with an `ERROR: Unknown Option -- $@".

So the *question* is:
- what does `-- $@` actually do? I understand it as `-- <entry_file>`, so I guess the confusing part is `$@` specifically.
- and there are any obivous solutions that I am missing?

**Comment by Amval** [comment]
On the second point about the problem the rendering changed what I wrote. I meant:
> "-- $@" and "-- $\"$@\""

**Comment by essenciary** [comment]
For loading the app in VSCode in the same terminal don't use the script, use, at the terminal: 

```
$ julia --project

julia> using Genie; Genie.loadapp()
```
