### ISSUE TITLE
MVC Tutorial Error

### ISSUE THREAD

**Issue by jackn11** [GenieFramework/Genie.jl#555]
I was going through the MVC tutorial found here https://genieframework.github.io/Genie.jl/dev/tutorials/4-1--Developing_MVC_Web_Apps.html and I notced that the line ```using WatchTonight.Movies``` caused an error for me until I restarted the genie server. However, in the docs it does not tell you to restart the genie server.

An instruction should be added to the tutorial at that point to restart the genie server so that the tutorial works properly.

**Comment by AbhimanyuAryan** [comment]
Thanks for reporting. I'll need to check it. Sounds like a revising issue

**Comment by jglee1** [comment]
The following worked for me.

using Movies

Note:  https://github.com/GenieFramework/Genie.jl/pull/579

**Comment by ruizhi92** [comment]
> I was going through the MVC tutorial found here https://genieframework.github.io/Genie.jl/dev/tutorials/4-1--Developing_MVC_Web_Apps.html and I notced that the line `using WatchTonight.Movies` caused an error for me until I restarted the genie server. However, in the docs it does not tell you to restart the genie server.
> 
> An instruction should be added to the tutorial at that point to restart the genie server so that the tutorial works properly.

Solve my problem. Thank you for sharing
