### ISSUE TITLE
blocks missing from no code editor

### ISSUE THREAD

**Issue by johntom** [GenieFramework/Genie.jl#556]
Im following the https://www.youtube.com/watch?v=Vu6q9tsegDA&ab_channel=Genie video and both julia 1.7.3 and 1.8.0-rc3 do not have a BLOCKS section used in tutoial

**Expected behavior**
I expect to see the same options shown in video

**Additional context**
Please include the output of 
`julia> versioninfo()`
 versioninfo()
Julia Version 1.8.0-rc3
Commit 33f19bcbd2 (2022-07-13 19:10 UTC)
Platform Info:
  OS: Windows (x86_64-w64-mingw32)
  CPU: 8 × Intel(R) Core(TM) i7-9700 CPU @ 3.00GHz
  WORD_SIZE: 64
  LIBM: libopenlibm
  LLVM: libLLVM-13.0.1 (ORCJIT, skylake)
  Threads: 1 on 8 virtual cores
pkg> st
Status `C:\Users\19177\.julia\environments\v1.8\Project.toml` (empty project)

for 1.7.3
Julia Version 1.7.3
Commit 742b9abb4d (2022-05-06 12:58 UTC)
Platform Info:
  OS: Windows (x86_64-w64-mingw32)
  CPU: Intel(R) Core(TM) i7-9700 CPU @ 3.00GHz
  WORD_SIZE: 64
  LIBM: libopenlibm
  LLVM: libLLVM-12.0.1 (ORCJIT, skylake)

 pkg> st
      Status `C:\Users\19177\.julia\environments\v1.7\Project.toml`
  [7876af07] Example v0.5.3
  [587475ba] Flux v0.13.4
  [c43c736e] Genie v5.1.0
  [340e8cb6] SearchLight v2.4.1

**Comment by essenciary** [comment]
They have been put in differently named groups but they should all be there. Any UI component that is specifically missing?

**Comment by essenciary** [comment]
Per additional feedback, we're missing the "Title + Content" block. We'll add it back.

**Comment by johntom** [comment]
Hi,
Not a big deal, just getting introduced to the product and following the
tutorial as it was not matching Blocks Title+content.
I worked around it and moved on. However, I think a github repo of Oscars
Explorer  would be a great asset,
Thanks
John

**Comment by AbhimanyuAryan** [comment]
@johntom https://github.com/GenieFramework/OscarsExplorer
