### ISSUE TITLE
examples of dealing with postpayloads, jsonpayload and rawpayload in docs

### ISSUE THREAD

**Issue by onoke123** [GenieFramework/Genie.jl#557]
There are 3 methods in Genie for receiving post data, postpayloads(), jsonpayload() and rawpayload().
I wonder if there were some examples code in docs of them. 

for example
     ・postpayload()
               post data:  name1=value1
               on Genie:   v = postpayload( :name1 )        <- 'v' is expected 'value1'

**Comment by AbhimanyuAryan** [comment]
thanks, I'll more about payloads in post payload docs. During next iteration(probably next week I'll be working on docs)

**Comment by essenciary** [comment]
Working on improving the API docs overall -- closing this.
