### ISSUE TITLE
HTTPS Section Says HTTP In First Paragraph

### ISSUE THREAD

**Issue by jackn11** [GenieFramework/Genie.jl#564]
https://genieframework.github.io/Genie.jl/dev/tutorials/92--Deploying_Genie_Server_Apps_with_Nginx.html#Enable-HTTPS

Says ```To enable HTTP``` when it should say HTTPS

**Comment by jackn11** [comment]
https://genieframework.github.io/Genie.jl/dev/tutorials/92--Deploying_Genie_Server_Apps_with_Nginx.html#Enable-HTTPS

Another typo in the last paragraph. ```Note that this steps``` should be ```Note that this step```

**Comment by essenciary** [comment]
@jackn11 Thanks - if you have a few minutes maybe you submit a PR on these please?

**Comment by iskyd** [comment]
@essenciary this issue can be closed.
