### ISSUE TITLE
Two different routes for 2 different servers

### ISSUE THREAD

**Issue by ravirathore** [GenieFramework/Genie.jl#572]
Hi,

Suppose a single code file contains 2 different http servers and two routes definitions. How can we map specific routes functions to specific servers. Was not able to locate this in docs.
Please advise.

Example code is:-

route("/hello") do
    "First Server !"
end

route("/hello") do
    "Second Server !"
end

up(8888, async=true)
up(8889, async=true)

Thanks,

**Comment by AbhimanyuAryan** [comment]
but why don't create two file/scripts. What are you trying to achieve with this configuration?

**Comment by ravirathore** [comment]
@AbhimanyuAryan 

Hi,

Just wanted to know if its possible - when both servers want to share/access same variables. 

Thanks,

**Comment by AbhimanyuAryan** [comment]
closing for lack of response. Feel free to reopen if you further queries
