### ISSUE TITLE
output redirection didn't work well for Genie apps

### ISSUE THREAD

**Issue by honghuzi** [GenieFramework/Genie.jl#574]
I started a Genie app on my linux server, everything worked fine except that the output redirection didn't work for it.
I used nohup to keep the Genie app running on the backend by using
```bash
nohup bin/server >logs/raw_logs.txt 2>&1 &
```
However, the raw_logs.txt only showed this messages after I played with the app for two days
```julia
nohup: ignoring input
WARNING: both HttpCommon and Genie export "Headers"; uses of it in module Html must be qualified
WARNING: both Html and Base export "div"; uses of it in module Stipple must be qualified
WARNING: both Html and Base export "mark"; uses of it in module Stipple must be qualified
WARNING: both Html and Base export "summary"; uses of it in module Stipple must be qualified
WARNING: both Html and Base export "time"; uses of it in module Stipple must be qualified
WARNING: both Html and Base export "view"; uses of it in module Stipple must be qualified
```
There are many `logging` and `print` code within my code, to which I expected be written to the raw_logs.txt file

**Comment by essenciary** [comment]
Does plain Julia logging work as expected? Depending on the configuration (and by default), Genie apps log to the Julia repl. 
However, you can set up the Genie logger to send the output to file or both. This also rotates the logs so they don't get too large (one log file per day). Finally, you can also control the amount/verbosity of the logging by setting the logging level.
