### ISSUE TITLE
Embedd latex code via MathJax

### ISSUE THREAD

**Issue by Diirkk** [GenieFramework/Genie.jl#575]
**Describe the bug**
I have tried to use 'MathJax' by integrating dependencies manually and calling them in the app.jl.html file (see image attached). I have changed in-line markers for mathematical formula to a custom combination (e.g. "??") as Genie does not seem to like "$". Formatting text is recognized by MathJax as latex code, however, latex commands (e.g. "3 \times 4") are not compiled properly. For other commands (e.g. "\frac{3}{4}") I get "Math Input error". To me, it seems there is some interference between latex commands and the genie compiler (specifically with "\").

**Error stacktrace**
Math input error

**To reproduce**
I have added this code to the html header section (app.jl.html file) and then used the custom inline command "??" to mark latex code. Also, note that "tex-chtml.jl" needs to be added (available from MathJax repertoire). 

    <script id="MathJax-script" src="/es5/tex-chtml.js" async>
    </script>

    <script>
      MathJax = {
        tex: {
          inlineMath: [['??', '??']],
          packages: ['base','require']
        },
          svg: {
          fontCache: 'global'
          }
        };
      </script>

**Expected behavior**
Code inside the 'inlineMath' deliminaters to be formatted as latex code to display mathematical content nicely.

**Comment by essenciary** [comment]
If it works in plain html files it should also work in Genie views. 

It's not that Genie doesn't like `$`, it's that `$` is a special character in Julia that signals embedded strings and it's treated like that in Genie too. The best approach (both from a Genie/Julia integration perspective but also as a general best practice) is to move your JS into dedicated JS files (they get compiled, cached, etc) so they are not parsed with Julia/Genie.

**Comment by dumyat** [comment]
Here is a minimum example: https://github.com/dumyat/Latex-Minimum-example.git

The output is the following: 
![latex](https://user-images.githubusercontent.com/112545979/189879539-d1a6930d-5a84-41b0-95e7-76137120e769.PNG)

Backslashes seem to be removed. 

Thanks,
D

**Comment by dumyat** [comment]
I have found a solution: The problem was indeed about backslashes. They seem to be removed/altered when rendering the page. If I use double backslash inside the TeX delimiters, formulas are rendered correctly.

**Comment by essenciary** [comment]
Thanks for the update @dumyat, glad that it worked. I'll reopen this maybe somebody has time to come up with a better solution.
