### ISSUE TITLE
Question UndefVarError: secret_token! not defined

### ISSUE THREAD

**Issue by jjd35** [GenieFramework/Genie.jl#586]
Disclaimer, I'm a bit new to genie/julia... and I've been running with Genie doing tutorials in my julia REPL for a while and its been working fine. I don't know what changed but now instead of just typing in the REPL:

`julia> loadapp()`

I have to type in 

`julia> Genie.loadapp()`

But it gives me a bunch of errors when I load it saying the secret_token! is not defined. Does anyone know what causes this?

**Comment by essenciary** [comment]
What is the error?

**Comment by jjd35** [comment]
It just says:

UndefVarError: secret_token! not defined

**Comment by jjd35** [comment]
Still not sure what this means exactly, but my environment just got in a weird state. I ended up restarting since it was just going through the tutorial. Still might be useful to know what causes the secret token to be undefined. Didn't find any information on it

**Comment by essenciary** [comment]
In order to investigate we need 2 things: 
1/ the full error message you're getting 
2/ a way to reproduce the issue you have experienced
