### ISSUE TITLE
Missing Sockets import in Loader 

### ISSUE THREAD

**Issue by cirocavani** [GenieFramework/Genie.jl#589]
**Describe the bug**

`Genie.Loader` uses `Sockets` when `EARLYBIND` env is set to true but this module is not imported. The docker file generated by GenieDeployDocker has `EARLYBIND=true` that results in `UndefVarError`.

https://github.com/GenieFramework/Genie.jl/blob/v5.10.0/src/Loader.jl#L41

Following <https://genieframework.com/docs/genie/v5.4/tutorials/Using-Genie-With-Docker.html>.

**Error stacktrace**

```
[ Info: Binding to host 0.0.0.0 and port 8080 
┌ Error: UndefVarError(:Sockets)
└ @ Genie.Loader ~/.julia/packages/Genie/3ARuQ/src/Loader.jl:43
┌ Warning: Failed binding! 
└ @ Genie.Loader ~/.julia/packages/Genie/3ARuQ/src/Loader.jl:45
```

**To reproduce**

How I saw the error:

```julia
GenieDeployDocker.dockerfile()
GenieDeployDocker.build()
GenieDeployDocker.run()
```

(the docker file has `EARLYBIND=true`)
 
**Expected behavior**

I suppose it is just an `import Sockets` missing. This error does not prevent the server to bind later (with Sockets in other part of the code).

**Additional context**

From `docker run --rm -it -p 80:8080 --name genieapp genie bin/repl`

`versioninfo`

```text
Julia Version 1.6.7
Commit 3b76b25b64 (2022-07-19 15:11 UTC)
Platform Info:
  OS: Linux (x86_64-pc-linux-gnu)
  CPU: unknown
  WORD_SIZE: 64
  LIBM: libopenlibm
  LLVM: libLLVM-11.0.1 (ORCJIT, k8-sse3)
Environment:
  JULIA_PATH = /usr/local/julia
  JULIA_DEPOT_PATH = /home/genie/.julia
  JULIA_VERSION = 1.6.7
  JULIA_GPG = 3673DF529D9049477F76B37566E3C7DC03D6E495
  JULIA_REVISE = auto
```

`pkg st`

```text
     Project DockerTest v0.1.0
      Status `~/app/Project.toml`
  [c43c736e] Genie v5.10.0
  [a082159f] GenieDeployDocker v1.0.1
  [6d011eab] Inflector v1.0.1
  [ade2ca70] Dates
  [56ddb016] Logging
```

**Comment by essenciary** [comment]
@cirocavani Great catch, thanks for reporting this with all the needed details. Currently tagging v5.10.1 which should fix it.

**Comment by cirocavani** [comment]
It's working! Thank you.

<img width="920" alt="image" src="https://user-images.githubusercontent.com/1027756/196950348-4bd04474-3af1-4c3f-9f3c-87594a496b22.png">
