### ISSUE TITLE
The Table of Content of tutorial page is sorting by alphabet

### ISSUE THREAD

**Issue by tudoanh** [GenieFramework/Genie.jl#591]
**Describe the bug**
As you can see here, very confusing for beginner.

![](https://user-images.githubusercontent.com/11133329/197572596-369eaf06-bce9-431e-82bd-eb555e6f88c2.png)

**Comment by AbhimanyuAryan** [comment]
Thanks for reporting this is because list is dynamically created instead of manually writing <li>s like previously. I will add some rule to fix it

**Comment by AbhimanyuAryan** [comment]
ok this is fixed. Please check and report if any other issues. Thanks for reporting :) 

![Uploading asdfasdfasdfasdf.png…]()

**Comment by AbhimanyuAryan** [comment]
Ok this is fixed. Closing it for now. Please report for any other issues. Thanks for reporting 🙂

<img width="463" alt="asdfasdfasdf" src="https://user-images.githubusercontent.com/8083613/207912655-668bf605-bfa8-4245-b3b6-1df06f8f71b4.png">
