### ISSUE TITLE
Memory leak?

### ISSUE THREAD

**Issue by tecosaur** [GenieFramework/Genie.jl#594]
**Describe the bug**
In the past week of the EmacsSurvey being live, the server has OOM'd twice now.

**Error stacktrace**

From the service log:

```
Oct 29 04:14:58 emacssurvey server[59388]: Killed
Oct 29 04:14:58 emacssurvey systemd[1]: genie-app.service: Main process exited, code=exited, status=137/n/a
Oct 29 04:14:58 emacssurvey systemd[1]: genie-app.service: Failed with result 'exit-code'.
```

From the journal:

```
Oct 29 04:14:58 emacssurvey kernel: oom-kill:constraint=CONSTRAINT_NONE,nodemask=(null),cpuset=/,mems_allowed=0,global_oom,task_memcg=/system.slice/genie-app.service,task=julia,pid=59390,uid=997
Oct 29 04:14:58 emacssurvey kernel: Out of memory: Killed process 59390 (julia) total-vm:2485336kB, anon-rss:1808960kB, file-rss:0kB, shmem-rss:0kB, UID:997 pgtables:4320kB oom_score_adj:0
Oct 29 04:14:58 emacssurvey server[59388]: Killed
```

**To reproduce**

Run the EmacsSurvey and accumulate responses.

**Additional context**

```
julia> versioninfo()
Julia Version 1.8.2
Commit 36034abf260 (2022-09-29 15:21 UTC)
Platform Info:
  OS: Linux (x86_64-linux-gnu)
  CPU: 2 × AMD EPYC Processor
  WORD_SIZE: 64
  LIBM: libopenlibm
  LLVM: libLLVM-13.0.1 (ORCJIT, znver2)
  Threads: 1 on 2 virtual cores
```

```
(EmacsSurvey) pkg> st
Project EmacsSurvey v0.1.0
Status `/opt/emacs-survey/Project.toml`
  [336ed68f] CSV v0.10.4
⌃ [a93c6f00] DataFrames v1.3.6
⌃ [c43c736e] Genie v5.6.2
⌃ [cd3eb016] HTTP v1.4.0
  [6d011eab] Inflector v1.0.1
  [033835bb] JLD2 v0.4.25
  [0f8b85d8] JSON3 v1.10.0
  [0aa819cd] SQLite v1.4.2
⌃ [340e8cb6] SearchLight v2.7.1
  [21a827c4] SearchLightSQLite v2.2.0
  [2913bbd2] StatsBase v0.33.21
  [2a0f44e3] Base64
  [ade2ca70] Dates
  [56ddb016] Logging
  [9a3f8284] Random
```

**Comment by AbhimanyuAryan** [comment]
thanks for reporting this issue @tecosaur

**Comment by essenciary** [comment]
@tecosaur I don't know what do say, there's not enough data. We've had applications running for months with load completely flat. May be an issue in Genie, may be an issue in your code. Is the app's codebase public? Is the load correlated to traffic? Can you pull other info and logs from the server? 

Also, on a related by different topic, what kind of setup do you have? As a best practice, you should make sure that the app automatically restarts so that crashes are not an issue.

**Comment by tecosaur** [comment]
> I don't know what do say, there's not enough data

I know :sweat_smile: I wish I had more to share.

> We've had applications running for months with load completely flat

That's useful to hear.

> may be an issue in your code

I do wonder that too. I have a cache that can grow but I can't imagine it growing to the size that triggers an OOM. The entire database being cached is currently at 50MB.

> Is the app's codebase public?

It is: https://git.tecosaur.net/tec/emacs-survey

> Is the load correlated to traffic?

I'm not currently sure, but I suspect it may be.

> Can you pull other info and logs from the server?

I can. I had a look at the logs though and all I saw was 404s for automatically requested resources (e.g. apple touch icon).

> Also, on a related by different topic, what kind of setup do you have? As a best practice, you should make sure that the app automatically restarts so that crashes are not an issue.

This is just a systemd service running on a simple Debian VM, the entire setup is documented here: https://git.tecosaur.net/tec/emacs-survey-server/src/branch/master/setup.org

I see I forgot to add `Restart=on-failure` to the service. I'll change that soon.

**Comment by essenciary** [comment]
@tecosaur Potentially related https://discourse.julialang.org/t/how-to-make-it-be-a-memory-leak-program-without-lower-function-such-as-gc-xxx-used/89347 FYI @hhaensel
