### ISSUE TITLE
Enable customization of behavior in respect to connection loss

### ISSUE THREAD

**Issue by jochenkrattenmacher** [GenieFramework/Genie.jl#599]
Hello!

**Is your feature request related to a problem? Please describe.**
My SPA frequently needs longer than 10 seconds to load. In this respect, the stuff which the displayAlert() function (in channels.js) does is a little annoying (false positive alerts).

**Describe the solution you'd like**
It would be great if I could set the behavior in the settings, i.e., whether an alert should be shown at all, and/or SERVER_GONE_ALERT_TIMEOUT (which currently is 10 sec)

hope I didn't miss anything. If there's something I can do, please let me know

thanks!

**Comment by essenciary** [comment]
Yes, makes sense. The alert can be hidden by putting a ridiculously large number, to keep it simple. 

However, from what you say, there might be a bug... The alert should show after a successful websocket connection, upon socket disconnect. From what you say it sounds like it shows without having connected first...?

**Comment by jochenkrattenmacher** [comment]
Ah well this bug actually seems to be solved in the latest version of Stipple/Genie. Forgot to update, sorry!

**Comment by jochenkrattenmacher** [comment]
sorry I am reopening this because actually that bug wasn't really fixed, it just eluded me because it seems on that particular day my machine was just in unusually good shape... So yeah, the banner still appears sometimes upon clicking a link which leads to a large SPA (when loading it for the first time). In any case, it would also be nice to be able to customize the behavior, but yeah I don't necessarily need it since I can just modify channels.js

**Comment by essenciary** [comment]
Starting with Genie v5.12 you can use `Genie.config.webchannels_server_gone_alert_timeout` to set up a custom value.
