### ISSUE TITLE
Genie 5.15.0 precompiliation never finishes on `master` (macOS ARM)

### ISSUE THREAD

**Issue by George9000** [GenieFramework/Genie.jl#621]
Genie precompile never finishes starting at [`b029fbf`](https://github.com/JuliaLang/julia/commit/b029fbfe8a24a3cc381b2adbfaf2520a3e43cca4) on Julia `master`. Reported on Julia issues and thought to be a Genie bug. See [`#48463`](https://github.com/JuliaLang/julia/issues/48463) and linked [`#48371`](https://github.com/JuliaLang/julia/issues/48371) in Julia issues.

**Comment by essenciary** [comment]
Thank you!
