### ISSUE TITLE
Escaping Julia code delimiters in html views

### ISSUE THREAD

**Issue by PGimenez** [GenieFramework/Genie.jl#624]
From [Discord](https://discord.com/channels/774897545717219328/774897545717219331/1071840601085055041)
Is there an escape character for `$()` or `<% %>`  in Views? It doesn’t seem possible to write something like
```
<body>
  <% @yield %>
</body>
```
since Genie tries to parse it. Same for `$(...)` substitution.

**Comment by essenciary** [comment]
@PGimenez I need to test, but how about: 

a) the `$` should be escaped as `\$` as it's a valid Julia escape sequence. I remember an issue with this was that the code was parsed multiple times, so actually `$` would have to be `\\\$` (though I think we fixed this, I don't remember). Anyway, can you try it and let me know? 

b) for `<%` and `%>` how about replacing the `<` and `>` with the corresponding HTML chars (`&lt;` and `&gt;`)?

**Comment by essenciary** [comment]
Closing - please reopen if these proposals don't work.
