### ISSUE TITLE
Genie stores path information to locally rendered views.

### ISSUE THREAD

**Issue by lazzarello** [GenieFramework/Genie.jl#635]
I built a docker image of a Genie app in my CI system. The build succeeded but when I view the HTML for / I get an exception that the path to the rendered view is missing in the container. This is correct, since `*/build` is included in a .gitignore file written by the webapp generator. The Genie documentation implies this view will be re-rendered on the first request if the build/ directory is missing but it seems like this is not the case.

When I view / the docker container throws a File Not Found error with a path to a view in `$APPROOT/build/GenieViews/<checksum>.jl` which references `$APPROOT/app/resources/orbits/views/orbitscontroller.jl.html`

The checksum matches the path of the rendered template on my local computer. This implies Genie is storing some local state from my computer in version control and using it when I push changes to my CI system to build the docker image. I don't know how to clear this state to instruct Genie to re-render the view.

If I remove `*/build` from .gitignore and build a new image, this error is removed.

**Additional context**
```
julia> versioninfo()
Julia Version 1.7.3
Commit 742b9abb4d (2022-05-06 12:58 UTC)
Platform Info:
  OS: Linux (x86_64-pc-linux-gnu)
  CPU: Intel(R) Core(TM) i7-10850H CPU @ 2.70GHz
  WORD_SIZE: 64
  LIBM: libopenlibm
  LLVM: libLLVM-12.0.1 (ORCJIT, skylake)
Environment:
  JULIA_PKG_USE_CLI_GIT = true

(Propagando) pkg> st
     Project Propagando v0.1.0
      Status `~/src/propagando.jl/Project.toml`
  [c43c736e] Genie v5.15.2
  [a082159f] GenieDeployDocker v1.0.1
  [6d011eab] Inflector v1.0.1
  [eaed0597] JSpaceLibrary v0.16.1 `git@gitlab.internal.momentus.space:engineering/jspacelibrary.git#master`
  [5bab7191] SPICE v0.2.3
  [340e8cb6] SearchLight v2.10.0
  [ade2ca70] Dates
  [56ddb016] Logging
```

**Comment by essenciary** [comment]
@lazzarello I don't fully understand the issue. We have many Genie apps running inside docker files without any problems. Can you pass me the exact exception? And even better, the full log... Maybe it's not allowed to make the folder or write into it...

**Comment by essenciary** [comment]
Closing due to lack of feedback - please reopen if issue not solved.
