### ISSUE TITLE
Customize or External host or Ip binding with port

### ISSUE THREAD

**Issue by Noorul-fluree** [GenieFramework/Genie.jl#653]
**Problem**
I have tried to use Customize or External host or Ip binding with port in up() function in julia genie app for running the server But it always get bind  with the localhost ip or showing thr error:
ERROR: cannot bind to port; may already be in use or access denied

can you guys please help me with this

**Comment by essenciary** [comment]
What did you do? Can you share some code?

**Comment by Noorul-fluree** [comment]
Thank you for sure response @essenciary 

using Genie



route("/") do
    "INDEXXXXXXXXX"
end



route("/hello") do
    "Hello World"
end


up(host ="My_IP",port=9000 ,async=false )
This is the exact error that I am getting:when i running the server

LoadError: cannot bind to port; may already be in use or access denied

Also, i have tried using up() from the Command line but still shows the same error.

**Comment by essenciary** [comment]
Looks like port 9000 is not available (already used by some other app or service). Depending on your OS, there are tools to check what app is using a certain port. For a quick check just use a different port.

**Comment by Noorul-fluree** [comment]
I have tried different different port numbersr but still getting the same error.
Could you please help me with this

**Comment by essenciary** [comment]
@Noorul-fluree Can you pass me the output of 

```julia
julia> versioninfo()
```

**Comment by Noorul-fluree** [comment]
@essenciary yeah sure , 
Here you go
julia> versioninfo()
Julia Version 1.6.7
Commit 3b76b25b64 (2022-07-19 15:11 UTC)
Platform Info:
  OS: Windows (x86_64-w64-mingw32)
  CPU: Intel(R) Core(TM) i7-10510U CPU @ 1.80GHz
  WORD_SIZE: 64
  LIBM: libopenlibm
  LLVM: libLLVM-11.0.1 (ORCJIT, skylake)

**Comment by essenciary** [comment]
@Noorul-fluree Thanks. 
Can you try this to see what's using the port? 
https://www.howtogeek.com/28609/how-can-i-tell-what-is-listening-on-a-tcpip-port-in-windows/

**Comment by essenciary** [comment]
Also, can you share some minimum code that illustrates the issue - so I can check on my side?

**Comment by Noorul-fluree** [comment]
@essenciary Sure ,
i already provided the code 
but here again 
using Genie

route("/") do
"INDEXXXXXXXXX"
end

route("/hello") do
"Hello World"
end

up(host ="My_IP",port=9000 ,async=false )

**Comment by essenciary** [comment]
Oh, that's all the code? So you put that into a `.jl` script and run it and you get the port error?
What is the `host="My_IP"` thing?

**Comment by Noorul-fluree** [comment]
No, not there is lot of code but at this i am facing problem and everything is working fine. Even it locally running fine i.e. on localhost.
But when i am using external IP or HOST i am getting the above error.
up(host ="My_IP",port=9000 ,async=false )

about external IP/Host in up() function:
i have created an IP on Microsoft azure and on that i wanted to run web services on web but duee this i am not able to do it that

**Comment by Noorul-fluree** [comment]
Can't share that My_IP bcoz its confidential

**Comment by essenciary** [comment]
OK, well you can't connect to an external IP, which I presume you're doing. In general, in production, you need to start the app on '0.0.0.0' and some port -- and expose that ideally through a web proxy like Nginx.

**Comment by essenciary** [comment]
Closing this, feel free to reopen if you have more info.
