### ISSUE TITLE
Update static Genie pages (welcome, error, etc) and remove old Twitter Bootstrap CSS

### ISSUE THREAD

**Issue by jaysacco** [GenieFramework/Genie.jl#655]
In Genie 5, the version of twitter bootstrap is 3.3.5, the latest available is 5.3.  Per https://github.com/twbs/release, V3 was end of life on July 24, 2019, V4 was end of life January 1, 2023.  It seems appropriate to move onto version 5 sometime soon.

**Comment by essenciary** [comment]
We don't really use Twitter Bootstrap for anything related to user apps if I remember correctly. Do you have some specific example in mind?

**Comment by jaysacco** [comment]
I'm using bootstrap to style my Genie website.  If it's just being provided with Genie so Genie users don't need to get it themselves, then I'd just deprecate it from Genie.  There's no point in packaging something that's not going to be kept up to date.  I just loaded the latest version for myself.

**Comment by essenciary** [comment]
We used to rely on it in the initial versions, but since then multiple CSS frameworks have emerged so we're no longer officially supporting any CSS framework. It might still be used in some of the default error pages. I'll take a look and remove it in Genie 6.
