### ISSUE TITLE
404 on minimal tutorial example

### ISSUE THREAD

**Issue by markmbaum** [GenieFramework/Genie.jl#658]
**Describe the bug**
I'm interested in learning more about Genie so I was going through the tutorials. When I try to run the simplest [example](https://genieframework.com/docs/genie/v5.11/tutorials/Getting-Started.html#Example) I get a 404 error.

**Error stacktrace**

<img width="622" alt="Screenshot 2023-07-07 at 4 45 49 PM" src="https://github.com/GenieFramework/Genie.jl/assets/18745581/5970a553-862e-4f3c-b763-7a985e4f8aa6">

**To reproduce**
```julia
using Genie

route("/hello") do
    "Hello World"
end

up()
```

**Expected behavior**
I expected the local app to display something, not an error.

**Additional context**

version info:
```
Julia Version 1.8.5
Commit 17cfb8e65ea (2023-01-08 06:45 UTC)
Platform Info:
  OS: macOS (arm64-apple-darwin21.5.0)
  CPU: 10 × Apple M1 Pro
  WORD_SIZE: 64
  LIBM: libopenlibm
  LLVM: libLLVM-13.0.1 (ORCJIT, apple-m1)
  Threads: 1 on 8 virtual cores
```

environment:
```
  [39de3d68] AxisArrays v0.4.6
  [31c24e10] Distributions v0.25.98
  [ffbed154] DocStringExtensions v0.9.3
  [c43c736e] Genie v5.18.1
  [98e50ef6] JuliaFormatter v1.0.34
  [5e2c8b86] MultiAssign v0.1.0
  [90137ffa] StaticArrays v1.6.0
  [2913bbd2] StatsBase v0.34.0
  [3a884ed6] UnPack v1.0.2
  [b8865327] UnicodePlots v3.6.0
  [9a3f8284] Random
  [10745b16] Statistics
  [8dfed614] Test
```

**Comment by markmbaum** [comment]
this was my mistake

**Comment by essenciary** [comment]
No prob, leaving this in case other users have the same problem: you haven't registered any route to handle `/` (which you were accessing) - you registered a route for the `/hello` URL instead.
