### ISSUE TITLE
Passing variables to `html` renderer yields key not found error 

### ISSUE THREAD

**Issue by PGimenez** [GenieFramework/Genie.jl#670]
Trying the example from the API docs 
```julia 
html("<h1>Welcome $(vars(:name))</h1>", layout = "<div><% @yield %></div>", name = "Adrian")
```

Returns
```julia
ERROR: KeyError: key :name not found
Stacktrace:
 [1] getindex(h::Dict{Symbol, Any}, key::Symbol)
   @ Base ./dict.jl:484
 [2] vars(key::Symbol)
   @ Genie.Renderer ~/.julia/packages/Genie/Es7Db/src/Renderer.jl:449
 [3] top-level scope
   @ REPL[30]:1
```

Passing variables works fine if the page is in a file

```julia
route("/message") do
    name = "John"
    html(Renderer.filepath("message.jl"), name=name)
end
```
```julia [message.jl]
p("Hello $name")
```

**Comment by essenciary** [comment]
@PGimenez But in the first example you're using `$vars(:name)` - you should use `$name` like in the second example.

**Comment by PGimenez** [comment]
Yes I tried that too but it throws the same  `name not found` error

```julia
html("<h1>Welcome $name</h1>", layout = "<div><% @yield %></div>", name = "Adrian")
```

**Comment by essenciary** [comment]
Sure, because `$name` is evaluated before `html(...)`. `$name` has to be escaped/preserved-as-is to be used at render-time inside the view template. 

<img width="695" alt="image" src="https://github.com/GenieFramework/Genie.jl/assets/11292378/96c3c80d-c599-46f6-9397-57dc60ffd58a">

**Comment by PGimenez** [comment]
Yea I thought so..didn't think to escape the string though. I'll change the docstring to this.
