### ISSUE TITLE
hot reload not possible once application hit the error, it require new bootstrap even in GENIE_ENV=dev

### ISSUE THREAD

**Issue by vrkansagara** [GenieFramework/Genie.jl#671]
**To reproduce**
(1) run application with dev environment
(2) add route as per given image 
(3) refresh the browser 
(4) correct the route.jl file like remove every route except `/` route and see application is stuck

<img width="854" alt="image" src="https://github.com/GenieFramework/Genie.jl/assets/12006483/8f960176-3282-49a8-a125-01129e42f2dc">
<img width="506" alt="image" src="https://github.com/GenieFramework/Genie.jl/assets/12006483/b484ac9b-fff8-4723-a56c-52cce1879414">

**Comment by vrkansagara** [comment]
After reloading the new bootstrap, I still had the same issue.
<img width="907" alt="image" src="https://github.com/GenieFramework/Genie.jl/assets/12006483/2822bbed-dd8d-4333-8403-99c55dc31c45">

**Comment by PGimenez** [comment]
I've tried reproducing the hot-reload after an error issue and hot reloading works fine for me. What I've done:

- Start with this code and access the `/`path

```julia
using Genie
using Genie.Renderer.Html

route("/") do
    "Welcome"
end
#= route("/error") do =#
#=     html("Error?") =#
#= end =#
```

- Uncomment the second route and access `/error`. This throws a `html` not defined error
- Add `using Genie.Renderer.Html`to the top of the script and try `/error` again. This time it works

**Comment by PGimenez** [comment]
There's another thing, which I'm not sure you're doing to trigger an error on purpose. The `route` takes a function as first argument, not a rendered HTML string. With the `do...end` syntax we're passing an anonymous function to it. You can see the signatures here

```julia
julia> methods(route)
# 3 methods for generic function "route" from Genie.Router:
 [1] route(action::Function, path::String; method, named, context)
     @ ~/.julia/packages/Genie/Es7Db/src/Router.jl:236
 [2] route(path::String, action::Function; method, named, context)
     @ ~/.julia/packages/Genie/Es7Db/src/Router.jl:239
 [3] route(r::Genie.Router.Route)
     @ ~/.julia/packages/Genie/Es7Db/src/Router.jl:242
```

**Comment by PGimenez** [comment]
There's another thing, which I'm not sure you're doing to trigger an error on purpose. The `route` takes a function as first argument, not a rendered HTML string as the one returned y `html()`. With the `do...end` syntax we're passing an anonymous function to it. You can see the signatures here

```julia
julia> methods(route)
# 3 methods for generic function "route" from Genie.Router:
 [1] route(action::Function, path::String; method, named, context)
     @ ~/.julia/packages/Genie/Es7Db/src/Router.jl:236
 [2] route(path::String, action::Function; method, named, context)
     @ ~/.julia/packages/Genie/Es7Db/src/Router.jl:239
 [3] route(r::Genie.Router.Route)
     @ ~/.julia/packages/Genie/Es7Db/src/Router.jl:242
```
This is how you'd use it with a function parameter

```julia
using Genie
greet() = "Welcome to Genie!"
route("/greet", greet)          # [GET] /greet => greet
up() # start the server
```

**Comment by vrkansagara** [comment]
This is not happening with MVC framework that I can confirm.
