### ISSUE TITLE
Error reporting dumps sensitive information

### ISSUE THREAD

**Issue by banachtech** [GenieFramework/Genie.jl#674]
Hello -

First time Genie user here. While trying out the Juliacon 2003 demo (API page implementation), I encountered some errors. The error message dumped on the HTML page accessing the REST API had the full stack trace and sensitive environment variable data under the header JULIA ENV. 

Is this info being shared elsewhere via telemetry? Am I missing any security setting to avoid this dump? 

Thanks.

**Comment by essenciary** [comment]
@banachtech 
1/ this info is not shared with anybody
2/ the dump is enable in dev and test environments for debugging purposes. When you run the application in `prod` this page and the data is disabled.

**Comment by essenciary** [comment]
We can probably disable the dump of JULIA ENV in v6 anyway -- I don't find it useful tbh.

**Comment by banachtech** [comment]
Thanks for the prompt reply.
