### ISSUE TITLE
index-base transation missing.

### ISSUE THREAD

**Issue by XLin0mu** [GenieFramework/Genie.jl#680]
`ar[0]` can work, besides `ar[1]` make errors.
In my opinion it's very anti-intuition for Julia users.
MRE as bellow:
```julia
using GenieFramework
@genietools

ar = [1]

@app begin
    @in ar
end

function pp()
    [
        textfield("test", Symbol("ar[0]"))
    ]
end;

@page("/", pp)
up()
```
And my Genie.jl version is as follow:
```julia
(@v1.9) pkg> st Genie
Status `C:\Users\XLin0mu\.julia\environments\v1.9\Project.toml`
  [c43c736e] Genie v5.19.1

(@v1.9) pkg> st GenieFramework
Status `C:\Users\XLin0mu\.julia\environments\v1.9\Project.toml`
  [a59fdf5c] GenieFramework v1.23.0
```

**Comment by PGimenez** [comment]
This is because reactive variables behave as Javascript variables in the browser, which are 0-indexed. I've added this information to the docs
https://learn.genieframework.com/reference/reactive-ui/caveats
