### ISSUE TITLE
How to make the new Genie work behind nginx

### ISSUE THREAD

**Issue by MariusDrulea** [GenieFramework/Genie.jl#700]
With the old genie syntax the set-up is described here: https://genieframework.github.io/Genie.jl/dev/tutorials/92--Deploying_Genie_Server_Apps_with_Nginx.html
I have played a bit with the above setting and I was able to make genie and nginx work to serve a static html page, as generated by the `newapp` method.

However, with the new syntax `module App, ui(), @page("/", ui), GenieFramework`, this does not seem to work. I do only get an empty page through nginx. Although the page is empty, the page source indicate the content is there, but is hidden for some reason. Also the nginx side often reports lost connection to the genie side, as you can see in the picture.

Additionally, the new documentation contains no reference to setting-up nginx and genie: https://learn.genieframework.com/docs/guides/deploying-genie-apps.

![image](https://github.com/GenieFramework/Genie.jl/assets/27725572/65f8cebf-1e3b-4e9c-b5d4-2f76abb72dec)

**Comment by MariusDrulea** [comment]
There is a description in the new doc: https://learn.genieframework.com/docs/reference/workflow/nginx-reverse-proxy.
I propose to add a link to this config also here: https://learn.genieframework.com/docs/guides/deploying-genie-apps

**Comment by MariusDrulea** [comment]
Ok, and I don't have an welcome.html index webpage, as my webpage is created this way:
```julia
    function ui()
          ...........
    end
    @page("/", ui)
```

So what to add here?
```
server {
  server_name   test.com;
  root          /home/ubuntu/MyGenieApp/public;
  index         welcome.html; # <----------------------------------------------------------
}
```

**Comment by essenciary** [comment]
@MariusDrulea What was the issue with the blank page? Sounds like no sockets access maybe?

**Comment by essenciary** [comment]
FYI @PGimenez

**Comment by MariusDrulea** [comment]
> @MariusDrulea What was the issue with the blank page? Sounds like no sockets access maybe?

I've seen some comment about Genie v6 using HTTP instead of websockets. Is this correct?

**Comment by essenciary** [comment]
> > @MariusDrulea What was the issue with the blank page? Sounds like no sockets access maybe?
> 
> I've seen some comment about Genie v6 using HTTP instead of websockets. Is this correct?

Web sockets is the most efficient method for real-time data sync and it's the default. There is AJAX (HTTP) fallback available (it's been available for a couple of years), mostly to be used with hosting that doesn't allow web sockets. We're also working on adding SSE support - it's already available in Genie (v5) for implementing routes and handlers over SSE. But there is no support yet for Stipple data sync.

**Comment by PGimenez** [comment]
@MariusDrulea @awojtas-r, I believe the issue here is that NGINX is not configured to handle websockets. Here's how to get it working:
1. Set the `BASEPATH`env variable to the desired path prefix, e.g., BASEPATH="/genieapp"
2. Add websocket-specific configuration to the nginx config:
```bash
server {
  listen 80;
  listen [::]:80;

  server_name   test.com;
  root          /home/ubuntu/MyGenieApp/public;
  index         welcome.html;

  location /genieapp/ {
      proxy_pass http://localhost:8000/;
      #websocket specific settings
      proxy_set_header Upgrade $http_upgrade;
      proxy_set_header Connection "upgrade";
      proxy_set_header Host $host;
  }
}
```

**Comment by MariusDrulea** [comment]
@PGimenez thanks for the update.

The above setting works nicely when we use `test.com/genieapp`. However, `localhost:8000` no longer finds the css files and the page is without styling. And this is because the style files have the following link: `link href="[/genieapp/stipple.jl/v0.27.17/assets/css/stipplecore.css]`. However, this link only works fine through nginx and through localhost.

So, how can we make both links work?

**Comment by MariusDrulea** [comment]
If I don't set the env basepath and in nginx have `location / {...}`, then both `test.com` and `localhost:8000` do work nicely. So it seems to me genie shall be able to handle a `/genieapp` basepath.

**Comment by PGimenez** [comment]
When the BASEPATH var is set, all links generated by the app will have a base path inserted. When the user browser requests a link, the reverse proxy will look at the base path and direct the request to the appropriate app. If you intend to access the app directly instead of through the reverse proxy, you have to remove the BASEPATH variable.

There's no way for the Genie app to handle routes with basepath and without at the same time. I believe this is the same for every framework out there. The way I do it is:

- Don't set the BASEPATH during development so that I can access the app at localhost:8000/
- Configure the BASEPATH when deploying since the app will be behind a reverse proxy

**Comment by PGimenez** [comment]
Another thing, make sure that all links pointing to routes or assets in your app have the base path prefix. You can use `Router.link_to`to automatically handle this:

```julia
julia> @page("/foo/bar/baz", "nop")
julia> routes()
10-element Vector{Genie.Router.Route}:
 [GET] /foo/bar/baz => #5 | :get_foo_bar_baz
julia> [Router.to](http://router.to/)_link(:get_foo_bar_baz)
"/foo/bar/baz"
julia> Genie.config.base_path = "/my/hosting/thing"
"/my/hosting/thing"
julia> [Router.to](http://router.to/)_link(:get_foo_bar_baz)
"/my/hosting/thing/foo/bar/baz"
```

For example, we use this in the navigation links of the [multipage app demo](https://github.com/BuiltWithGenie/MultiPageApp/blob/main/layout.jl):
```html
cell(style="display: flex; justify-content: space-between; align-items: center; background-color: #112244; padding: 10px 50px; color: #ffffff; top: 0; width: 100%; box-sizing: border-box;", [
    cell(style="font-size: 1.5em; font-weight: bold;",
        "Genie workshop"
    ),
    Html.div(style="display: flex; gap: 20px;", [
        a(href="$(Router.link_to(:get_eda))", style="text-decoration: none; color: #ffffff;",
            "Exploratory data analysis"
        ),
        a(href="$(Router.link_to(:get_ml))", style="text-decoration: none; color: #ffffff;",
            "Neural network training"
        ),
        a(href="$(Router.link_to(:get_api))", target="_blank", style="text-decoration: none; color: #ffffff;",
            "API"
        )
    ])
])
```

I'll add this info to the NGINX page in the docs

**Comment by PGimenez** [comment]
@MariusDrulea can we close this issue?

**Comment by MariusDrulea** [comment]
The setup works, the issue is fully solved.
