### ISSUE TITLE
Automatically refresh on browser as per react apps?

### ISSUE THREAD

**Issue by scheung38** [GenieFramework/Genie.jl#97]
But how do we automatically refresh when code changes without manually hitting the refresh button on browser as per react apps?

**Comment by essenciary** [comment]
This feature is not available yet. It has to be built. 
You can use a 3rd party tool like LiveReload (http://livereload.com) although you might have to write a custom plugin to support working with '.jl' files.

**Comment by tlienart** [comment]
Just chipping in here, [LiveServer.jl](https://github.com/asprionj/LiveServer.jl) might be useful here to trigger browser reloads. You might want to have your own logic for what triggers reloads but that shouldn't be hard (happy to help if you think it could be useful).

**Comment by essenciary** [comment]
@tlienart Does it work with `.jl` files? The idea is to monitor the various MVC files and reload. The thing is, `Revise.jl` already does this monitoring so ideally it should be integrated with `Revise.jl`. I opened a feature request for Revise a while ago, to be able to register hooks to be notified when Revise recompiles a file - it should be coupled with this.

**Comment by tlienart** [comment]
> @tlienart Does it work with `.jl` files? The idea is to monitor the various MVC files and reload.

Yes.

I know Revise can do the file tracking, we use our own FileWatcher but Tim Holy told us we could have used Revise as well. At the end of the day the effect is the same except that our FileWatcher is trivial to adjust to your case (effectively you can write it yourself following a template) and we do have the callback baked in that will trigger browser reloads.

This is just a suggestion though :)

**Comment by essenciary** [comment]
Thank you @tlienart sounds really good! To be honest though, I'm tempted to give Revise a try as it's already deeply integrated with Genie. Besides avoiding another dependency, it also avoids adding a second file watcher (which concerns me more...).

**Comment by essenciary** [comment]
Published a first version of the GenieAutoreload plugin at https://github.com/GenieFramework/GenieAutoreload

Docs pending
